### ISSUE TITLE
Narrator ignores IsCheckable on RibbonMenuButtonItem

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#641] opened 2019-05-03 19:00 UTC
<p>Expected:</p><p>If you set IsCheckable=false, the menu item should not be read in Narrator as checked or un-checked.</p><p>Actual: </p><p>No matter how IsCheckable is set, Narrator interprets RibbonMenuButtonItems as checkable controls and tries to read them accordingly.  </p><p>Repro:</p><p>Here’s a xaml sample that will exhibit the issue in
Narrator:</p><p>&lt;Window x:Class=&quot;RibbonBug.MainWindow&quot;</p><p> xmlns=&quot;<a href="https://nam06.safelinks.protection.outlook.com/?url=http://schemas.microsoft.com/winfx/2006/xaml/presentation&amp;data=04%7c01%7cChris.Sires%40microsoft.com%7c219b2370283d4d59c91408d69071900c%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636855215066474038%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c-1&amp;sdata=PAasQVsCWK8bI1A/57xntBvRXtG52XMj2Fs%2BGO80kuk%3D&amp;reserved=0">http://schemas.microsoft.com/winfx/2006/xaml/presentation</a>&quot;</p><p> xmlns:x=&quot;<a href="https://nam06.safelinks.protection.outlook.com/?url=http://schemas.microsoft.com/winfx/2006/xaml&amp;data=04%7c01%7cChris.Sires%40microsoft.com%7c219b2370283d4d59c91408d69071900c%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636855215066484046%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c-1&amp;sdata=e1F2pjph5hn96Lw9ZYqk7fVB7U7cZwS0/clgJSFrY0k%3D&amp;reserved=0">http://schemas.microsoft.com/winfx/2006/xaml</a>&quot;</p><p> xmlns:d=&quot;<a href="https://nam06.safelinks.protection.outlook.com/?url=http://schemas.microsoft.com/expression/blend/2008&amp;data=04%7c01%7cChris.Sires%40microsoft.com%7c219b2370283d4d59c91408d69071900c%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636855215066494054%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c-1&amp;sdata=itcYEd7%2By4hto3QmKwP4BXSw4zP59qJUvtsBUjCDLwA%3D&amp;reserved=0">http://schemas.microsoft.com/expression/blend/2008</a>&quot;</p><p> xmlns:mc=&quot;<a href="https://nam06.safelinks.protection.outlook.com/?url=http://schemas.openxmlformats.org/markup-compatibility/2006&amp;data=04%7c01%7cChris.Sires%40microsoft.com%7c219b2370283d4d59c91408d69071900c%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636855215066524083%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c-1&amp;sdata=5t%2BiLellbX6vVv%2ByvYBn%2B1ICEyfQCY4A5wYxoBKKMs8%3D&amp;reserved=0">http://schemas.openxmlformats.org/markup-compatibility/2006</a>&quot;</p><p> xmlns:local=&quot;clr-namespace:RibbonBug&quot;</p><p> mc:Ignorable=&quot;d&quot;</p><p> Title=&quot;MainWindow&quot; Height=&quot;450&quot; Width=&quot;800&quot;&gt;</p><p>&lt;Grid&gt;</p><p>&lt;Ribbon Title=&quot;Ribbon
Title&quot;&gt;</p><p>&lt;RibbonMenuButton Label=&quot;RibbonMenuButton
Label&quot;&gt;</p><p>&lt;!--
bug: IsCheckable has no effect on Narrator's output the item is still checked
or unchecked --&gt;</p><p>&lt;RibbonMenuItem IsCheckable=&quot;False&quot; Header=&quot;RibbonMenuButtonItem
Header&quot; /&gt;</p><p>&lt;/RibbonMenuButton&gt;</p><p>&lt;/Ribbon&gt;</p><p>&lt;/Grid&gt;</p><p>&lt;/Window&gt;</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/451536/narrator-ignores-ischeckable-on-ribbonmenubuttonit.html
VSTS ticketId: 790539_
_These are the original issue comments:_

Visual Studio Feedback System on 2/12/2019, 07:10 PM (79 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by grubioe** [comment] 2019-05-30 16:06
Closing as duplicate of #349

**Closed by grubioe** 2019-05-30 16:06 UTC
Labels: vsfeedback
