### ISSUE TITLE
Calendar day binding not working

### ISSUE THREAD

**Issue by tanpuresiddhant** [dotnet/wpf#2120] opened 2019-10-25 21:35 UTC
1. Open VS 2019
2. Create new WPF Core app.
3. Open MainWindow.xaml.
4. Replace Grid element with XAML below..
<Grid>
    <Grid.RowDefinitions>
        <RowDefinition Height="44*"/>
        <RowDefinition Height="49*"/>
        <RowDefinition Height="43*"/>
        <RowDefinition Height="298*"/>
    </Grid.RowDefinitions>

    <Grid.ColumnDefinitions>
        <ColumnDefinition Width="83*"/>
        <ColumnDefinition Width="317*"/>
    </Grid.ColumnDefinitions>
        <Label Grid.Row="0" Grid.Column="0" x:Name="label1" Content="year:" Grid.ColumnSpan="2" Grid.RowSpan="4" />
        <TextBlock Grid.Row="0" Grid.Column="1" x:Name="textBlock1" Text="{Binding DisplayDate.Year, ElementName=datePicker, Mode=OneWay}" Grid.ColumnSpan="2" Grid.RowSpan="4" />
        <Label Grid.Row="1" Grid.Column="0" x:Name="label2" Content="Month:" Grid.ColumnSpan="2" Grid.RowSpan="4"/>
        <TextBlock Grid.Row="1" Grid.Column="1" x:Name="textBlock2" Text="{Binding DisplayDate.Month, ElementName=datePicker, Mode=OneWay}" Grid.ColumnSpan="2" Grid.RowSpan="4"/>
        <Label Grid.Row="2" Grid.Column="0" x:Name="label3" Content="Day:" Grid.ColumnSpan="2" Grid.RowSpan="4" />
        <TextBlock Grid.Row="2" Grid.Column="1" x:Name="textBlock3"  Grid.ColumnSpan="2" Grid.RowSpan="4" Text="{Binding DisplayDate.Day, ElementName=datePicker, Mode=OneWay}" />
        <DatePicker Grid.Row="3" Grid.Column="1" x:Name="datePicker" Grid.ColumnSpan="2" Grid.RowSpan="4" Height="100" Width="100"/>
        <Button/>
    </Grid>
6. F5
7. Change date from the calendar to some other date

Actual: Textbox "textBlock3" text doesn't update to new date 
Expected: Textbox "textBlock3" text updates to new date

**Comment by miloush** [comment] 2019-10-27 17:59
Duplicate of #451

**Comment by arpitmathur** [comment] 2019-10-29 18:49
Verify if this is a dupe of #451 and reproduces in framework?

**Comment by SamBent** [comment] 2019-10-29 19:38
This is not a bug, and not a dupe of #451.  

[DisplayDate](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.datepicker.displaydate?view=netframework-4.8) is "the date to display", meaning that when the calendar is open the given date appears in the main section (e.g. if the calendar is in Month mode, it displays the month containing the given date) .  Selecting another date doesn't change DisplayDate, unless needed to display the new selected date.  

To get the behavior I think you want, your bindings should refer to SelectedDate;  that's the property that changes when you choose a new date.   (Keeping in mind that SelectedDate is initially null.)

**Closed by SamBent** 2019-10-29 19:38 UTC
Labels: issue-type-bug
