### ISSUE TITLE
WPF .NET 5 app won't build when having service reference to gRPC from another project. "Done executing task "Csc" -- FAILED."

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5644] opened 2021-11-05 16:09 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/WPF-NET-5-app-wont-build-when-having-s/1257533?preview=true)._

---
[severity:It bothers me. A fix would be nice]
     Done executing task "Csc" -- FAILED.
3>        Done building target "CoreCompile" in project "SyriliumRiF.WinForms.FWK_bqdegipv_wpftmp.csproj" -- FAILED.
3>
3>        Done building project "SyriliumRiF.WinForms.FWK_bqdegipv_wpftmp.csproj" -- FAILED.
3>      Done executing task "GenerateTemporaryTargetAssembly" -- FAILED.
3>    Target _CheckForCompileOutputs:
3>    Target "_SGenCheckForOutputs" skipped, due to false condition; ('$(_SGenGenerateSerializationAssembliesConfig)' == 'On' or ('@(WebReferenceUrl)'!='' and '$(_SGenGenerateSerializationAssembliesConfig)' == 'Auto')) was evaluated as ('Off' == 'On' or (''!='' and 'Off' == 'Auto')).
3>    Target _CleanGetCurrentAndPriorFileWrites:
3>      Using "ReadLinesFromFile" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
3>      Task "ReadLinesFromFile"
3>      Done executing task "ReadLinesFromFile".
3>      Using "ConvertToAbsolutePath" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
3>      Task "ConvertToAbsolutePath"
3>      Done executing task "ConvertToAbsolutePath".
3>      Using "FindUnderPath" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
3>      Task "FindUnderPath"
3>        Comparison path is "C:\Programming\SyriliumRiF\Main\SyriliumRiF.WinForms.FWK".
3>      Done executing task "FindUnderPath".
3>      Task "FindUnderPath"
3>        Comparison path is "bin\Debug\".
3>      Done executing task "FindUnderPath".
3>      Task "FindUnderPath"
3>        Comparison path is "obj\Debug\".
3>      Done executing task "FindUnderPath".
3>      Using "RemoveDuplicates" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
3>      Task "RemoveDuplicates"
3>      Done executing task "RemoveDuplicates".
3>    Target _CleanRecordFileWrites:
3>      Task "RemoveDuplicates"
3>      Done executing task "RemoveDuplicates".
3>      Task "MakeDir"
3>      Done executing task "MakeDir".
3>      Using "WriteLinesToFile" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
3>      Task "WriteLinesToFile"
3>      Done executing task "WriteLinesToFile".
3>
3>    Done building project "SyriliumRiF.WinForms.FWK.csproj" -- FAILED.
3>  Done executing task "MSBuild" -- FAILED.
3>
3>Done building project "SyriliumRiF.MSIX.wapproj" -- FAILED.

Referencing gRPC project directly and not by proto gen solved the problem for now.

---
#### Feedback Bot on 11/16/2020, 06:45 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 2/19/2021, 10:06 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by singhashish-wpf** [comment] 2022-07-11 11:16
Is this reproducible in .NET 6 app as well?

**Comment by singhashish-wpf** [comment] 2023-02-08 05:29
Closing as not further information was provided since long.

**Closed by singhashish-wpf** 2023-02-08 05:29 UTC
Labels: needs more information
