### ISSUE TITLE
x:Reference does not seem to be supported

### ISSUE THREAD

**Issue by ccifra** [dotnet/wpf#156] opened 2018-12-11 20:57 UTC
* .NET Core Version: 3.0.100-preview-009812
* Windows version: 10.0.18298
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 **Problem description:**
We are using x:Reference in some of the XAML that we are trying to port from .NET Framework WPF to .NET Core WPF and when building under .NET Core we a build error:

```
error MC3074: The tag 'Reference' does not exist in XML namespace  'http://schemas.microsoft.com/winfx/2006/xaml'.
 ```
We are using X:Reference to set a converter parameter from a ControlTemplate like this:

``` XML
Value="{Binding SelectedColor, Mode=TwoWay, RelativeSource={RelativeSource TemplatedParent}, Converter={StaticResource RedToColorConverter}, ConverterParameter={x:Reference PART_HexInput}}"
```

 **Expected behavior:**
 x:Reference should be a supported construct

 **Minimal repro:**
I can create one if needed

**Comment by dotMorten** [comment] 2018-12-11 20:59
I'm curious if that's caused by #119 ?

**Comment by stevenbrix** [comment] 2018-12-13 18:12
Duplicate of #119 

@ccifra i'm going to close this and ensure that #119 tracks this issue as well. Thank you for opening this!

**Closed by stevenbrix** 2018-12-13 18:12 UTC
