### ISSUE TITLE
During multi-touch, lifting primary touch point before non-primary points crashes.

### ISSUE THREAD

**Issue by grubioe** [dotnet/wpf#742] opened 2019-05-23 17:27 UTC
Copied from VSO ID: 672856

 **Problem description: & Repro Steps**
===================================
Run the attached touch move test application against .NET Core 3 WPF builds.

Touch down with multiple touch points.  Ensure that you lift the primary (first down) finger prior to any non-primary point.

Observe the following crash:

at System.Windows.Input.StylusWisp.WispLogic.PromoteMainToMouse(StagingAreaInputItem stagingItem)
   at System.Windows.Input.StylusWisp.WispLogic.PromoteMainUpToTouch(WispStylusDevice stylusDevice, StagingAreaInputItem stagingItem)
   at System.Windows.Input.StylusWisp.WispLogic.PromoteMainToTouch(ProcessInputEventArgs e, StylusEventArgs stylusEventArgs)
   at System.Windows.Input.StylusWisp.WispLogic.PromoteMainToOther(ProcessInputEventArgs e)
   at System.Windows.Input.StylusWisp.WispLogic.PostProcessInput(Object sender, ProcessInputEventArgs e)
   at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(ProcessInputEventHandler postProcessInput, ProcessInputEventArgs processInputEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.StylusWisp.WispLogic.InputManagerProcessInputEventArgs(InputEventArgs input)
   at System.Windows.Input.StylusWisp.WispLogic.InputManagerProcessInput(Object oInput)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.WrappedInvoke(Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.WrappedInvoke(Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, Object arg)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.TranslateAndDispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at MovePerfTester.App.Main()
 
 
[TouchMoveSample.zip](https://github.com/dotnet/wpf/files/3213428/TouchMoveSample.zip)

Initial Investigation:
===============
There is a debug assert that fails in this code path.  Something about either NetCore3 or SxS COM is causing this prior assumption to be invalid.

When tested in the netfxdev1 SxS COM prototype, this failure did not occur, leading me to believe this is something to do with NetCore3.

**Comment by rladuca** [comment] 2019-07-16 20:17
Initial investigation shows this no longer reproduces.

I've currently only tested this on a Surface Studio, but will add some other touch devices before being satisfied that this will not reproduce.

Unfortunately I don't quite know why this happened in the first place.  It was discovered very early on in the dev cycle for .NET Core 3 so something underneath the input stack could have changed to fix this.

@ryalanms I'm going to attempt to reproduce #38 while I am at it, since these are the 2 touch issues we discovered immediately after swapping to SxS COM.

**Comment by rladuca** [comment] 2019-07-19 00:39
I tried this on three different touch screens and I cannot reproduce it.

Something seems to have been fixed since.

As such, closing this out.  Perhaps we will find a repro and re-open, but it seems unlikely.

**Closed by rladuca** 2019-07-19 00:39 UTC
Labels: issue-type-bug, rank20, regression
