### ISSUE TITLE
WPF for .NET Core throws first chance exceptions due to .NET Core limitations

### ISSUE THREAD

**Issue by AArnott** [dotnet/wpf#2395] opened 2020-01-03 22:51 UTC
* .NET Core Version: 3.1
* Windows version: 1909
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 **Problem description:**

WPF for .NET Core throws a multiple first-chance exceptions during startup because AppSettings isn't available on .NET Core. 

https://github.com/dotnet/wpf/blob/24faa3f5afce57898fdd52f0f2de92c5ef5b444e/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/CoreCompatibilityPreferences.cs#L23
 
 **Actual behavior:** 

```
System.Configuration.ConfigurationErrorsException
  HResult=0x80131902
  Message=Configuration system failed to initialize
  Source=System.Configuration.ConfigurationManager
  StackTrace:
   at System.Configuration.ConfigurationManager.PrepareConfigSystem() in /_/src/System.Configuration.ConfigurationManager/src/System/Configuration/ConfigurationManager.cs:line 150

  This exception was originally thrown at this call stack:
    System.Configuration.ClientConfigPaths.ClientConfigPaths(string, bool) in ClientConfigPaths.cs
    System.Configuration.ClientConfigPaths.GetPaths(string, bool) in ClientConfigPaths.cs
    System.Configuration.ClientConfigurationHost.ConfigPaths.get() in ClientConfigurationHost.cs
    System.Configuration.ClientConfigurationHost.GetStreamName(string) in ClientConfigurationHost.cs
    System.Configuration.ClientConfigurationHost.IsAppConfigHttp.get() in ClientConfigurationHost.cs
    System.Configuration.Internal.DelegatingConfigHost.IsAppConfigHttp.get() in DelegatingConfigHost.cs
    System.Configuration.ClientConfigurationSystem.ClientConfigurationSystem() in ClientConfigurationSystem.cs
    System.Configuration.ConfigurationManager.EnsureConfigurationSystem() in ConfigurationManager.cs

Inner Exception 1:
PlatformNotSupportedException: Operation is not supported on this platform.
```
 
 **Expected behavior:**
 
I expect WPF for .NET Core avoids calling APIs that are known to not work on .NET Core so that these first chance exceptions aren't thrown.

**Comment by AArnott** [comment] 2020-01-03 23:22
This also appears in `FrameworkCompatibilityPreferences`:

https://github.com/dotnet/wpf/blob/24faa3f5afce57898fdd52f0f2de92c5ef5b444e/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/FrameworkCompatibilityPreferences.cs#L35

**Comment by ericstj** [comment] 2020-01-06 17:16
/cc @JeremyKuhne @maryamariyan 

AppSettings should be usable on .NETCore, though we wouldn't recommend building things around it.  @AArnott it looks like you're hitting this:
https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ClientConfigPaths.cs#L49-L56

Perhaps you're hitting this because the way you're hosting CoreCLR doesn't set EntryAssembly?  That might be something to try to root cause here: I suspect other things might fallout of this.

**Comment by AArnott** [comment] 2020-01-06 17:41
Oh, quite possibly. I'll see if I can figure out how to set that EntryAssembly property. So far the only property I'm setting is `APP_CONTEXT_BASE_DIRECTORY`, and I'm discovering properties I need to set as I go. Is there a complete list of properties that may need setting in a custom .NET Core host?

**Comment by ericstj** [comment] 2020-01-06 17:58
Looks to be the issue discussed here: https://github.com/dotnet/corefx/issues/27091.  I couldn't find any hook to set EntryAssembly.  As @jkotas mentioned it's only set on the appdomain when [ExecuteMainMethod](https://github.com/dotnet/runtime/blob/e695a98652b23486a76ab4df31291bdf33862e19/src/coreclr/src/vm/assembly.cpp#L1668) is called.

**Comment by rladuca** [comment] 2020-01-08 21:17
Thanks @ericstj for checking into it.

@AArnott WPF isn't going to change that code in any significant fashion unless there is an overriding need to.  There are significant switches that help ensure backward compatibility with .NET Framework and minimize problems with porting to .NET Core that we want to preserve.  All of these are based around ConfigurationManager.

I'm going to close this as there doesn't seem like any actions for WPF here.

**Closed by rladuca** 2020-01-08 21:17 UTC
Labels: issue-type-tracking-external

**Comment by ivan2007** [comment] 2021-02-15 21:36
Hi, 
I have a similar issue with a win32 app that calls a c++/cli NET Core 3.1 lib. The c++/cli lib calls a WPF NET Core 3.1 lib.
The exceptions are:
'System.PlatformNotSupportedException' in System.Configuration.ConfigurationManager.dll
'System.Configuration.ConfigurationErrorsException' in System.Configuration.ConfigurationManager.dll
You can find more details [here](https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/306)

**Comment by ryalanms** [comment] 2021-02-16 22:35
Hi, @ivan2007.  Can you attach your information to this https://github.com/dotnet/runtime/issues/25027?  This is a runtime issue.  Thanks.

**Comment by ivan2007** [comment] 2021-02-16 22:43
Hi @ryalanms, I can't attach my information because the issue dotnet/runtime#25027 is locked

**Comment by SamBent** [comment] 2021-02-17 00:13
@ivan2007 Then open a new issue in dotnet/runtime.  It looks like the problem was fixed in .NET 5.0, but you need the fix in 3.1.  WPF cannot help you - it's a runtime issue.

**Comment by ericstj** [comment] 2021-02-17 01:51
Even with that exception, I suspect it is caught and handled.  If you aren't trying to use an app.exe.config file you're likely fine and not impacted by the config-system's failure to locate the config file.  Those are just first chance exceptions that clutter the debug output.

@SamBent / @ryalanms WPF could eliminate it's use of ConfigurationManager.  Of course that would be something to consider in a future version.

**Comment by ivan2007** [comment] 2021-02-17 21:56
@SamBent I opened a new [issue](https://github.com/dotnet/runtime/issues/48423) in dotnet/runtime
I confirm that the issue is not present with NET 5.0 but for now I can't migrate so it would be nice to have a fix for NET Core
