### ISSUE TITLE
Error NETSDK1022: Duplicate 'Page' items were included. by build a solution

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5639] opened 2021-11-05 16:05 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Error-NETSDK1022:-Duplicate-Page-items/1147022)._

---
[severity:Accessibility concern]
I'm making a WPF class library, but I have one problem with StaticResources. On the Internet, I found this information https://github.com/jbe2277/waf/wiki/WPF-Design-Time-Support-(Part-2). Now I can work with resources at the library. But I have an error when I build solution. 
"Error NETSDK1022: Duplicate 'Page' items were included. The .NET SDK includes 'Page' items from your project directory by default. You can either remove these items from your project file, or set the 'EnableDefaultPageItems' property to 'false' if you want to explicitly include them in your project file. For more information, see https://aka.ms/sdkimplicititems. The duplicate items were: 'Properties\DesignTimeResources.xaml'"

---
#### Feedback Bot on 8/12/2020, 07:29 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/20/2020, 01:42 AM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by sobujbd** [comment] 2022-07-14 08:27
I'm also getting this error on build,
 #### `Microsoft.NET.Sdk.WindowsDesktop.targets(111, 5): [NETSDK1022] Duplicate 'Page' items were included. The .NET SDK includes 'Page' items from your project directory by default. You can either remove these items from your project file, or set the 'EnableDefaultPageItems' property to 'false' if you want to explicitly include them in your project file. For more information, see https://aka.ms/sdkimplicititems. The duplicate items were: 'Properties\DesignTimeResources.xaml'`

What more information do you need?

**Comment by miloush** [comment] 2022-07-28 23:07
This is by design of the new .NET SDK and all the information to fix it is in the error message: _You can either remove these items from your project file, or set the 'EnableDefaultPageItems' property to 'false' if you want to explicitly include them in your project file._

**Comment by miloush** [comment] 2022-07-28 23:09
Documented here: https://docs.microsoft.com/en-US/dotnet/core/project-sdk/msbuild-props-desktop

**Comment by dipeshmsft** [comment] 2022-08-23 12:07
Closing this issue as this is by design in .NET SDK.

**Closed by dipeshmsft** 2022-08-23 12:07 UTC
Labels: needs more information
