### ISSUE TITLE
Cross Platform support

### ISSUE THREAD

**Issue by eq7755** [dotnet/wpf#804] opened 2019-06-01 12:01 UTC
Is there any plan to make WPF with cross platform? This is a very useful and promising feature, isn't it? Thanks for the WPF team of MS.

**Comment by rladuca** [comment] 2019-06-01 13:48
@eq7755 This is a duplicate of #48.  We've outline our position on cross-platform clearly in[ this comment](https://github.com/dotnet/wpf/issues/48#issuecomment-444198305) and there is a good amount of community discussion as well that you might find interesting.

Closing as dupe of #48.

**Closed by rladuca** 2019-06-01 13:48 UTC
