### ISSUE TITLE
Code behind references Microsoft.Windows.Themes failing in Preview 9 

### ISSUE THREAD

**Issue by Sybren-** [dotnet/wpf#1818] opened 2019-09-09 09:20 UTC
.NET Core Version 3.0.100-preview9-014004
Windows 10
Visual Studio 2019 Professional 16.2.4

Preview 9 build fixed the issue with referencing Microsoft.Windows.Themes in XAML https://github.com/dotnet/wpf/issues/1655

Given the following code:

`using Microsoft.Windows.Themes;`
`private static bool IsValidOriginalSource(object dragSource)
        {
            if (dragSource is ScrollBar || dragSource is ScrollChrome)
            {
                return false;
            }
        }`

I get the error:

CS0433	The type 'ScrollChrome' exists in both 'PresentationFramework.Aero, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'	

Do I have to work with 'extern alias' (there seems no support for it in .NET Core)?
How to fix the above issue?

**Comment by grubioe** [comment] 2019-09-10 18:12
Dependent on https://github.com/dotnet/designs/pull/81

**Comment by grubioe** [comment] 2019-10-08 23:28
Closing as a dupe of #765

**Closed by grubioe** 2019-10-08 23:28 UTC
Labels: issue-type-bug, issue-type-tracking-external, rank20, regression, tenet-adoption, tenet-compatibility
