### ISSUE TITLE
ToolTip immediately closed when showing in Button while project create with .Net 6

### ISSUE THREAD

**Issue by vijayarasan** [dotnet/wpf#6283] opened 2022-03-18 15:06 UTC
* .NET Core Version: 6.0
 
 **Problem description:**
 I am using button and defined the tooltip like below mentioned code snippet,
```XML  
<Button x:Name="btn"  Content="Button"  Width="150" Height="30" >
            <ToolTipService.ToolTip>
                <ToolTip Background="#FFDB000C" Content="Hello" />
            </ToolTipService.ToolTip>
 </Button>
```

When hovering to the button ToolTip immediately disappear. The reported problem occurs while using with VS2022 Preview, Scaling 150 and .Net 6.0. 
 
 I have also set the ShowDuration and InitialDelayDuration, but no effect.
 
 **Note :** The reported problem does not occurs in .Net 5.0 
 
 **Actual behavior:** 
 ToolTip immediately closed when showing in Button while project create with .Net 6
 
 **Expected behavior:**
 ToolTip properly display when showing in Button while project create with .Net 6

**Sample Link:**  [ToolTipDemo.zip](https://github.com/dotnet/wpf/files/8305470/ToolTipDemo.zip)

Can you please check and share any idea to resolve this issue?

**Comment by ryoasai** [comment] 2022-03-18 23:39
This is related to #6220 and https://github.com/dotnet/core/issues/7268

**Comment by SamBent** [comment] 2022-03-24 19:53
Closing this as a dupe of #6220.

**Closed by SamBent** 2022-03-24 19:53 UTC
Labels: Untriaged, Requires WPF team triage
