### ISSUE TITLE
When UseWPF set True in a WinForms. Proj fails to recognize ApplicationConfiguration bootstrap code

### ISSUE THREAD

**Issue by Njoro007** [dotnet/wpf#6522] opened 2022-03-31 18:37 UTC
### .NET version

6.0.3

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Worked without any issues in NET 5 and Net Framework

### Issue description

In a WinForms desktop application targeting .NET 6, the [UseWindowsForms] element in the .proj file is set to True, and a bootstrap ApplicationConfiguration.Initialize(); is generated and called from the startup file Program.

Now I want to enable WPF by setting [EnableWPF] to True. When I do that and build I get the following error in the output log

` Program.cs(13,13,13,37): error CS0103: The name 'ApplicationConfiguration' does not exist in the current context
1>Done building project "WinFormsApp1_s2dcxfug_wpftmp.csproj" -- FAILED. `

**My workaround for a net6 WinForm Project with WPF Enabled is editing the Program.CS to code below**
`
//ApplicationConfiguration.Initialize();
Application.SetHighDpiMode(HighDpiMode.SystemAware);
Application.EnableVisualStyles();
Application.SetCompatibleTextRenderingDefault(false);
Application.Run(new Form1());
`

### Steps to reproduce

**To Reproduce**

- Create a new Windows Forms project in VS 2022 targeting .NET 6.
- Go to proj properties and check the Enable WPF for this project check box
- Add a WPF window to the project
- Build

**Comment by RussKie** [comment] 2022-05-04 05:26
Here's a [binlog](https://github.com/dotnet/winforms/files/8617501/msbuild.zip) from a basic Windows Forms app with a WPF window.

Upon further digging in I've started thinking that perhaps the issue is caused by `GenerateTemporaryTargetAssembly`, that is not aware of inbox analyzers (described in https://github.com/dotnet/designs/blob/main/accepted/2021/InboxSourceGenerators.md) and introduced in .NET 6.0 timeframe:
https://github.com/dotnet/wpf/blob/bedefb0542bd1cbe309cadd0bbb58e35739cdfa4/src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets#L439-L455

Curiously, the task contains this line:
https://github.com/dotnet/wpf/blob/bedefb0542bd1cbe309cadd0bbb58e35739cdfa4/src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets#L452
...however, it is a property and generates a property in the temp project, and it has nothing to do with the list of resolved analyzers, which is contained in `@Analyzer` item group.

**Comment by ThomasGoulet73** [comment] 2022-05-04 22:52
I can reproduce on my machine using the Regex source generator so this is unrelated to WinForms.

@RussKie The code snippet for `Analyzers` that you sent looks suspicious, `GenerateTemporaryTargetAssembly` should use the `Analyzer` ItemGroup to add it in the generated csproj to pass to the Csc task in CoreCompile (Which also uses the `Analyzer` ItemGroup).

I'll try to work on a fix (If you're not already working on one).

**Comment by RussKie** [comment] 2022-05-05 02:43
> Hmm, we've seen this problem in a few different iterations.
> 
> [dotnet/roslyn#60257](https://github.com/dotnet/roslyn/issues/60257) #4421 [dotnet/roslyn#46300](https://github.com/dotnet/roslyn/issues/46300)
> 
> Basically all of these occur be

@ThomasGoulet73 do you think your fix would address any of these?

**Comment by ThomasGoulet73** [comment] 2022-05-05 03:20
@RussKie Here's the result of my tests:
dotnet/roslyn#60257
Fixed by my PR. I tried the repro and the build fails without my changes and succeeds with my changes.

dotnet/wpf#4421
Not fixed by my PR. It looks like #5711 (It looks like SomeRazorComponent is generated in the generated project namespace instead of the main project namespace. `WpfBlazorRepro_5s0cnboz_wpftmp` instead of `WpfBlazorRepro`), I'll try to take a closer look at #5711.

dotnet/roslyn#46300
Looks unrelated to WPF, the issue talks about WinUI 3 and the CompileXaml task, which is not in WPF.

**Comment by ThomasGoulet73** [comment] 2022-05-05 03:39
> #4421 Not fixed by my PR. It looks like #5711 (It looks like SomeRazorComponent is generated in the generated project namespace instead of the main project namespace. `WpfBlazorRepro_5s0cnboz_wpftmp` instead of `WpfBlazorRepro`), I'll try to take a closer look at #5711.

I found the problem, I opened #6535.

**Comment by RussKie** [comment] 2022-05-05 04:52
Champion! Thank you

**Comment by RussKie** [comment] 2022-06-14 00:43
@singhashish-wpf can we expedite this? This needs to be serviced into .NET 6.
/cc: @merriemcgaw

**Closed** 2022-06-14 05:26 UTC
Labels: Bug, :construction: work in progress
