### ISSUE TITLE
TreeView Virtualization seems to be broken under .NET 7

### ISSUE THREAD

**Issue by akade** [dotnet/wpf#7321] opened 2022-11-28 14:29 UTC
<details>
  <summary>Environment: SDKs 7.0.100 & 6.0.301 on Win 10 22H2 </summary>
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  6.0.301 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>

 **Problem description:**

If a TreeView is within a StackPanel and has Virtualization turned on, it fails to render more than one item on the second or deeper level of the treeview:
![image](https://user-images.githubusercontent.com/16369295/204301816-6e9aa382-ed86-46f7-ba32-408ffba8ea47.png)

While the same under .NET 6 works as expected:
![image](https://user-images.githubusercontent.com/16369295/204302042-0511634e-b271-411e-b725-d12e2354e51c.png)
 
 **Minimal repro:**
[WpfApp2.zip](https://github.com/dotnet/wpf/files/10104551/WpfApp2.zip)
Just change the TFM, clean & rebuild in VS to reproduce the bug.

**Comment by lindexi** [comment] 2022-11-29 01:15
I can repro this issues. But I haven't pinpointed the specific problem yet.

![TreeView Virtualization seems to be broken](https://user-images.githubusercontent.com/16054566/204414287-98131db3-fbe3-45bf-87ad-f05789be25ad.gif)

**Comment by Laniusexcubitor** [comment] 2022-12-09 12:57
The same happens when grouping in an ItemsControl and enabling virtualization for grouping.
There seems to be an issue with hierarchical virtualization.

See this [gist](https://gist.github.com/Laniusexcubitor/c16a9661e382fdb3d9a6f761c2c44fc4) for a repro with a simple items control with virtualization and grouping.
All items get realized in dotnet 6 but only the first item in each group gets realized in dotnet 7

**Comment by zlatanov** [comment] 2022-12-16 20:49
I can confirm that this happens with ItemsControl with virtualization enabled as @Laniusexcubitor said. This is a major setback, why is no one on the WPF team responding to this?

**Comment by batzen** [comment] 2022-12-16 21:07
It's not limited to the TreeView. Virtualized grouping is also affected, so i guess nested virtualization is affected completely.

**Comment by batzen** [comment] 2022-12-16 21:10
@dipeshmsft any chance someone from the WPF team can have a look at this?

**Comment by pchaurasia14** [comment] 2022-12-17 10:00
@batzen - Yes. We're checking on this. Will update this thread asap.

**Comment by singhashish-wpf** [comment] 2022-12-23 07:17
InternalChildren Property is showing up wrong value along with other properties related to the size and height. Still debugging it further to check for the root cause.

**Comment by singhashish-wpf** [comment] 2023-01-12 06:38
The changes in PR https://github.com/dotnet/wpf/pull/4220 are disturbing the HierarchicalVirtualizationConstraints calculation, which is further used in calculation of the sizes of the virtualizing items and availableSize, DesiredSize, Viewport and extendedViewport calculations.
The result of all this is showing just the first item rather than all the items in the group

**Comment by singhashish-wpf** [comment] 2023-04-18 16:18
Fix released in 7.0.3, Closing the issue

**Closed by singhashish-wpf** 2023-04-18 16:18 UTC
Labels: Bug, area-VirtualizingStackPanel
