### ISSUE TITLE
Textbox cursors disappear when moving from high DPI to low DPI

### ISSUE THREAD

**Issue by grubioe** [dotnet/wpf#1066] opened 2019-06-23 18:36 UTC
Copied from AzDO: 831015

OS: Windows 10 19H1

CPU: X64

.NET Build Number: 4.8.03752

Repro Steps:

1. Have 200% primary, 100% secondary
2. Launch repro proj exe on primary
3. Focus the textbox and see the cursor blinking
4. Move it to secondary
5. The cursor disappears, but can still type in the textbox  

Expected:

    The cursor is still visible and blinking
![image](https://user-images.githubusercontent.com/49078227/59980455-ea561600-95aa-11e9-8a1d-37c155013ec7.png)
 

Actual:

    The cursor disappears, but can still type in the textbox
![image](https://user-images.githubusercontent.com/49078227/59980460-fb9f2280-95aa-11e9-96bd-46ff7fabfb8d.png)

**Comment by AmadeusW** [comment] 2019-08-23 21:28
FYI this affects Visual Studio. See very popular issue https://developercommunity.visualstudio.com/content/problem/488656/cursor-dissapears-in-search-boxes-on-2nd-monitor.html

**Comment by SamBent** [comment] 2019-09-24 16:52
Duplicate of #1774

**Closed by SamBent** 2019-09-24 16:52 UTC
Labels: area-netfx, issue-type-bug
