### ISSUE TITLE
Compile errors using Refit in WPF in VS17.2.1

### ISSUE THREAD

**Issue by zwcm2007** [dotnet/wpf#6878] opened 2022-08-10 09:45 UTC
I have a WPF Desktop application that framework targets net6.0-windows . When my IDE VS2022 upgrading from 17. 2.1 to 17.3.0 and using Refit 6.3.2 , vs compiles errors as below:
![56E997DD-89C5-4363-BF0B-3B7B2F45A408](https://user-images.githubusercontent.com/20622446/183869331-3e8c091c-e69d-4db3-a28d-58a16f0c4470.png)

There is nothing code except a interface file named "IAccoutnApi",  but it's all right in winform App,  so how to resolve this problem?

**Comment by ThomasGoulet73** [comment] 2022-08-10 16:58
This is a duplicate of dotnet/wpf#6792. The fix is already in the .Net 6 branch and should be included in .Net 6.0.9, which is not released yet (Should be next month).

**Closed by ThomasGoulet73** 2022-08-10 16:58 UTC
Labels: Bug, regression
