### ISSUE TITLE
Crash: Height must be non-negative

### ISSUE THREAD

**Issue by nerai** [dotnet/wpf#2854] opened 2020-04-08 09:32 UTC
* .NET Core Version: .NET Core 3.1.100
* Windows version: 10.0.18362
* Does the bug reproduce also in WPF for .NET Framework 4.8?: did not test

 **Problem description:**

Concurrently adding/removing items to ListBox and moving focus causes exception.
 
 **Actual behavior:** 

```
System.ArgumentException
  HResult=0x80070057
  Message=Height must be non-negative.
  Source=WindowsBase
  StackTrace:
   at System.Windows.Rect.set_Height(Double value)
   at System.Windows.Controls.VirtualizingStackPanel.ExtendViewport(IHierarchicalVirtualizationAndScrollInfo virtualizationInfoProvider, Boolean isHorizontal, Rect viewport, VirtualizationCacheLength cacheLength, VirtualizationCacheLengthUnit cacheUnit, Size stackPixelSizeInCacheBeforeViewport, Size stackLogicalSizeInCacheBeforeViewport, Size stackPixelSizeInCacheAfterViewport, Size stackLogicalSizeInCacheAfterViewport, Size stackPixelSize, Size stackLogicalSize, Int32& itemsInExtendedViewportCount)
   at System.Windows.Controls.VirtualizingStackPanel.IsExtendedViewportFull()
   at System.Windows.Controls.VirtualizingStackPanel.ShouldItemsChangeAffectLayoutCore(Boolean areItemChangesLocal, ItemsChangedEventArgs args)
   at System.Windows.Controls.Panel.OnItemsChanged(Object sender, ItemsChangedEventArgs args)
   at System.Windows.Controls.ItemContainerGenerator.OnItemAdded(Object item, Int32 index)
   at System.Windows.Controls.ItemContainerGenerator.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
   at System.Windows.Data.CollectionView.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
   at System.Windows.Data.CollectionView.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
   at MS.Internal.Controls.InnerItemCollectionView.Add(Object item)
   at System.Windows.Controls.ItemCollection.Add(Object newItem)
   at WpfApp1.MainWindow.<>c__DisplayClass1_0.<Work>b__0() in C:\Users\mafu\source\repos\WpfApp1\WpfApp1\MainWindow.xaml.cs:line 42
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```
 
 **Expected behavior:**

No exception.
 
 **Minimal repro:**

XAML:

```
<Window x:Class="WpfApp1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp1"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
	<Grid>
		<ListBox x:Name="list"/>
	</Grid>
</Window>
```

CS:
```
using System;
using System.Collections.Generic;
using System.Threading;
using System.Windows;

namespace WpfApp1
{
	public partial class MainWindow : Window
	{
		public MainWindow ()
		{
			InitializeComponent ();

			for (int i = 0; i < 4; i++) {
				new Thread (Work) { IsBackground = true }.Start ();
			}
		}

		private void Work ()
		{
			var mtid = Thread.CurrentThread.ManagedThreadId;
			var r = new Random (mtid);
			int i = 0;
			var its = new List<string> ();

			while (true) {
				if ((its.Count == 0) || (r.Next () % 2 == 0)) {
					var it = $"{mtid}-{++i}";
					its.Add (it);
					Dispatcher.BeginInvoke ((Action) delegate {
						list.Items.Add (it);
					});
				}
				else {
					var index = r.Next (its.Count);
					var it = its [index];
					its.RemoveAt (index);
					Dispatcher.BeginInvoke ((Action) delegate {
						list.Items.Remove (it);
					});
				}
				Thread.Sleep (r.Next (2));
			}
		}
	}
}
```

When the application is running, press HOME, END and ARROW-DOWN keys randomly in quick succession until it crashes (takes a few seconds).

**Comment by nerai** [comment] 2020-04-08 09:34
Note sure if #382 is related. The stack traces look vaguely similar (?).

**Comment by elyoh** [comment] 2020-04-28 17:07
I intermittently see a similar stack trace in telemetry from an app running on .NET 4.8 but have not been able to reproduce it locally.

```
System.ArgumentException: Height must be non-negative.
   at System.Windows.Rect.set_Height(Double value)
   at System.Windows.Controls.VirtualizingStackPanel.ExtendViewport(IHierarchicalVirtualizationAndScrollInfo virtualizationInfoProvider, Boolean isHorizontal, Rect viewport, VirtualizationCacheLength cacheLength, VirtualizationCacheLengthUnit cacheUnit, Size stackPixelSizeInCacheBeforeViewport, Size stackLogicalSizeInCacheBeforeViewport, Size stackPixelSizeInCacheAfterViewport, Size stackLogicalSizeInCacheAfterViewport, Size stackPixelSize, Size stackLogicalSize, Int32& itemsInExtendedViewportCount)
   at System.Windows.Controls.VirtualizingStackPanel.IsExtendedViewportFull()
   at System.Windows.Controls.VirtualizingStackPanel.ShouldItemsChangeAffectLayoutCore(Boolean areItemChangesLocal, ItemsChangedEventArgs args)
   at System.Windows.Controls.VirtualizingPanel.OnItemsChangedInternal(Object sender, ItemsChangedEventArgs args)
   at System.Windows.Controls.Panel.OnItemsChanged(Object sender, ItemsChangedEventArgs args)
   at System.Windows.Controls.ItemContainerGenerator.OnItemAdded(Object item, Int32 index)
   at System.Windows.Controls.ItemContainerGenerator.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
   at System.Collections.ObjectModel.ReadOnlyObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at MS.Internal.Data.CollectionViewGroupRoot.AddToSubgroup(Object item, LiveShapingItem lsi, CollectionViewGroupInternal group, Int32 level, Object name, Boolean loading)
   at MS.Internal.Data.CollectionViewGroupRoot.AddToSubgroups(Object item, LiveShapingItem lsi, CollectionViewGroupInternal group, Int32 level, Boolean loading)
   at System.Windows.Data.ListCollectionView.PrepareGroups()
   at System.Windows.Data.ListCollectionView.PrepareLocalArray()
   at System.Windows.Data.ListCollectionView.RefreshOverride()
   at System.Windows.Data.CollectionView.RefreshInternal()
   at System.Windows.Data.CollectionView.EndDefer()
   at System.Windows.Data.CollectionView.DeferHelper.Dispose()
```

**Comment by CVManoj** [comment] 2021-10-12 09:04
Are there any solution for this issue?

**Comment by singhashish-wpf** [comment] 2021-11-09 11:44
Duplicate of https://github.com/dotnet/wpf/issues/2854

**Comment by lindexi** [comment] 2021-11-09 12:07
> 
> 
> Duplicate of #2854

Duplicate of #2854 ?  This is #2854

**Comment by nerai** [comment] 2021-11-10 12:45
@SamBent Thanks for looking into this. I'm sorry I'm currently unable to check this again and will be for a few weeks. It seems this issue happened to others, too, so I hope someone else can provide a trace.

Re repro, I should add that the focus should be on the list box, and the keys should be pressed randomly and in very quick succession (cat typing is not enough to trigger it).

**Comment by SamBent** [comment] 2021-11-11 00:44
@nerai Yes, I had focus on the list box, and pressed HOME/END/DOWN rapidly at random.  No crash for me.

I added scroll-tracing and ran under a debugger, and found that your app is starving the UI thread's dispatcher - tasks at low priority aren't getting a chance to run.  This is because your background threads are calling BeginInvoke at high priority (default is Normal, the second highest priority) as fast as possible, since they sleep for the minimum amount.  Thus the dispatcher always (well, almost always) has high-priority work to do.

By starving Background tasks, you are starving
* the "Measure Caches" layout pass that de-virtualizes items just before and after the current viewport
* the re-virtualization of items that have scrolled out of view (which depends on the result of "Measure Caches")
* other useful tasks, including many "cleanup" tasks that release weak references and other resources no longer needed

By starving Input tasks, the app won't respond to mouse and keyboard input.  By starving Render tasks, the app will stop updating the screen.  I've seen all of this happen;  it takes a while, and happens in stages, and it seems to be sensitive to the history of scrolling and virtualization, as well as to the usual suspects:  thread scheduling, CPU load, machine speed, etc.

The response to add/remove collection changes also depends on the result of "Measure Caches".  I can envision how the state that causes the exception can arise, although I can't get it to happen.  Let's just say it's because my machine is faster (or slower) than yours, or has different load.  I can get it to happen in a repro from another internal report, which is more like @elyoh's case in that it involves refresh of a grouped collection.  But the point here is that fixing the exception won't make the starvation go away;  you'll still see these problems.  If your real app is starving the dispatcher, well, don't do that. (WPF has too many essential tasks at lower priorities, and no general way to detect and cope with starvation issues.  It's up to apps to play nice.)

**Comment by Viveksach** [comment] 2022-02-11 11:49
Hi,  same issue is occurring when working with  .Net 5. Can someone confirm if it is already applied to .Net 5 and if not when will it be applied and in which release version it will be available?

**Comment by lindexi** [comment] 2022-02-11 11:51
@Viveksach Could you update to .NET 6.0.2 ?

**Comment by Viveksach** [comment] 2022-02-11 11:55
@lindexi we can not update our solution to .Net 6 right now due to the Visual studio 2019 restrictions. Does the fix has not been released for .Net 5 ?

**Comment by Viveksach** [comment] 2022-02-21 04:51
@SamBent Could you please confirm if the fix has been released for .Net 5 version or still pending for next releases.

**Comment by ThomasGoulet73** [comment] 2022-02-21 04:55
@Viveksach The fix is not in a currently released version of .Net 5.0 but it has been merged and should be in .Net 5.0.15 according to the milestone on the pull request containing the changes for .Net 5.0 (https://github.com/dotnet/wpf/pull/6013).

**Comment by Viveksach** [comment] 2022-02-22 11:45
Ok. Thanks for the details @ThomasGoulet73

**Comment by gurpreet-wpf** [comment] 2022-02-28 10:22
PRs merged, closing this issue

**Closed by gurpreet-wpf** 2022-02-28 10:22 UTC
Labels: Bug, Port to .NET Core 3.1, Port to .NET 5.0, Port to .NET 6.0
