### ISSUE TITLE
Resource File not exits in WPF core 3.0

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#407] opened 2019-03-06 05:45 UTC
VSF_TYPE_MARKDOWNI had include a png file in my proyect as Resource, but when my application is compiled it is not found.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/478320/resource-file-not-exits-in-wpf-core-30.html
VSTS ticketId: 810337_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by aelij** [comment] 2019-03-30 09:25
I think that when `<UseWpf>` is specified, every file that was automatically added as a `Resource` item in WPF projects should continue to behave the same. This included images, icons, fonts, etc.

**Comment by stevenbrix** [comment] 2019-04-04 03:38
Duplicate of #209

**Closed by stevenbrix** 2019-04-04 03:38 UTC
Labels: bug
