### ISSUE TITLE
ToolTip no longer stable.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#6336] opened 2022-03-31 21:29 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ToolTip-no-longer-stable/1691105)._

---
[severity:It's more difficult to complete my work]
ToolTip behaviour is now unstable. 

I tried resetting Visual Studio. Created a simple project with a Button and a ToolTip.  The 'ToolTip' is displayed so briefly as to be unusable. Movement of the mouse even whilst over the button the 'ToolTip' disappears.

---
#### Ray Wynn on 3/14/2022, 06:27 AM: 

(private comment, text removed)
#### Feedback Bot on 3/14/2022, 09:14 AM: 

(private comment, text removed)
#### Vicky Du [MSFT] on 3/15/2022, 10:07 AM: 

(private comment, text removed)
#### Ray Wynn on 3/15/2022, 06:09 PM: 

(private comment, text removed)
#### Ray Wynn on 3/15/2022, 08:15 PM: 

(private comment, text removed)
#### Vicky Du [MSFT] on 3/16/2022, 09:47 AM: 

(private comment, text removed)
#### Ann Yang (Beyondsoft Corporation) [MSFT] on 3/18/2022, 07:04 AM: 

(private comment, text removed)
#### Ann Yang (Beyondsoft Corporation) [MSFT] on 3/18/2022, 07:07 AM: 

(private comment, text removed)
#### Ray Wynn on 3/18/2022, 07:23 AM: 

(private comment, text removed)
#### Ann Yang (Beyondsoft Corporation) [MSFT] on 3/18/2022, 07:27 AM: 

(private comment, text removed)
#### Ray Wynn on 3/18/2022, 01:54 PM: 

(private comment, text removed)
#### Feedback Bot on 3/21/2022, 07:23 AM: 

(private comment, text removed)

---
#### Ray Wynn solved on 3/18/2022, 11:05 PM, 0 votes: 

<p>[Workaround]<br>
Windows 11 <strong>System&gt;Display</strong><br>
<strong>Scale</strong> must be set to 100%.</p>
<p><em>Any other <strong>Scale</strong> value causes the ToolTip instability problem.</em></p>

#### Ray Wynn solved on 3/18/2022, 11:07 PM, 0 votes: 

<p>[Workaround]<br>
Windows 11 <strong>System&gt;Display</strong><br>
<strong>Scale</strong> must be set to 100%.</p>
<p><em>Any other <strong>Scale</strong> value causes the ToolTip instability problem.</em></p>

**Comment by lindexi** [comment] 2022-04-01 00:36
Duplicate of #6220

**Closed** 2022-04-01 07:43 UTC
