### ISSUE TITLE
.Net SDK 6.0 RC2 - UseWPF project with multiple semi-colon delimited SDKs fails as it tries to treat the set as a single SDK

### ISSUE THREAD

**Issue by breidikl** [dotnet/wpf#5607] opened 2021-10-27 23:29 UTC
### Description

When moving our global SDK version from 5.0.402 to 6.0.100-rc.2.21505.57 (which also included switching from MSBuild 16.11.3 to 17 preview 6), one of our UseWPF projects that targets an older framework version started failing as it appears to be trying to evaluate the SDK value with multiple semi-colon delimited sdks as a single SDK inside the generated wpftmp.csproj file.  

### Details

The csproj starts with the following:

```
<Project Sdk="Build.Before;Microsoft.NET.Sdk.WindowsDesktop;Build.After">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>GraphAnalyzer</AssemblyName>
    <NeutralLanguage>en</NeutralLanguage>
    <UseWPF>true</UseWPF>
    <TargetFramework>net472</TargetFramework>
```

While that works when using the .NET 5 SDK, after switching to .NET 6 RC2 it now fails with the following:

>   graphanalyzer_xdtcdvpd_wpftmp.csproj(9,3): error : %DOTNET_ROOT%\sdk\6.0.100-rc.2.21505.57\Sdks\Build.Before;Microsoft.NET.Sdk.WindowsDesktop;Build.After\Sdk not found. Check that a recent enough .NET SDK is installed and/or increase the version specified in global.json.
>   graphanalyzer_xdtcdvpd_wpftmp.csproj(9,31): error MSB4236: The SDK 'Build.Before;Microsoft.NET.Sdk.WindowsDesktop;Build.After' specified could not be found.

graphanalyzer_xdtcdvpd_wpftmp.csproj appears to be the generated TemporaryTargetAssemblyProjectName built by the  _CompileTemporaryAssembly target.

**Comment by ThomasGoulet73** [comment] 2022-08-02 22:49
This is likely a duplicate of #5921 which was fixed by #5922 for .Net 7. @breidikl: Could you try building your project using the .Net 7 SDK and see if you can still reproduce this issue ?

**Comment by breidikl** [comment] 2022-08-03 17:45
@ThomasGoulet73 I've confirmed that this is fixed when using .NET 7 preview 6 SDK.

**Comment by dipeshmsft** [comment] 2022-08-24 11:16
Closing this issue as the fix is already merged.

**Closed by dipeshmsft** 2022-08-24 11:16 UTC
Labels: Bug, Investigate
