### ISSUE TITLE
Window content renders blurry when targeting .NET 7

### ISSUE THREAD

**Issue by BieleckiLtd** [dotnet/wpf#6586] opened 2022-05-14 17:28 UTC
* .NET Core Version: 7.0.0-preview.4.22229.4
* Windows version: Windows 11 21H2 **250% scaling - this might be key in order to repro**
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No

 **Problem description:**
After changing .NET to ver. 7.0.0 preview 4 window started rendering blurry
 
![2022-05-14_18-14-27](https://user-images.githubusercontent.com/57046415/168442323-3eeda78e-e4a4-45bc-a692-3964e7c5bec6.png)

 **Actual behavior:**
Window is blurry
 
 **Expected behavior:**
Window should not be blurry
 
 **Minimal repro:**
* Create new WPF Application project targeting 7.0.0 (Preview) framework
* Add ```<Button Content="Button in .NET 7.0.0-preview.4.22229.2" VerticalAlignment="Top"/>``` between ```Grid``` tags
* Run

**Comment by lindexi** [comment] 2022-05-15 07:36
@BieleckiLtd It work well for me in dotnet 7.0.100-preview.4.22252.9

![](https://user-images.githubusercontent.com/16054566/168462328-2cf0608f-58f4-47b8-8c84-d09ba7e22dcf.png)

**Comment by BieleckiLtd** [comment] 2022-05-15 09:29
@lindexi is your Windows scaling higher than 100%? Are you using more than one display?
My Windows is set to 250% scaling which is recommended for my display and I had no other display connected to my laptop.

**Comment by lindexi** [comment] 2022-05-16 00:37
@BieleckiLtd My Windows is set to 100%

**Comment by BieleckiLtd** [comment] 2022-05-17 06:52
Thanks @lindexi for confirming. 100% scaling will not pronounce issue that much (if at all). I think blurring would be better visible on high dpi displays that use scaling greater than 100%.

**Comment by ThomasGoulet73** [comment] 2022-05-17 12:59
@BieleckiLtd This is probably caused by a bug in high DPI initialization in .NET 7.0 Preview 4 caused by #5765 which should be fixed in the next preview by #6245. Could you try calling [SetProcessDPIAware](https://github.com/dotnet/wpf/blob/main/src/Microsoft.DotNet.Wpf/src/PresentationCore/ModuleInitializer.cs#L49-L50) at the start of your application (Before you show a Window) and see if it fixes your bug ?

**Comment by BieleckiLtd** [comment] 2022-05-18 17:56
@ThomasGoulet73 Yes, I can confirm that calling https://github.com/dotnet/wpf/blob/e8767ef7cf95e3edf86f0600a85c2cc6270cb530/src/Microsoft.DotNet.Wpf/src/PresentationCore/ModuleInitializer.cs#L49-L50 fixes the issue

**Closed** 2022-06-10 10:51 UTC
Labels: Investigate
