### ISSUE TITLE
Tips disappear before anyone could read it.

### ISSUE THREAD

**Issue by lncubus** [dotnet/wpf#6471] opened 2022-04-22 15:45 UTC
* .NET Core Version: Microsoft.NETCore.App 6.0.4, Microsoft.WindowsDesktop.App 6.0.4
* Windows version: Windows 11 Home, 21H2 build 22000.613
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 
 
 **Problem description:**
Tooltips on WPF controls disappear just after displayed.
We experience that on some systems with different Windows 10/11 versions and different .Net 6 framework versions.
I can reproduce it on my machine.
[PowerToys: #17484](https://github.com/microsoft/PowerToys/issues/17484)
 
 **Actual behavior:** 
 The tooltip is shown and immediately closed.

 **Expected behavior:**
The tip should last longer.
 
 **Minimal repro:**
To reproduce the issue I created a sample WPF Application with a button and a list box with one item.
The tooltip for that item appears only for a short time.
If I add tooltip for the button the button's tooltip remains visible.
If I add more items to the window the behavior becomes irregular.
Also tooltips on WPF debug buttons disappear too fast as well.

Added application sources and stack trace from my machine.
[stack_trace.txt](https://github.com/dotnet/wpf/files/8542254/stack_trace.txt)
[WpfApp1.zip](https://github.com/dotnet/wpf/files/8542256/WpfApp1.zip)

I was able to reproduce that with following XAML code:
`<Window x:Class="WpfApp1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp1"
        mc:Ignorable="d"
        Title="MainWindow">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition/>
            <RowDefinition/>
        </Grid.RowDefinitions>
        <Button Grid.Row="0">
            Sample Button 1
        </Button>
        <ListBox Grid.Row="1" Grid.ColumnSpan="2">
            <ListBox.Items>
                <ListBoxItem>Sample Item 1
                    <ToolTipService.ToolTip>
                        <ToolTip>
                            ToolTip for Sample Item 1
                        </ToolTip>
                    </ToolTipService.ToolTip>
                </ListBoxItem>
            </ListBox.Items>
        </ListBox>
    </Grid>
</Window>
`

**Comment by ThomasGoulet73** [comment] 2022-04-22 15:53
This is probably a duplicate of #6220.

The fix for #6220 is already merged in the .Net 6 servicing branch and should be included in the next servicing release (6.0.5).

**Comment by lncubus** [comment] 2022-04-22 16:01
Looks like that, but I've got it on .Net 6.0.2 as well.
Anyway setting display scale to 100% fixes the problem.
Will wait for .net 6.0.5 thank you.

**Comment by ThomasGoulet73** [comment] 2022-04-22 16:11
@lncubus See @SamBent's comment [here](https://github.com/dotnet/wpf/issues/6220#issuecomment-1078072569). The issue was for a similar tooltip bug which was fixed in .Net 6.0.3 but it broke tooltips in high-DPI which should be fixed in .Net 6.0.5.

**Comment by htcfreek** [comment] 2022-04-22 16:14
> @lncubus See @SamBent's comment [here](https://github.com/dotnet/wpf/issues/6220#issuecomment-1078072569). The issue was for a similar tooltip bug which was fixed in .Net 6.0.3 but it broke tooltips in high-DPI which should be fixed in .Net 6.0.5.

Now things make sense. 💡

**Comment by singhashish-wpf** [comment] 2022-04-25 07:27
Please check in 6.0.5, The fix is included.

**Closed by singhashish-wpf** 2022-04-25 07:27 UTC
Labels: Untriaged, Requires WPF team triage

**Comment by htcfreek** [comment] 2022-04-25 11:33
> Please check in 6.0.5, The fix is included.

Is it released yet?

**Comment by singhashish-wpf** [comment] 2022-04-25 13:56
> > Please check in 6.0.5, The fix is included.
> 
> @singhashish-wpf Is it released yet?
> 
> @lncubus Can you test and verify that it's fixed?

Not yet released.

**Comment by lncubus** [comment] 2022-04-25 14:50
Can we get some nightly build then?

**Comment by lindexi** [comment] 2022-04-26 00:34
@lncubus You can use my custom build version: https://github.com/dotnet-campus/wpf/actions/runs/2165079979

Please note that this is not an official build. But you can use it to test your application.

**Comment by Symbai** [comment] 2022-05-11 05:00
.NET 6.0.5 is now released but the fix is not included in the changelog: https://github.com/dotnet/wpf/issues?q=milestone%3A6.0.5+is%3Aclosed+label%3Aservicing-approved+
