### ISSUE TITLE
Attaching touch device on a non-touch machine fails to initialize PenIMC_cor3

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/wpf#38] opened 2018-11-30 23:24 UTC
Repro Steps:

- Start any WPF NetCore3 application on a machine with no touch or stylus devices.
- Notice that PenIMC_cor3.dll is not loaded (use windbg, lmsm).
- Attach a touch or stylus device.

Notice the following errors and the fact that touch has failed to initialize.

`ModLoad: 00007ffc`14a70000 00007ffc`14bd5000   C:\Program Files\dotnet\shared\Microsoft.Private.WPF\3.0.0-alpha-26828-2\PenIMC_cor3.dll(5278.aec): Windows Runtime Originate Error - code 40080201 (first chance)onecore\com\combase\dcomrem\marshal.cxx(1156)\combase.dll!00007FFC79AF9379: (caller: 00007FFC79AFA49C) ReturnHr(1) tid(aec) 80040155 Interface not registered    Msg:[Failed to marshal with IID={BD2C38C2-E064-41D0-A999-940F526219C2}] onecore\com\combase\dcomrem\marshal.cxx(1077)\combase.dll!00007FFC79AFA4C9: (caller: 00007FFC79AFCDF9) LogHr(1) tid(aec) 80040155 Interface not registeredonecore\com\combase\dcomrem\marshal.cxx(1017)\combase.dll!00007FFC79AFD147: (caller: 00007FFC79AEC673) ReturnHr(2) tid(aec) 80040155 Interface not registered(5278.52cc): CLR exception - code e0434352 (first chance)ModLoad: 00007ffc`74110000 00007ffc`74119000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0-preview1-26820-01\System.Diagnostics.StackTrace.dllModLoad: 00007ffc`147d0000 00007ffc`148d5000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0-preview1-26820-01\System.Reflection.Metadata.dllModLoad: 00007ffc`74100000 00007ffc`74109000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0-preview1-26820-01\System.Diagnostics.Tracing.dllModLoad: 00007ffc`11130000 00007ffc`113b2000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0-preview1-26820-01\System.Collections.Immutable.dllWorkerOperationGetTabletsInfo.OnDoWork failed due to: System.InvalidCastException: Interface not registeredFailed to find proxy registration for IID: {BD2C38C2-E064-41D0-A999-940F526219C2}.   at MS.Win32.Penimc.UnsafeNativeMethods.CoCreateInstance(Guid& clsid, Object punkOuter, Int32 context, Guid& iid)   at MS.Win32.Penimc.UnsafeNativeMethods.CreatePimcManager()   at MS.Win32.Penimc.UnsafeNativeMethods.get_PimcManager()   at System.Windows.Input.PenThreadWorker.WorkerOperationGetTabletsInfo.OnDoWork()(5278.aec): Windows Runtime Originate Error - code 40080201 (first chance)onecore\com\combase\dcomrem\marshal.cxx(1156)\combase.dll!00007FFC79AF9379: (caller: 00007FFC79AFA49C) ReturnHr(3) tid(aec) 80040155 Interface not registered    Msg:[Failed to marshal with IID={BD2C38C2-E064-41D0-A999-940F526219C2}] onecore\com\combase\dcomrem\marshal.cxx(1077)\combase.dll!00007FFC79AFA4C9: (caller: 00007FFC79AFCDF9) LogHr(2) tid(aec) 80040155 Interface not registeredonecore\com\combase\dcomrem\marshal.cxx(1017)\combase.dll!00007FFC79AFD147: (caller: 00007FFC79AEC673) ReturnHr(4) tid(aec) 80040155 Interface not registered(5278.52cc): CLR exception - code e0434352 (first chance)WorkerOperationGetTabletsInfo.OnDoWork failed due to: System.InvalidCastException: Interface not registeredFailed to find proxy registration for IID: {BD2C38C2-E064-41D0-A999-940F526219C2}.   at MS.Win32.Penimc.UnsafeNativeMethods.CoCreateInstance(Guid& clsid, Object punkOuter, Int32 context, Guid& iid)   at MS.Win32.Penimc.UnsafeNativeMethods.CreatePimcManager()   at MS.Win32.Penimc.UnsafeNativeMethods.get_PimcManager()   at System.Windows.Input.PenThreadWorker.WorkerOperationGetTabletsInfo.OnDoWork()`

**Comment by Yitzchok** [comment] 2019-01-28 23:44
On .NET 4.7.1,2 I get the same behavior. And when removing and re-adding the touch device the app loads PenIMC and touch start working.

For now, I am going around this by using WM_POINTER https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/mitigation-pointer-based-touch-and-stylus-support

**Comment by grubioe** [comment] 2019-05-23 03:53
Reference to internal ID: 672857

**Comment by rladuca** [comment] 2019-07-19 00:40
@ryalanms I tried this on my local machines and I couldn't reproduce this exact failure.  However, connecting touch after the application has started sometimes fails to initialize.  So there might be a related bug going on here.

**Comment by rladuca** [comment] 2019-07-19 00:42
@Yitzchok Sorry for the delayed response, but this particular failure isn't possible in .NET Framework.  It's specific to COM changes we made purely for .NET Core 3.

However, there may be some issues that you are facing on .NET Framework that are exacerbated in .NET Core 3 and might even be the cause of me seeing similar things as I stated above.

**Comment by rladuca** [comment] 2020-04-15 18:35
This is actually going to be solved by #2393, and is related to multi-threaded applications and the activation contexts.  Closing this accordingly.

**Closed by rladuca** 2020-04-15 18:35 UTC
Labels: issue-type-bug, regression
