### ISSUE TITLE
Microsoft.NET.Sdk.WindowsDesktop.props references System.Windows.Controls.Ribbon on .NET 4.0

### ISSUE THREAD

**Issue by ericstj** [dotnet/wpf#255] opened 2019-01-11 00:24 UTC
**Problem description:**
When targeting net40 from a WPF app the build emits a warning. 

 **Actual behavior:** 
 Warning:
```
C:\Program Files\dotnet\sdk\3.0.100-preview-010046\Microsoft.Common.CurrentVersion.targets(2114,5): warning MSB3267: The primary reference "System.Windows.Controls.Ribbon", which is a framework assembly, could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "System.Windows.Controls.Ribbon" or retarget your application to a framework version which contains "System.Windows.Controls.Ribbon".
```

 **Expected behavior:**
No warning
 
 **Minimal repro:**
dotnet new wpf
change targetframework to `net40` or make it cross-target.
dotnet build

(project also attached)
[net40.zip](https://github.com/dotnet/wpf/files/2747557/net40.zip)

I believe the fix is here is to put a condition on the _SDKImplicitReference items defined in Microsoft.NET.Sdk.WindowsDesktop.props.

Originally reported here: https://github.com/dotnet/core/issues/2085#issuecomment-453309364

**Comment by BillHenning** [comment] 2019-05-09 13:34
We are beginning to multi-target our WPF control assemblies to net40 and netcoreapp3.0 and are running into this warning now all over the place:

> MSB3267	The primary reference "System.Windows.Controls.Ribbon", which is a framework assembly, could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "System.Windows.Controls.Ribbon" or retarget your application to a framework version which contains "System.Windows.Controls.Ribbon".

This was originally reported in January and is still occurring in .NET 3.0 preview5.  Will it be fixed soon?

**Comment by vatsan-madhavan** [comment] 2019-05-09 17:29
We should definitely fix this before p7. I worry that this will continue to be a big problem for several mainstream scenarios. This is either related to or a duplicate of https://github.com/dotnet/wpf/issues/327. 

/cc @nguerrera, @grubioe, @rladuca

**Closed** 2019-06-08 06:13 UTC
Labels: area-Infrastructure, bug
