### ISSUE TITLE
Compilation error MC3064 when importing internal user control from signed class library

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#2492] opened 2020-01-31 21:50 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/887201/compilation-error-mc3064-when-importing-internal-u.html)._

---
The Wpf project fails to compile with the  error MC3064 when importing signed user control if its visibility set to internal.

Note: The imported library has appropriate directive [InternalsVisibleTo()].

Same control compiles without problem if library is not strongly signed (check attached project to reproduce problem).

The attached project WpfClientApp will not compile with error:
1&gt;------ Build started: Project: WpfClientApp, Configuration: Debug Any CPU ------
1&gt;C:\Users\aza\source\repos\WpfClientApp\MainWindow.xaml(12,10): error MC3064: Only public or internal classes can be used within markup. 'ButtonControl' type is not public or internal.

If you remove signing of the assembly and the application (Project properties-&gt;Signing tab-&gt;uncheck  &quot;Sign the assembly&quot; and remove PublicKey parameter from the ControlsLibrary\Properties\AssemblyInfo.cs), project will compile and run successfully.

This makes it impossible to distincts controls for public and internal use in the community controls library.

---
#### Visual Studio Feedback System on 1/16/2020, 07:04 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### azatvornitskiy on 1/19/2020, 11:35 PM: 

Thank you, will be witing.

---
### Original Solutions
(no solutions)

**Comment by adamhewitt627** [comment] 2021-02-12 05:40
[DotnetWpf2492.zip](https://github.com/dotnet/wpf/files/5969852/DotnetWpf2492.zip)

I've also run into this, but only with SDK-style projects. I've attached a reproduction project.

**Comment by ryalanms** [comment] 2021-02-18 23:27
Thanks, @gomathip02 and @adamhewitt627.  

WPF does type validation during both markup compilation passes.  As part of this, there is a check to allow non-visible types if the containing assembly for that type has the custom attribute for InternalsVisibleTo and the parameter for that attribute matches the target assembly.  The comparison of assembly names only happens if the custom property retrieved from the assembly containing the referenced type is of typeof(InternalsVisibleToAttribute).  This initial check was testing the attribute type against the default load context, not the reflection-only load context.  These are incompatible.  

The fix is to compare the attribute type against the type from the reflection-only context.  This is a bug from the initial port from .NET Framework.

**Comment by ryalanms** [comment] 2021-02-18 23:40
Unfortunately, there are no workaround, and this will have to go into a servicing release for 3.1 and 5.0.

**Comment by ryalanms** [comment] 2021-02-18 23:41
If your company is blocked I can give you a private version of PresentationBuildTasks.dll with the fix.

**Comment by adamhewitt627** [comment] 2021-02-19 05:23
Thanks. I'm not blocked, I ran into this trying to migrate to the SDK project but don't need it. Hopefully it can make a release soon so I can take another shot at updating.

**Comment by ryalanms** [comment] 2021-07-27 23:40
I've created a servicing request to bring the fix to .NET 5.0.  It has been fixed in 6 since Preview 3.

**Closed by ryalanms** 2021-07-27 23:40 UTC
Labels: Bug, Has PR, Investigate, regression
