### ISSUE TITLE
Editing for DataGrid cell is not triggered while pressing any characters for some language

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#6070] opened 2022-02-03 19:16 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Editing-for-DataGrid-cell-is-not-trigger/1651231)._

---
In WPF DataGrid, if we select a cell and press any key, editing for that cell is triggered properly when the selected language in language preferences option in Windows 10 is English. 

If we select Tamil, then the cell doesn't enter edit mode when pressing any character in the key. 

Please refer to the attached video illustration of the problem and provide if there is any way to resolve this.

[DataGrid_EditDemo.zip] (https://aka.ms/dc/file?name=B0dce2072831744a2966a813180c0bcdd637792309689738136_DataGrid_EditDemo.zip&tid=0dce2072831744a2966a813180c0bcdd637792309689738136)

---
#### Feedback Bot on 2/2/2022, 05:33 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by gurpreet-wpf** [comment] 2022-02-07 05:14
This is duplicate of #6041 and will be tracked there. Hence, closing this.

**Closed by gurpreet-wpf** 2022-02-07 05:14 UTC
