### ISSUE TITLE
Wpf Application switches to WinExe, not only in Net5, also in a 4.6.1

### ISSUE THREAD

**Issue by jogibear9988** [dotnet/wpf#4314] opened 2021-03-22 19:31 UTC
Thias was a change in Net5:

https://docs.microsoft.com/de-de/dotnet/core/compatibility/windows-forms/5.0/automatically-infer-winexe-output-type

But it also affects Net 4.6.1 Software.

Our Program did not work any more until we added the suggested fix.

**Comment by TysonMN** [comment] 2021-03-23 18:06
@jogibear9988, what SDK are you using?

**Comment by jogibear9988** [comment] 2021-03-23 18:49
My csproj looks like this:

	<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
	  <PropertyGroup><GenerateErrorForMissingTargetingPacks>false</GenerateErrorForMissingTargetingPacks></PropertyGroup>
	  <PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net461</TargetFramework>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<ApplicationIcon />
		<StartupObject />
		<AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
	  </PropertyGroup>
	  <ItemGroup>
		<ProjectReference Include="..\DotNetSiemensPLCToolBoxLibrary.TIAV13\DotNetSiemensPLCToolBoxLibrary.TIAV13.csproj">
		  <Private>true</Private>
		</ProjectReference>
		<ProjectReference Include="..\DotNetSiemensPLCToolBoxLibrary.TIAV14SP1\DotNetSiemensPLCToolBoxLibrary.TIAV14SP1.csproj">
		  <Private>true</Private>
		</ProjectReference>
		<ProjectReference Include="..\DotNetSiemensPLCToolBoxLibrary.TIAV15\DotNetSiemensPLCToolBoxLibrary.TIAV15.csproj">
		  <Private>true</Private>
		</ProjectReference>
		<ProjectReference Include="..\DotNetSiemensPLCToolBoxLibrary.TIAV15_1\DotNetSiemensPLCToolBoxLibrary.TIAV15_1.csproj">
		  <Private>true</Private>
		</ProjectReference>
		<ProjectReference Include="..\DotNetSiemensPLCToolBoxLibrary.TIAV16\DotNetSiemensPLCToolBoxLibrary.TIAV16.csproj">
		  <Private>true</Private>
		</ProjectReference>
		<ProjectReference Include="..\LibNoDaveConnectionLibrary.WinForms\DotNetSiemensPLCToolBoxLibrary.WinForms.csproj" />
		<ProjectReference Include="..\LibNoDaveConnectionLibrary\DotNetSiemensPLCToolBoxLibrary.csproj" />
	  </ItemGroup>
	  <ItemGroup>
		<Compile Update="Properties\Settings.Designer.cs">
		  <DesignTimeSharedInput>True</DesignTimeSharedInput>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Settings.settings</DependentUpon>
		</Compile>
	  </ItemGroup>
	  <ItemGroup>
		<None Update="Properties\Settings.settings">
		  <Generator>SettingsSingleFileGenerator</Generator>
		  <LastGenOutput>Settings.Designer.cs</LastGenOutput>
		</None>
	  </ItemGroup>
	</Project>


     D:\>dotnet --version
      5.0.201

	D:\>dotnet --list-sdks
	2.1.700 [C:\Program Files\dotnet\sdk]
	2.1.701 [C:\Program Files\dotnet\sdk]
	2.1.801 [C:\Program Files\dotnet\sdk]
	2.1.802 [C:\Program Files\dotnet\sdk]
	2.2.110 [C:\Program Files\dotnet\sdk]
	3.0.100 [C:\Program Files\dotnet\sdk]
	3.1.101 [C:\Program Files\dotnet\sdk]
	3.1.201 [C:\Program Files\dotnet\sdk]
	3.1.302 [C:\Program Files\dotnet\sdk]
	5.0.100 [C:\Program Files\dotnet\sdk]
	5.0.200-preview.21077.7 [C:\Program Files\dotnet\sdk]
	5.0.201 [C:\Program Files\dotnet\sdk]

**Comment by jogibear9988** [comment] 2021-03-23 18:52
Okay, maybe I missread this.

I means when I install a newer SDK, compile agains Net461, I need to change my csproj, so it works again.

Also, If I change Type from WinExe to Exe via the visual Studio Project Settings, I think VisualStudio should add
DisableWinExeOutputInference
automaticly

**Comment by jogibear9988** [comment] 2021-03-23 18:55
Maybe you could add a Info to VS:
![image](https://user-images.githubusercontent.com/364896/112202417-a970b280-8c11-11eb-92a9-386e523f4aa1.png)

**Comment by jogibear9988** [comment] 2021-03-23 18:55
Maybe there would be a better message.

**Comment by jogibear9988** [comment] 2021-03-23 18:57
This is the Program I had the error with:
https://github.com/dotnetprojects/DotNetSiemensPLCToolBoxLibrary/blob/master/TiaGitHandler/Program.cs

It's a commandline utility, wich shows a WPF/Winforms UI when no Parameters are used

**Comment by batzen** [comment] 2021-03-23 18:59
Or maybe, just maybe, the SDK stops ignoring/overwriting the users explicit choice to produce a console exe.
I had to add `DisableWinExeOutputInference` to every Directory.build.props for my OSS projects and at work to avoid extreme user confusion.

**Comment by TysonMN** [comment] 2021-03-23 19:15
> Okay, maybe I missread this.
> 
> I means when I install a newer SDK, compile agains Net461, I need to change my csproj, so it works again.

Yes, I think that is the intended behavior.

> Or maybe, just maybe, the SDK stops ignoring/overwriting the users explicit choice to produce a console exe.
> I had to add `DisableWinExeOutputInference` to every Directory.build.props for my OSS projects and at work to avoid extreme user confusion.

I also think this change was a bad idea.

**Comment by TysonMN** [comment] 2021-03-23 19:15
I don't think has anything to do with WPF though, so @jogibear9988, I recommend closing this issue.

**Comment by jogibear9988** [comment] 2021-03-24 00:07
I haven't moved this issue to here.
I reported it at dotnet/runtime.
I don't think closing is the right solution. I think someone should move it to the correct repository (maybe runtime or a vs one).
And if behavior is not changed at all, I think my VisualStudio suggestions should be discussed.

**Comment by TysonMN** [comment] 2021-03-24 00:40
> I haven't moved this issue to here.
> I reported it at dotnet/runtime.

My impression is that your primary issue is with the intentional breaking change made to the .NET SDK in version 5.0.  I think the correct place to challenge that decision is [dotnet/sdk](https://github.com/dotnet/sdk).

> I don't think closing is the right solution. I think someone should move it to the correct repository (maybe runtime or a vs one).
> And if behavior is not changed at all, I think my VisualStudio suggestions should be discussed.

The correct place to request improvements to Visual Studio is the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/home).  I don't think it is possible to move an issue from GitHub to the VSDC.

I am not a big fan of moving issues.  The problem is that after its moved, everyone who reads that issue will also read this conversation we are having now, which will be a waste of their time.  Instead, you want those people to spend as much of their time thinking about your problem and fixing it.

I think it is also worth pointing out that you don't have to use the new .NET SDK with this breaking change.  You can keep using a previous version of the .NET SDK, and your builds will keep working just as well as they did before.

**Comment by reflectronic** [comment] 2021-03-28 16:11
See https://github.com/dotnet/wpf/issues/4138, which links to many issues in dotnet/sdk about this

**Comment by dsplaisted** [comment] 2021-08-13 21:28
Hi folks,

Sorry for the inconvenience this caused. We've reverted the change for .NET 6: https://github.com/dotnet/sdk/pull/19651

**Closed by dsplaisted** 2021-08-13 21:28 UTC
Labels: External Non-WPF Issue
