### ISSUE TITLE
On Intel Core 11 generation CPU, cannot refresh images continuously on the WriteableBitmap class of WPF

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#4273] opened 2021-03-11 18:51 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/On-Intel-Core-11-generation-CPU-cannot-/1364945)._

---
The WPF writeablebitmap object is used to refresh the image control in the order of red, green and blue. Only the color refreshed for the first time takes effect.

---
#### Feedback Bot on 3/10/2021, 07:21 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by lindexi** [comment] 2021-03-12 00:41
Duplicate of #3817 

[WPF - cannot redraw page on Intel 11th Core Iris Xe Integration graphic card · Issue #3817 · dotnet/wpf](https://github.com/dotnet/wpf/issues/3817 )

![图片](https://user-images.githubusercontent.com/16054566/110874468-bf779c80-830e-11eb-80e4-7ad6d84ce6a5.png)


See: https://github.com/dotnet/wpf/issues/3817#issuecomment-796687889

**Comment by wulong52569** [comment] 2021-03-12 02:34
Thank you very much for your reply. This problem has bothered me for a long time.

**Comment by ryalanms** [comment] 2021-03-15 18:30
Thanks, @lindexi.

**Comment by lindexi** [comment] 2021-06-10 07:09
@ryalanms  It's fixed by Intel, see https://github.com/dotnet/wpf/issues/3817#issuecomment-858237384 

And I think you can close this issues

**Closed** 2022-06-29 10:51 UTC
Labels: External Non-WPF Issue
