### ISSUE TITLE
Net Core 6: Microsoft Fakes and WPF Issue

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#9955] opened 2024-10-14 23:06 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Net-Core-6:-Microsoft-Fakes-and-WPF-Issu/10128442)._

---
Hello,

I'm in the progress of migrating our WPF from .Net 4.7.2 to .Net Core 6
I run into issues with our test projects that reference WPF and use Microsoft Fakes
Please see my demo repo here:
https://github.com/RoyRosenberg/msFakesWPF

Basically, the problem can be described like the following:
- Class Library project with true
- The project contains ControlDemo class that inherits from UserControl class
- MSTest project with reference to the class library project
- I added fakes assembly to the class lib. project

When trying to compile, I got the 20 errors related to Fakes generation, one of them is:

`Error CS7069 Reference to type 'DependencyObject' claims it is defined in 'WindowsBase', but it could not be found`

![image.png](https://aka.ms/dc/image?name=B6ceb79108abd4529bf4df59be7f4246e637968667681213058_20220823-185246-image.png&tid=6ceb79108abd4529bf4df59be7f4246e637968667681213058)

Please help me find out the problem
Thanks in advance,
Roy

---
#### Feedback Bot on 8/23/2022, 11:05 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Dolly Wang [MSFT] on 8/23/2022, 11:53 PM: 

<p>Thanks for your feedback! Unfortunately, we cannot reproduce the issue using your repo in the latest stable version of Visual Studio installed from <a target='_blank' href="https://visualstudio.microsoft.com/downloads">https://visualstudio.microsoft.com/downloads</a>.<br>
Could you update your Visual Studio to the latest version, and also delete the existing bin and obj folder in your repo, and then try again?</p>

#### Roy Rosenberg on 8/24/2022, 00:29 AM: 

<p>Hello,<br>
Thanks for the quick response</p>
<p>I just upgraded VS to 17.3.2<br>
I performed delete to all bin/obj and FakesAssemblies folders and performed a clean build, but the errors continue to appear…weird.<br>
I also cloned again the repo to a new folder but got the same errors</p>
<p><a target='_blank' href="https://aka.ms/dc/file?name=B5860864e38b845ccbaaa5ecb58f2ac0e637969228485191029_buildErrors.txt&amp;tid=5860864e38b845ccbaaa5ecb58f2ac0e637969228485191029">buildErrors.txt</a></p>
<p>My installed VS Info:</p>
<pre><code>Microsoft Visual Studio Enterprise 2022
Version 17.3.2
VisualStudio.17.Release/17.3.2+32819.101
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Enterprise

ASP.NET and Web Tools   17.3.376.3011
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.3.376.3011
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.3.376.3011
Azure Functions and Web Jobs Tools

C<span class="hljs-comment"># Tools   4.3.0-3.22412.4+c97184bafab9a34d61e85f1c1ef34f25283ce9ba</span>
C<span class="hljs-comment"># components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.</span>

Common Azure Tools   1.10
Provides common services for <span class="hljs-keyword">use</span> <span class="hljs-keyword">by</span> Azure Mobile Services <span class="hljs-keyword">and</span> Microsoft Azure Tools.

Microsoft Azure Tools <span class="hljs-keyword">for</span> Visual Studio   <span class="hljs-number">2.9</span>
Support <span class="hljs-keyword">for</span> Azure Cloud Services projects

Microsoft JVM Debugger   <span class="hljs-number">1.0</span>
Provides support <span class="hljs-keyword">for</span> connecting the Visual Studio debugger <span class="hljs-keyword">to</span> JDWP compatible <span class="hljs-keyword">Java</span> <span class="hljs-keyword">Virtual</span> Machines

NuGet <span class="hljs-keyword">Package</span> Manager   <span class="hljs-number">6.3</span><span class="hljs-number">.0</span>
NuGet <span class="hljs-keyword">Package</span> Manager <span class="hljs-keyword">in</span> Visual Studio. <span class="hljs-keyword">For</span> more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   <span class="hljs-number">17.0</span><span class="hljs-number">.0</span><span class="hljs-number">.2232702</span>+e1d654e792aa2fe6646a6935bcca80ff0aff4387
Provides languages services <span class="hljs-keyword">for</span> ASP.NET Core Razor.

<span class="hljs-keyword">SQL</span> <span class="hljs-keyword">Server</span> <span class="hljs-keyword">Data</span> Tools   <span class="hljs-number">17.0</span><span class="hljs-number">.62207</span><span class="hljs-number">.04100</span>
Microsoft <span class="hljs-keyword">SQL</span> <span class="hljs-keyword">Server</span> <span class="hljs-keyword">Data</span> Tools

TypeScript Tools   <span class="hljs-number">17.0</span><span class="hljs-number">.10701</span><span class="hljs-number">.2001</span>
TypeScript Tools <span class="hljs-keyword">for</span> Microsoft Visual Studio

Visual Basic Tools   <span class="hljs-number">4.3</span><span class="hljs-number">.0</span><span class="hljs-number">-3.22412</span><span class="hljs-number">.4</span>+c97184bafab9a34d61e85f1c1ef34f25283ce9ba
Visual Basic components used <span class="hljs-keyword">in</span> the IDE. Depending <span class="hljs-keyword">on</span> your <span class="hljs-keyword">project</span> <span class="hljs-keyword">type</span> <span class="hljs-keyword">and</span> <span class="hljs-keyword">settings</span>, a different <span class="hljs-keyword">version</span> <span class="hljs-keyword">of</span> the compiler may be used.

Visual F<span class="hljs-comment"># Tools   17.1.0-beta.22363.4+1b94f89d4d1f41f20f9be73c76f4b229d4e49078</span>
Microsoft Visual F<span class="hljs-comment"># Tools</span>

Visual Studio IntelliCode   <span class="hljs-number">2.2</span>
AI-assisted development <span class="hljs-keyword">for</span> Visual Studio.
</code></pre>

#### Roy Rosenberg on 8/24/2022, 01:05 AM: 

<p>Dolly Wang,</p>
<p>FYI - I attached the warning logs I think they also help us understand the root cause</p>
<p><a target='_blank' href="https://aka.ms/dc/file?name=B1c24f43849e64b3f9304078706fc73cc637969250710630963_warnings.txt&amp;tid=1c24f43849e64b3f9304078706fc73cc637969250710630963">warnings.txt</a></p>
<p>Got conflicts on WindowsBase:</p>
<pre><code>Found conflicts between different versions of <span class="hljs-string">"WindowsBase"</span> that could <span class="hljs-keyword">not</span> be resolved
</code></pre>

#### Dolly Wang [MSFT] on 8/23/2022, 11:55 PM: 

<p><a target='_blank' href="https://aka.ms/dc/file?name=B3e61ea1f39a046b49ab73e6cf7981e58637969209143667265_Build.PNG&amp;tid=3e61ea1f39a046b49ab73e6cf7981e58637969209143667265">Build.PNG</a><br>
<a target='_blank' href="https://aka.ms/dc/file?name=Be5bf79ce2f11462484aa1e2f6c212cab637969209256023456_NoError.PNG&amp;tid=e5bf79ce2f11462484aa1e2f6c212cab637969209256023456">NoError.PNG</a></p>

#### Dolly Wang [MSFT] on 8/24/2022, 01:37 AM: 

(private comment, text removed)
#### Roy Rosenberg on 8/24/2022, 09:27 AM: 

<p>Dolly Wang,</p>
<p>Thanks again for your help</p>
<p>Unfortunately, I cannot overcome it.<br>
I also tried from another machine with VS 2022 installed and got the same problem - I don’t know how it works on your side…<br>
I have VS 2019 and VS 2022 installed, both are up-to-date<br>
Here are the installed SDKs/Runtimes:</p>
<pre><code>5<span class="hljs-selector-class">.0</span><span class="hljs-selector-class">.411</span> <span class="hljs-selector-attr">[C:\Program Files\dotnet\sdk]</span>
6<span class="hljs-selector-class">.0</span><span class="hljs-selector-class">.400</span> <span class="hljs-selector-attr">[C:\Program Files\dotnet\sdk]</span>

<span class="hljs-selector-tag">Microsoft</span><span class="hljs-selector-class">.AspNetCore</span><span class="hljs-selector-class">.App</span> 3<span class="hljs-selector-class">.1</span><span class="hljs-selector-class">.28</span> <span class="hljs-selector-attr">[C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]</span>
<span class="hljs-selector-tag">Microsoft</span><span class="hljs-selector-class">.AspNetCore</span><span class="hljs-selector-class">.App</span> 5<span class="hljs-selector-class">.0</span><span class="hljs-selector-class">.17</span> <span class="hljs-selector-attr">[C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]</span>
<span class="hljs-selector-tag">Microsoft</span><span class="hljs-selector-class">.AspNetCore</span><span class="hljs-selector-class">.App</span> 6<span class="hljs-selector-class">.0</span><span class="hljs-selector-class">.8</span> <span class="hljs-selector-attr">[C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]</span>
<span class="hljs-selector-tag">Microsoft</span><span class="hljs-selector-class">.NETCore</span><span class="hljs-selector-class">.App</span> 3<span class="hljs-selector-class">.1</span><span class="hljs-selector-class">.28</span> <span class="hljs-selector-attr">[C:\Program Files\dotnet\shared\Microsoft.NETCore.App]</span>
<span class="hljs-selector-tag">Microsoft</span><span class="hljs-selector-class">.NETCore</span><span class="hljs-selector-class">.App</span> 5<span class="hljs-selector-class">.0</span><span class="hljs-selector-class">.17</span> <span class="hljs-selector-attr">[C:\Program Files\dotnet\shared\Microsoft.NETCore.App]</span>
<span class="hljs-selector-tag">Microsoft</span><span class="hljs-selector-class">.NETCore</span><span class="hljs-selector-class">.App</span> 6<span class="hljs-selector-class">.0</span><span class="hljs-selector-class">.8</span> <span class="hljs-selector-attr">[C:\Program Files\dotnet\shared\Microsoft.NETCore.App]</span>
<span class="hljs-selector-tag">Microsoft</span><span class="hljs-selector-class">.WindowsDesktop</span><span class="hljs-selector-class">.App</span> 3<span class="hljs-selector-class">.1</span><span class="hljs-selector-class">.28</span> <span class="hljs-selector-attr">[C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]</span>
<span class="hljs-selector-tag">Microsoft</span><span class="hljs-selector-class">.WindowsDesktop</span><span class="hljs-selector-class">.App</span> 5<span class="hljs-selector-class">.0</span><span class="hljs-selector-class">.17</span> <span class="hljs-selector-attr">[C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]</span>
<span class="hljs-selector-tag">Microsoft</span><span class="hljs-selector-class">.WindowsDesktop</span><span class="hljs-selector-class">.App</span> 6<span class="hljs-selector-class">.0</span><span class="hljs-selector-class">.8</span> <span class="hljs-selector-attr">[C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]</span>
</code></pre>
<p>I made sure all Nuget package versions are the latest<br>
What else can I do?<br>
Thanks,</p>

#### Feedback Bot on 8/24/2022, 06:06 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Roy Rosenberg on 8/28/2022, 09:23 PM: 

<p>Dolly Wang hi,</p>
<p>Hope you are doing well</p>
<p>I tried again on a 3rd computer, but got the same errors/warnings<br>
Is there any news on your end?</p>
<p>Thanks,<br>
Roy</p>

#### Roy Rosenberg on 9/1/2022, 11:41 PM: 

<p>Dolly Wang hi,<br>
I just wanted to inform you that the issue still exists. I cannot continue with the migration to .net core 6.0<br>
Please let me know if you have any progress regarding this<br>
Thansk for your help<br>
Roy</p>

#### Roy Rosenberg on 9/20/2022, 10:12 AM: 

<p>Hi,<br>
Still got no answer, and the problem persists<br>
Can someone please reply with an update?<br>
This ticket is more than 1 month and I managed to reproduce it on 5 different PCs<br>
Thanks,<br>
Roy</p>

#### Roy Rosenberg on 11/5/2022, 11:58 PM: 

<p>Hello,<br>
It’s been 3 months and the problem is not resolved<br>
We can not continue with the migration to .Net Core because of this<br>
Visual Studio 2022 is up to date<br>
The project NuGet references are all up to date<br>
still have an issue</p>
<pre><code><span class="hljs-selector-attr">[C:\Users\roy.rosenberg\Downloads\msFakesWPF-master\FakesWPFIssue.Test\obj\Debug\net6.0-windows\Fakes\fwpfi\f.csproj]</span>	<span class="hljs-selector-tag">FakesWPFIssue</span><span class="hljs-selector-class">.Test</span>	<span class="hljs-selector-tag">C</span>:\<span class="hljs-selector-tag">Program</span> <span class="hljs-selector-tag">Files</span>\<span class="hljs-selector-tag">Microsoft</span> <span class="hljs-selector-tag">Visual</span> <span class="hljs-selector-tag">Studio</span>\2022\<span class="hljs-selector-tag">Enterprise</span>\<span class="hljs-selector-tag">MSBuild</span>\<span class="hljs-selector-tag">Current</span>\<span class="hljs-selector-tag">Bin</span>\<span class="hljs-selector-tag">amd64</span>\<span class="hljs-selector-tag">Microsoft</span><span class="hljs-selector-class">.Common</span><span class="hljs-selector-class">.CurrentVersion</span><span class="hljs-selector-class">.targets</span>	2302	
</code></pre>
<p>Please help me overcome this<br>
Thanks in advanced,<br>
Roy</p>

#### Feedback Bot on 11/30/2022, 10:55 PM: 

<p>I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.</p>

#### Feedback Bot on 2/7/2023, 04:13 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
#### Pankaj Chaurasia [MSFT] solved on 7/5/2024, 01:24 AM, undefined votes: 

<p>We moved this issue to a relevant GitHub project. Please comment and track it at this URL: <a target='_blank' href="https://github.com/dotnet/wpf/issues/9359">https://github.com/dotnet/wpf/issues/9359</a></p>

**Comment by miloush** [comment] 2024-10-15 08:08
Should we close this one as duplicate of #9359?

**Comment by himgoyalmicro** [comment] 2024-10-16 05:28
Hello, 
Does your app work with .Net 8 ?

**Closed** 2024-10-16 05:29 UTC
