### ISSUE TITLE
Calling System.Windows.DataObject.GetData(DataFormats.FileDrop) throws COMException with long path names

### ISSUE THREAD

**Issue by smezger** [dotnet/wpf#3483] opened 2020-09-10 06:53 UTC
* .NET Core Version: 3.1.302
* Windows version: 1909 Build 18363.049)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes/No
 
 **Problem description:**
 Calling dataObject.GetData(DataFormats.FileDrop) with long path names (over 260 chars) leads to a COMException i.e. is not working.

 **Actual behavior:** 
Unhandled Exception: System.Runtime.InteropServices.COMException: The data area passed to a system call is too small.
 (Exception from HRESULT: 0x8007007A)

Callstack:   
  at System.Runtime.InteropServices.ComTypes.IDataObject.GetData(FORMATETC& format, STGMEDIUM& medium)
   at System.Windows.DataObject.OleConverter.GetDataFromOleHGLOBAL(String format, DVASPECT aspect, Int32 index)
   at System.Windows.DataObject.OleConverter.GetDataFromBoundOleDataObject(String format, DVASPECT aspect, Int32 index)
   at System.Windows.DataObject.OleConverter.GetData(String format, Boolean autoConvert, DVASPECT aspect, Int32 index)
   at System.Windows.DataObject.OleConverter.GetData(String format, Boolean autoConvert)
   at System.Windows.DataObject.GetData(String format, Boolean autoConvert)
   at System.Windows.DataObject.GetData(String format)

 **Expected behavior:**
 Support drag and drop of files with long path names (or provide meaningful error)
 **Minimal repro:**
https://github.com/smezger/WpfLongPathProblem

**Comment by ryalanms** [comment] 2020-09-14 18:45
Hi @smezger

Does this repro on .NET 4.8?  Thanks.

**Comment by smezger** [comment] 2020-09-15 05:57
Hi @ryalanms 
yes same for .NET 4.8, check sample repo `WpfAppLongPath48` project!

**Comment by kprueckl** [comment] 2021-01-24 09:43
I see the same issue on .NET Core 5.0 - especially with files on ReFS.

**Comment by kprueckl** [comment] 2021-04-12 17:05
It seems that the issue has been silently fixed with one of the latest .NET 5.0 versions - at least shipped with VS2019 16.9.3, which I've just noticed by trying again (maybe it was solved already earlier). A bit disappointing that the community is not updated here, since I was waiting for a notification.

**Comment by neelabo** [comment] 2022-07-27 07:13
I see the same issue on .NET 6.0

**Comment by anjali-wpf** [comment] 2023-09-12 09:48
@smezger - The cause of this issue is the inability of the underlying system API to return the data requested for the filestream if the filepath exceeds 260 characters. 

There is an option to enable longer file paths which instructs the underlying API to substitute a longer file path with a shorter one (with several characters replaced).

Here's a link explaining the steps to enable this on Windows. 
[https://thegeekpage.com/make-windows-11-accept-file-paths-over-260-characters/](https://thegeekpage.com/make-windows-11-accept-file-paths-over-260-characters/)

As such, there is very little that WPF can do wrt this.

**Closed** 2023-10-03 13:01 UTC
Labels: Bug, :mailbox_with_no_mail: waiting-author-feedback, :zzz: no-recent-activity
