### ISSUE TITLE
TypeInitializationException in System.Windows.Media.FontFamily

### ISSUE THREAD

**Issue by albahari** [dotnet/wpf#771] opened 2019-05-28 09:11 UTC
* .NET Core Version: 3.0.0preview6.19270.
* Windows version: 10.0.17763.0
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 **Problem description:**

I have a WPF app in beta that targets .NET Core 3. When some users run it, it crashes with a TypeInitializationException - The type initializer for 'System.Windows.Media.FontFamily' threw an exception. I've contacted one of the users who has tried it on another machine and got the same error.

I've attached a full stack trace including IL offsets. 
[stacktrace.txt](https://github.com/dotnet/wpf/files/3226579/stacktrace.txt)

**Comment by Symbai** [comment] 2019-05-28 10:13
I've reported the same issue in corefx repo https://github.com/dotnet/corefx/issues/37956
This issue only happens since Preview 6 so if you downgrade to preview 5 it should work.

**Comment by mikedn** [comment] 2019-05-28 11:17
I'm not sure if the fact that the other issue was closed implies that the bugfix has flown into an SDK build. I have 3.0.0-preview6-27727-01 locally (AFAIR I installed it just yesterday) and I'm seeing the exact same behavior I've seen before the fix.

The stack trace you have posted also shows that the original exception came from `Factory::Initialize`:
```
MS.Internal.Text.TextInterface.Factory.Initialize(factoryType) offset=0x23
```

**Comment by rprouse** [comment] 2019-05-28 14:39
I can reproduce this issue on two of my machines using @albahari's beta if you need any help tracking down the problem.

**Comment by rladuca** [comment] 2019-05-28 17:17
The JIT change @albahari linked is the general fix for the issue, but WPF was able to work around this in #725 .  However, it seems neither of these have made the daily builds just yet.  This sort of got caught up with the large code drop as well since, before that, `DirectWriteForwarder` was built from an internal repo.

Those updates (along with this one) have started to flow today and the daily builds should have them soon.

I'm going to close this as a duplicate of #725.

**Closed by rladuca** 2019-05-28 17:17 UTC

**Comment by Lakritzator** [comment] 2019-06-06 13:35
I don't want to ask you when we can expect this fix, you can take as long as you need!

But I wonder how can we see what fixes are in a certain build?

I'm currently using SDK 3.0.100-preview7-012278, and the issue is still there:
```
************** Exception Text **************
System.InvalidCastException: Specified cast is not valid.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)
   at MS.Internal.Text.TextInterface.Native.Util.ConvertHresultToException(Int32 hr)
   at MS.Internal.Text.TextInterface.Factory.Initialize(FactoryType factoryType)
   at MS.Internal.Text.TextInterface.Factory..ctor(FactoryType factoryType, IFontSourceCollectionFactory fontSourceCollectionFactory, IFontSourceFactory fontSourceFactory)
   at MS.Internal.Text.TextInterface.Factory.Create(FactoryType factoryType, IFontSourceCollectionFactory fontSourceCollectionFactory, IFontSourceFactory fontSourceFactory)
   at MS.Internal.FontCache.DWriteFactory..cctor()
```

**Comment by rladuca** [comment] 2019-06-06 16:46
@Lakritzator Are you 100% sure the machine you are running on has Preview 7 builds installed and that your application is indeed loading binaries from a Preview 7 build?  If it was a self-contained application it could be using an old version or you could be running specifically against an older version of the framework if you haven't rebuilt.

If you debug your application in Visual Studio and open the modules window, you can check where `DirectWriteForwarder` is loading from.  If it's from the shared framework (in a Program Files directory) then the version of `WindowsDesktop` is loads from should be `3.0.0-preview7.27805-02`.  If it's loading from some other version that is older, make sure you update.  If it's loading from a self-contained location (side by side with the application), make sure you publish again with the new SDK so that the new files make their way into the application.

I just tested this by installing `3.0.100-preview7-012279` and building an application against the shared framework and it ran without issue, loading `DirectWriteForwarder` fine.

**Comment by Lakritzator** [comment] 2019-06-06 21:04
I'm very sure about the version, but I now realized this issue only shows when I do a single exe publish with trimming. Sorry to have confused you.

**Comment by rladuca** [comment] 2019-06-06 22:02
@Lakritzator All good, thanks for checking into it further!

**Comment by bizzbizz** [comment] 2019-07-02 11:42
I've been following this issue around and I guess it's the same in all of the `3.0.0-preview` versions.

I am using `3.0.0-preview6-27804-01`. Here's the minimal steps to repro it:

1. Create a WPF application.
2. Add the following code to the MainWindow.xaml
`<TextBox Height="40" Width="300" Text="some text..."/>`

3. Set PropertyGroup of the csproj to:
```
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishSingleFile>true</PublishSingleFile>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
```
4. run `dotnet publish -r win-x64 -c release`
5. see the app does not open.

However,
the app opens, if you write `<Rectangle/>` instead of `<TextBox/>`
