### ISSUE TITLE
Binding errors occurs in NET 7.0

### ISSUE THREAD

**Issue by DhivyaBharathi-SF3890** [dotnet/wpf#8214] opened 2023-09-13 05:48 UTC
### Description

Binding errors occurred in the WPF .NET 7.0 project, even without the use of any controls, including the Grid.

simple NET7.0 sample:
[WpfApp1.zip](https://github.com/dotnet/wpf/files/12593678/WpfApp1.zip)

**Binding errors:**
````
System.Windows.Data Information: 10 : Cannot retrieve value using the binding and no valid fallback value exists; using default instead. BindingExpression:Path=UserOptions.ShowLiveVisualTreeCommand; DataItem=null; target element is 'ButtonNoStyle' (Name='ShowLiveVisualTree'); target property is 'Command' (type 'ICommand')
System.Windows.Data Information: 10 : Cannot retrieve value using the binding and no valid fallback value exists; using default instead. BindingExpression:Path=StartLivePreviewCommand; DataItem=null; target element is 'ButtonNoStyle' (Name='StartLivePreview'); target property is 'Command' (type 'ICommand')
System.Windows.Data Information: 10 : Cannot retrieve value using the binding and no valid fallback value exists; using default instead. BindingExpression:Path=UserOptions.IsInAppSelectionEnabled; DataItem=null; target element is 'ToggleButtonNoStyle' (Name='InAppSelection'); target property is 'IsChecked' (type 'Nullable`1')
System.Windows.Data Information: 10 : Cannot retrieve value using the binding and no valid fallback value exists; using default instead. BindingExpression:Path=ToggleInAppSelectionTooltip; DataItem=null; target element is 'ToggleButtonNoStyle' (Name='InAppSelection'); target property is 'ToolTip' (type 'Object')
System.Windows.Data Information: 10 : Cannot retrieve value using the binding and no valid fallback value exists; using default instead. BindingExpression:Path=UserOptions.IsLayoutAdornersEnabled; DataItem=null; target element is 'ToggleButtonNoStyle' (Name='LayoutAdorners'); target property is 'IsChecked' (type 'Nullable`1')
System.Windows.Data Information: 10 : Cannot retrieve value using the binding and no valid fallback value exists; using default instead. BindingExpression:Path=UserOptions.IsTrackFocusedElementEnabled; DataItem=null; target element is 'ToggleButtonNoStyle' (Name='TrackFocusedElement'); target property is 'IsChecked' (type 'Nullable`1')
System.Windows.Data Information: 10 : Cannot retrieve value using the binding and no valid fallback value exists; using default instead. BindingExpression:Path=UserOptions.IsBindingFailuresVisible; DataItem=null; target element is 'Rectangle' (Name=''); target property is 'Visibility' (type 'Visibility')
System.Windows.Data Information: 10 : Cannot retrieve value using the binding and no valid fallback value exists; using default instead. BindingExpression:Path=UserOptions.ShowBindingFailuresCommand; DataItem=null; target element is 'ButtonNoStyle' (Name='BindingFailures'); target property is 'Command' (type 'ICommand')
System.Windows.Data Information: 10 : Cannot retrieve value using the binding and no valid fallback value exists; using default instead. BindingExpression:Path=UserOptions.BindingFailuresTooltip; DataItem=null; target element is 'ButtonNoStyle' (Name='BindingFailures'); target property is 'ToolTip' (type 'Object')
System.Windows.Data Information: 10 : Cannot retrieve value using the binding and no valid fallback value exists; using default instead. BindingExpression:Path=UserOptions.IsBindingFailuresVisible; DataItem=null; target element is 'ButtonNoStyle' (Name='BindingFailures'); target property is 'Visibility' (type 'Visibility')
System.Windows.Data Information: 10 : Cannot retrieve value using the binding and no valid fallback value exists; using default instead. BindingExpression:Path=UserOptions.BindingFailuresCount; DataItem=null; target element is 'Rectangle' (Name=''); target property is 'Visibility' (type 'Visibility')
System.Windows.Data Information: 10 : Cannot retrieve value using the binding and no valid fallback value exists; using default instead. BindingExpression:Path=UserOptions.BindingFailuresCount; DataItem=null; target element is 'Rectangle' (Name=''); target property is 'Visibility' (type 'Visibility')
System.Windows.Data Information: 10 : Cannot retrieve value using the binding and no valid fallback value exists; using default instead. BindingExpression:Path=UserOptions.BindingFailuresCount; DataItem=null; target element is 'TextBlockNoStyle' (Name='BindingFailuresCountText'); target property is 'Visibility' (type 'Visibility')
System.Windows.Data Information: 10 : Cannot retrieve value using the binding and no valid fallback value exists; using default instead. BindingExpression:Path=UserOptions.BindingFailuresCountText; DataItem=null; target element is 'TextBlockNoStyle' (Name='BindingFailuresCountText'); target property is 'Text' (type 'String')
System.Windows.Data Information: 10 : Cannot retrieve value using the binding and no valid fallback value exists; using default instead. BindingExpression:Path=ShowAccessibilityCheckerCommand; DataItem=null; target element is 'ButtonNoStyle' (Name='ShowAccessibilityChecker'); target property is 'Command' (type 'ICommand')
System.Windows.Data Information: 10 : Cannot retrieve value using the binding and no valid fallback value exists; using default instead. BindingExpression:Path=HotReloadTooltip; DataItem=null; target element is 'ButtonNoStyle' (Name='HotReloadHelp'); target property is 'ToolTip' (type 'Object')
System.Windows.Data Information: 10 : Cannot retrieve value using the binding and no valid fallback value exists; using default instead. BindingExpression:Path=HotReloadHelpCommand; DataItem=null; target element is 'ButtonNoStyle' (Name='HotReloadHelp'); target property is 'Command' (type 'ICommand')
System.Windows.Data Information: 10 : Cannot retrieve value using the binding and no valid fallback value exists; using default instead. BindingExpression:Path=IsHotReloadAvailable; DataItem=null; target element is 'Rectangle' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Information: 10 : Cannot retrieve value using the binding and no valid fallback value exists; using default instead. BindingExpression:Path=IsHotReloadAvailable; DataItem=null; target element is 'Rectangle' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Information: 10 : Cannot retrieve value using the binding and no valid fallback value exists; using default instead. BindingExpression:Path=NextExpandStateCommand; DataItem=null; target element is 'ButtonNoStyle' (Name='HotReloadExpander'); target property is 'Command' (type 'ICommand')
System.Windows.Data Information: 10 : Cannot retrieve value using the binding and no valid fallback value exists; using default instead. BindingExpression:Path=NextExpandStateCommand; DataItem=null; target element is 'ButtonNoStyle' (Name='InAppMenuExpander'); target property is 'Command' (type 'ICommand')
````
### Reproduction Steps

Way 1:
1.Enable binding errors and Run the provided sample 

Way 2:
1. Create a simple NET7.0 sample and enable binding errors 
2.Run the sample

Observed Behavior:
Binding error occurs

### Expected behavior

Binding errors should not occur

### Actual behavior

Binding errors are occurred

### Configuration

.NET Version - .NET 7.0
OS Version - Windows 10 21H2
Architecture - Anu CPU

**Comment by pchaurasia14** [comment] 2023-09-13 06:13
@DhivyaBharathi-SF3890  - I ran the sample you've provided and I don't see any errors (neither on the app nor in VS (Version 17.7.3))

![image](https://github.com/dotnet/wpf/assets/105205215/bd240a51-8697-4c38-b75c-7f14b3174fd5)

Can you share the exact location where you're seeing this error?
Also, if you have an xaml extension installed, it may be a side effect of a failure reported in it.

**Comment by miloush** [comment] 2023-09-13 09:13
I would think this is duplicate of #7838. These are not error, there are information messages.

**Comment by DhivyaBharathi-SF3890** [comment] 2023-09-13 11:10
@pchaurasia14  Set the Data Binding option as All to see the Binding errors.
![image](https://github.com/dotnet/wpf/assets/113903149/4e6803e5-5b25-4777-844a-bed3af3f59eb)

In output Window we can able to see the binding errors
![image](https://github.com/dotnet/wpf/assets/113903149/daeab34c-50a4-4f85-8b44-93a165860f1c)

**Comment by pchaurasia14** [comment] 2023-09-13 11:31
@DhivyaBharathi-SF3890 - As mentioned by @miloush above, these are informational traces and it is simply letting you know that the binding value was not found and hence default value is being used. 

Unless this is interfering with any functionality in your app, you may simply ignore these messages.

**Closed** 2023-10-04 13:01 UTC
Labels: :mailbox_with_no_mail: waiting-author-feedback, :zzz: no-recent-activity
