### ISSUE TITLE
SoldidColorBrush created from BrushConverter(). ConvertFrom method does not work in a ValueConverter 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5674] opened 2021-11-09 18:24 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/SoldidColorBrush-created-from-BrushConve/1468736)._

---
[regression] [worked-in:?]
! [SolidColorBrush.png] (https://aka.ms/dc/image?name=Bea2e435819fe4d4fbdb2883700ebcb68637611762643440184_SolidColorBrush.png&tid=ea2e435819fe4d4fbdb2883700ebcb68637611762643440184)

When I use ' SolidColorBrush brush = new SolidColorBrush(color: Colors.Gainsboro);' it changes the backgroundcolor.
If i use SolidColorBrush brush = (SolidColorBrush)(new BrushConverter(). ConvertFrom("#CCFF0000"));  the backgroundcolor stays always red even if the value becomes true .
Happend after update to 16.10.3 and is's quite a while ago since i ran this code. As I update as soon as there is an update, i can't remember the last working version !

---
#### Feedback Bot on 7/7/2021, 00:15 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/9/2021, 02:04 AM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by pchaurasia14** [comment] 2022-06-30 12:20
We are unable to reproduce this issue with .NET 6.

![image](https://user-images.githubusercontent.com/105205215/176675443-95ef6dc6-99bc-4c39-bbff-f736af809f7c.png)

Let us know if you are still having this issue.

**Comment by dipeshmsft** [comment] 2022-08-23 12:14
Closing this as this is working in .NET 6. If the issue persists, please reopen the issue.

**Closed by dipeshmsft** 2022-08-23 12:14 UTC
Labels: needs more information
