### ISSUE TITLE
Image Source fails to load an image if application path has hash sign in it

### ISSUE THREAD

**Issue by lncubus** [dotnet/wpf#6560] opened 2022-05-09 19:37 UTC
* .NET Core Version: 6.0.4
* Windows version: Windows 11 21H2
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes

 
 
 **Problem description:**
It is possible to specify Image source with relative path in XAML definition:
`Icon="Images/app.dark.png"`
However, this definition fails to load image if the path containing application has `#` symbol.
 
 **Actual behavior:** 
In .Net 6
Fails in `BitmapDecoder.SetupDecoderFromUriOrStream` with `System.IO.DirectoryNotFoundException`
which transforms to exception going out:
`System.Windows.Markup.XamlParseException: "System.Windows.Baml2006.TypeConverterMarkupExtension" throws an exception."`

 **Expected behavior:**
 We should load image with relative path without crash.

 **Minimal repro:**
1. Create a WPF application
2. Add image in subfolder and specify its Build Action as Content and Copy to Output Directory as Copy or Copy if newer
3. Specify main window Icon image with relative path
`<Window x:Class="WpfApp1.MainWindow"
        Icon="Images/app.dark.png">`
4. Start an application and check everything is okay
5. Rename the project path into `#WpfApp1`
6. Start an application
7. Get an exception shown above

**Comment by lncubus** [comment] 2022-05-09 19:48
Exception details
[ex1.txt](https://github.com/dotnet/wpf/files/8654888/ex1.txt)

**Comment by lncubus** [comment] 2022-05-10 15:12
A minimal example for .NET 6
[LoadingImageSource_Net6.zip](https://github.com/dotnet/wpf/files/8662787/LoadingImageSource_Net6.zip)
A minimal example for .Net Framework 4.8
[LoadingImageSource_Net48.zip](https://github.com/dotnet/wpf/files/8662788/LoadingImageSource_Net48.zip)

**Comment by lncubus** [comment] 2022-05-10 15:21
Original issue:
[microsoft/PowerToys/issues/17652](https://github.com/microsoft/PowerToys/issues/17652)

**Comment by lindexi** [comment] 2022-05-11 02:15
@lncubus Thank you.

Duplicate of https://github.com/dotnet/wpf/issues/4781

And I fixed it in https://github.com/dotnet/wpf/pull/5066

**Comment by dipeshmsft** [comment] 2022-05-18 06:23
Yeah, as @lindexi mentioned this is a duplicate of #4781, hence we are marking it closed as of now and will keep tracking the bug from the original issue. Also, we will take a look at the PR #5066 from @lindexi, to get to a resolution.

**Closed by dipeshmsft** 2022-05-18 06:23 UTC
