### ISSUE TITLE
StringFormat doesn't return the correct currency format

### ISSUE THREAD

**Issue by DannyLee89** [dotnet/wpf#4539] opened 2021-05-19 13:50 UTC
* .NET Core Version: 5
* Windows version: Windows 10 Pro
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No

 
 
 **Problem description:**
Binding to a decimal value using the currency StringFormat ("c") produces the wrong output for (en-US) culture with CurrencyNegativePattern=0.

 
 **Actual behavior:** 
"-$123.45"
 
 **Expected behavior:**
"($123.45)"
 
 **Minimal repro:**
View Model
```
public class TestViewModel
{
    public decimal DecimalValue { get; set; } = -123.45M;
    public string FormattedValue
    {
        get
        {
            return DecimalValue.ToString("c");
        }
    }
}
```

XAML Binding
```
<Window.DataContext>
    <local:TestViewModel x:Name="vm"/>
</Window.DataContext>
<StackPanel>
    <StackPanel Margin="20">
        <TextBox Text="{Binding DecimalValue, StringFormat=c}"/>
        <TextBox Text="{Binding FormattedValue, Mode=OneWay}"/>
    </StackPanel>

    <StackPanel Margin="20">
        <TextBlock Text="{Binding DecimalValue, StringFormat=c}"/>
        <TextBlock Text="{Binding FormattedValue, Mode=OneWay}"/>
    </StackPanel>
</StackPanel>
```

Example Output
![image](https://user-images.githubusercontent.com/5075637/118823971-0dfd6600-b87f-11eb-9b35-5a4ee4544d49.png)

**Comment by miloush** [comment] 2021-05-24 16:05
> Does the bug reproduce also in WPF for .NET Framework 4.8?: No

Reproduces on net48 too.

However, this is expected behavior. The `ToString` method without any format provider uses the current culture to format the string. 

See the documentation [here](https://docs.microsoft.com/en-us/dotnet/standard/base-types/formatting-types#culture-sensitive-formatting-of-numeric-values):
> By default, the formatting of numeric values is culture-sensitive. If you do not specify a culture when you call a formatting method, the formatting conventions of the current thread culture are used.

The binding on the other side uses the language specified in XAML [by design](http://web.archive.org/web/20120628224036/https://connect.microsoft.com/VisualStudio/feedback/details/442569/wpf-binding-uses-the-wrong-currentculture-by-default).

You can change the binding behavior by either setting `ConvertCulture` parameter of the binding, or changing the XAML language using `Language` property (e.g. on the `Window`) or `xml:lang` attribute.

**Comment by DannyLee89** [comment] 2021-05-24 18:01
> Reproduces on net48 too.

Can you detail how you tested this?

I created a sample C# WPF project targeting .Net Framework 4.8 using the same code as I detailed above. The resulting output was not the same.  It returned "($123.45)" in all situations, which is the behavior I expected and has worked in previous WPF projects targeting .Net Framework.

![image](https://user-images.githubusercontent.com/5075637/119387366-789f0f00-bc8e-11eb-888f-87298c3068eb.png)

I understand that the output here depends on the culture being used.  I assumed that in all these scenarios the current culture would default to the same value, and indeed they do ("en-US" for me).  Even with the same culture, however, between a WPF app targeting .Net 5 and WPF app targeting .Net Framework 4.8 return different results.

**Comment by miloush** [comment] 2021-05-24 18:15
Well I tested on 4.8 only in fact, and got different results:
![image](https://user-images.githubusercontent.com/10546952/119389754-f29dbb00-bcc3-11eb-81d7-7edc0f42578d.png)

Maybe provide some details on what cultures you are using? If you have customized the culture there is also #1946.

**Comment by DannyLee89** [comment] 2021-05-24 20:12
What details are you interested in?  I haven't customized the culture at all for these tests, just using default values for the "en-US" culture.

Here is a snapshot of my `CurrentCulture` if it helps:
![image](https://user-images.githubusercontent.com/5075637/119400977-7f368200-bca0-11eb-8cab-20b5d462e8bb.png)

Regardless of the culture being used though, am I correct in assuming that if using the same culture settings and given the same input, `ToString("c")` and `StringFormat=c` should produce the same output?

**Comment by miloush** [comment] 2021-05-24 20:51
Oh okay, I tried on .NET Core now, and the output is different, but that is because the pattern is different:

![image](https://user-images.githubusercontent.com/10546952/119405782-b83f1880-bcd9-11eb-898d-7e291180a993.png)

I don't know why that is but it wouldn't be a WPF issue.


> Regardless of the culture being used though, am I correct in assuming that if using the same culture settings and given the same input, `ToString("c")` and `StringFormat=c` should produce the same output?

Not really, for example as I mentioned, if the user overrides the culture settings. What you can do is use a value converter for the binding, and inspect the `CultureInfo` that gets passed in.

**Comment by DannyLee89** [comment] 2021-05-24 21:38
Right, that's the behavior that I was seeing.  According to [this documentation](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.numberformatinfo.currencynegativepattern?view=net-5.0#remarks), it seemed like the CurrencyNegativePattern was behaving as if it were set to 1.  Which in my last comment you can see that for my CurrentCulture it is set to 0, so that was my reasoning for submitting the bug.

I did as you suggested and created a value converter and inspected the culture being passed in.  I do in fact see that the culture's NumberFormat contains a CurrencyNegativePattern=1, so that is the reason for the difference.  My apologies for submitting the bug in the wrong place.  I assumed they were both using the CurrentCulture to do the formatting.

However, since they're both utilizing the same culture.  I feel like the CurrencyNegativePattern should be defaulted to 0 though instead of 1 to be consistent.  Do you know if this change is intentional?  Or is there another place I should post this issue?

Thanks for your help in getting to the bottom of this.

**Comment by miloush** [comment] 2021-05-25 11:24
If think the change is a result of switching from Windows culture data to ICU: https://docs.microsoft.com/en-us/dotnet/core/compatibility/globalization/5.0/icu-globalization-api

As such I am afraid the change would be intentional.

(Also by "customized culture" I mean changing preferred format in the Settings or Control Panel. I cannot really seem to be able to get an en-US culture with 0 negative currency pattern on .NET Core out of the box.)

**Comment by dipeshmsft** [comment] 2022-08-24 04:48
@DannyLee89  @miloush, as per my understanding we have reached to a conclusion on this issue, right ?? Is it alright to close this ?

**Comment by dipeshmsft** [comment] 2022-08-24 09:03
Closing this issue

**Closed by dipeshmsft** 2022-08-24 09:03 UTC
Labels: needs more information
