### ISSUE TITLE
Vertical scroll bar is not visible when horizantal scroll bar moved to extreme left in wpf datagrid

### ISSUE THREAD

**Issue by Siyumii** [dotnet/wpf#2794] opened 2020-03-20 09:09 UTC
I am currently developing a WPF application where it has a WPF data grid. The issue I'm facing here is,when I scroll horizontal scroll bar to extreme left side, Vertical scroll bar is not visible.I have mentioned what I have tried in below. Further,I got this below code snippet using a answer provided for this [link ](https://stackoverflow.com/questions/5975737/wpf-datagrid-horizontal-scrollbar-not-showing)

```
<ScrollViewer HorizontalScrollBarVisibility="Auto"
              VerticalScrollBarVisibility="Disabled">
    <DataGrid>
        ...
    </DataGrid>
</ScrollViewer>
```
Any guidance or suggestion will be much appreciated!

**Comment by weltkante** [comment] 2020-03-20 09:18
Looks like it is working as intended, by putting the `ScrollViewer` around the entire `DataGrid` you include the vertical scrollbar in the scrolled region. Maybe you should create an issue for the problem you are trying to solve, not for the side effects you encounter when you try to use a bad workaround.

**Comment by gomathip02** [comment] 2020-03-26 20:52
Closing this issue as this is by design.

**Closed by gomathip02** 2020-03-26 20:52 UTC
