### ISSUE TITLE
There is a serious bug in patch KB5020613--wpf

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#7415] opened 2023-01-04 18:54 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/There-is-a-serious-bug-in-patch-KB502061/10222103)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:KB5020613]
Update to patch KB5020613, insert record into WPF DataGrid index 0，datagrid cannot be automatically scrolled to the top。

The bug in patch KB5020613. when i uninstall KB5020613, datagrid is ok. We find the bug in win10_home win10_Professional and windows server 2019 ...

**before uninstall KB5020613:**
![update1.png](https://aka.ms/dc/image?name=B6863249695194abfa081203dbea7903f638058907365075116_update1.png&tid=6863249695194abfa081203dbea7903f638058907365075116)
![datagrid.gif](https://aka.ms/dc/image?name=B070ccfbeeae4418b9b0e915ffea0cc1c638058907531721101_datagrid.gif&tid=070ccfbeeae4418b9b0e915ffea0cc1c638058907531721101)

**after uninstall KB5020613:**
![267260-image.png](https://aka.ms/dc/image?name=Bdc29b2e99b184e16b7c07fb7f7ffb6e7638058907988660510_267260-image.png&tid=dc29b2e99b184e16b7c07fb7f7ffb6e7638058907988660510)
![267361-datagrid-ok.gif](https://aka.ms/dc/image?name=B8e556fe64a2449748b3103a576243d9c638058908148447704_267361-datagrid-ok.gif&tid=8e556fe64a2449748b3103a576243d9c638058908148447704)

OS：
![267290-image.png](https://aka.ms/dc/image?name=B46aca708bd6145f0ab0817173116b2fd638058908449907868_267290-image.png&tid=46aca708bd6145f0ab0817173116b2fd638058908449907868)

Microsoft Visual Studio Community 2019
版本 16.11.21
VisualStudio.16.Release/16.11.21+33027.164
Microsoft .NET Framework
版本 4.8.04084

已安装的版本: Community

Visual C++ 2019 00435-00000-00000-AA733
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019 16.11.110.1451
ASP.NET and Web Tools 2019

Azure 应用服务工具 3.0.0 版 16.11.110.1451
Azure 应用服务工具 3.0.0 版

C# 工具 3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
IDE 中使用的 C# 组件。可能使用其他版本的编译器，具体取决于你的项目类型和设置。

IntelliCode 扩展 1.0
IntelliCode Visual Studio 扩展详细信息

JetBrains ReSharper 2022.2.3 Build 222.0.20220901.62528
JetBrains ReSharper package for Microsoft Visual Studio. For more information about ReSharper, visit http://www.jetbrains.com/resharper. Copyright © 2022 JetBrains, Inc.

Microsoft JVM Debugger 1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger 1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ 向导 1.0
Microsoft Visual C++ 向导

Microsoft Visual Studio VC 软件包 1.0
Microsoft Visual Studio VC 软件包

NuGet 包管理器 5.11.2
Visual Studio 中的 NuGet 包管理器。有关 NuGet 的详细信息，请访问 https://docs.nuget.org/

ProjectServicesPackage Extension 1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Visual Basic 工具 3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
IDE 中使用的 Visual Basic 组件。可能使用其他版本的编译器，具体取决于你的项目类型和设置。

Visual F# Tools 16.11.0-beta.21514.6+b6c2c4f53ea3a08fa603ea93d6d2f808a62a21d1
Microsoft Visual F# Tools

Visual Studio Code 调试适配器主机包 1.0
用于在 Visual Studio 中托管 Visual Studio Code 调试适配器的互操作层

Visual Studio Tools for CMake 1.0
Visual Studio Tools for CMake

适用于 Google Test 的测试适配器 1.0
启用带有针对 Google Test 编写的单元测试的 Visual Studio 测试工具。扩展安装目录中提供了使用条款和第三方通知。

通用 Azure 工具 1.10
通过 Azure 移动服务和 Microsoft Azure Tools 提供通用服务。

用于 Boost.Test 的测试适配器 1.0
通过针对 Boost.Test 编写的单元测试启用 Visual Studio 测试工具。扩展安装目录中提供用户条款和第三方通知。

---
#### Feedback Bot on 12/5/2022, 07:04 PM: 

(private comment, text removed)
#### Dolly Wang [MSFT] on 12/7/2022, 01:53 AM: 

(private comment, text removed)
#### 詹晓海 on 12/7/2022, 06:18 AM: 

(private comment, text removed)
#### Dolly Wang [MSFT] on 12/8/2022, 05:06 AM: 

(private comment, text removed)
#### Feedback Bot on 12/20/2022, 10:54 PM: 

(private comment, text removed)
#### Feedback Bot on 12/27/2022, 00:29 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by miloush** [comment] 2023-01-04 18:57
sounds like duplicate of #7199

**Comment by dipeshmsft** [comment] 2023-01-05 03:06
Yes, this is a duplicate of #7199, and the fix for the bug is already shipped.

**Comment by dipeshmsft** [comment] 2023-01-06 05:03
Closing this as it is a duplicate of #7199. Further discussions, regarding the fix will continue on the previous issue.

**Closed by dipeshmsft** 2023-01-06 05:03 UTC
