### ISSUE TITLE
Reference markup extension is missed

### ISSUE THREAD

**Issue by pavelovcharov** [dotnet/wpf#273] opened 2019-01-17 13:07 UTC
The System.Windows.Markup.Reference class is missed in NetCore3, although the WPF implementation seems to work as expected
```
[ContentProperty("Name")]
public class Reference : MarkupExtension {
    public Reference() {
    }

    public Reference(string name) {
        Name = name;
    }

    [ConstructorArgument("name")]
    public string Name { get; set; }

    public override object ProvideValue(IServiceProvider serviceProvider) {
        if(serviceProvider == null)
            throw new ArgumentNullException(nameof(serviceProvider));
        IXamlNameResolver service = serviceProvider.GetService(typeof(IXamlNameResolver)) as IXamlNameResolver;
        if(service == null)
            throw new InvalidOperationException("MissingNameResolver");
        if(string.IsNullOrEmpty(Name))
            throw new InvalidOperationException("MustHaveName");
        object obj = service.Resolve(Name);
        if(obj == null) {
            string[] strArray = new string[1] { Name };
            obj = service.GetFixupToken(strArray, true);
        }
        return obj;
    }
}
```
[ReferenceTest.zip](https://github.com/dotnet/wpf/files/2768688/ReferenceTest.zip)

**Comment by rladuca** [comment] 2019-01-17 17:16
This is an issue with the XMLNS definitions in the reference assembly for System.Xaml.  This work is covered by #119 .  

I had previously done a fixup, but accidentally merged an incomplete fix, you should see this fix in the latest daily build (3.0.0-preview-27315-14) of the WindowsDesktop SDK.

Dupe of #119

**Closed by rladuca** 2019-01-17 17:16 UTC
