### ISSUE TITLE
Fluent Theme: Inconsistent `Label` style

### ISSUE THREAD

**Issue by bent-rasmussen** [dotnet/wpf#9960] opened 2024-10-15 15:47 UTC
### Description

`Label` has a different style depending on whether it is inside an `Expander` or outside one:

![Image](https://github.com/user-attachments/assets/df06ea47-be9b-42b3-a9cc-144cbc57aaef)

It will be hard to make consistent UX with such differences. Instead of using a `Border`, one will be forced to use an `Expander` to get better usability for labels - or overriding the default `Label` style.

### Reproduction Steps

1. Create a .NET 9 WPF application with the Fluent style in `App.xaml`.
2. Overwrite the default `MainWindow.xaml` with this:
```xaml
<Window
    x:Class="ExpanderTextBlockStyle.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:local="clr-namespace:ExpanderTextBlockStyle"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    Title="MainWindow"
    Width="500"
    Height="250"
    ThemeMode="Light"
    mc:Ignorable="d">
    <Grid>
        <Grid.ColumnDefinitions>
            <ColumnDefinition />
            <ColumnDefinition />
        </Grid.ColumnDefinitions>

        <Expander
            Width="200"
            Header="Expander"
            IsExpanded="True">
            <StackPanel Orientation="Vertical">
                <Label>First label</Label>
                <Label>Second label</Label>
                <Label>Third label</Label>
            </StackPanel>
        </Expander>

        <Border
            Grid.Column="1"
            Width="200"
            Height="100">
            <StackPanel Orientation="Vertical">
                <TextBlock Margin="0,0,0,8" Style="{DynamicResource BodyStrongTextBlockStyle}">
                    Labels not in an Expander
                </TextBlock>
                <Label>First label</Label>
                <Label>Second label</Label>
                <Label>Third label</Label>
            </StackPanel>
        </Border>
    </Grid>
</Window>
```

### Expected behavior

Consistent label styling regardless of where the `Label` is placed.

This is how it looks in the old style:

![Image](https://github.com/user-attachments/assets/5ae460ea-c3c4-4d33-b9ac-02cb6a8ac4bf)

### Actual behavior

`Label` has different styling depending on context (`Expander` vs other).

![Image](https://github.com/user-attachments/assets/df06ea47-be9b-42b3-a9cc-144cbc57aaef)

### Regression?

Since the Fluent theme is new, it can perhaps not be called a regression, strictly speaking, but compared to the old "style", it is less consistent.

### Impact

Makes it hard to make a consistent UX.

### Configuration

| Property | Value |
| ----------|-------|
| SDK | .NET 9 RC2 |
| OS Name | Microsoft Windows 11 Pro |
| Version | 10.0.22631 Build 22631 |
| System SKU | Surface_Pro_8_1983 |

**Comment by siagupta0202** [comment] 2024-12-09 08:44
I believe this issue is occurring in the .NET 9 RC2 version. It was occurring because the expander had been provided a font size of 14 and the labels inside the expander were inheriting this value due to it.
[wpf/src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Expander.xaml at release/9.0-rc2 · dotnet/wpf](https://github.com/dotnet/wpf/blob/release/9.0-rc2/src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Expander.xaml#L278)
This is now fixed in the latest .NET 9 version and should not be occurring anymore.

**Comment by siagupta0202** [comment] 2024-12-17 06:42
@bent-rasmussen since this issue is not reproducible anymore, I am going ahead and closing this issue. If it still occurs, you can reopen this issue with more details.

**Closed by siagupta0202** 2024-12-17 06:42 UTC
Labels: :mailbox_with_no_mail: waiting-author-feedback, Investigate, Win 11 Theming
