### ISSUE TITLE
Fluent Themes contain invalid DataGridColumn styles

### ISSUE THREAD

**Issue by MitchRazga** [dotnet/wpf#9755] opened 2024-09-10 13:48 UTC
### Description

Iterating through the resources of any Fluent theme will throw this exception
```ArgumentException: 'DataGridCheckBoxColumn' type must derive from FrameworkElement or FrameworkContentElement.```

Which leads back to these styles:
https://github.com/dotnet/wpf/blob/94751f56a45603960704642bdbc245a78e725644/src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DataGrid.xaml#L62
https://github.com/dotnet/wpf/blob/94751f56a45603960704642bdbc245a78e725644/src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DataGrid.xaml#L505-L507
https://github.com/dotnet/wpf/blob/94751f56a45603960704642bdbc245a78e725644/src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DataGrid.xaml#L792-L795

This is because [DataGridColumn](https://learn.microsoft.com/en-us/dotnet/api/system.windows.controls.datagridcolumn?view=windowsdesktop-9.0) and derived types inherit from DependencyObject not FrameworkElement or FrameworkContentElement and therefore cannot be styled.

### Reproduction Steps

[TestResources.zip](https://github.com/user-attachments/files/16945279/TestResources.zip)

### Expected behavior

Iterating through the framework's resources should not cause an exception.
DataGridColumn, DataGridTextColumn and DataGridCheckBoxColumn should not have any styles.

### Actual behavior

```ArgumentException: 'DataGridColumn' type must derive from FrameworkElement or FrameworkContentElement.```
```ArgumentException: 'DataGridTextColumn' type must derive from FrameworkElement or FrameworkContentElement.```
```ArgumentException: 'DataGridCheckBoxColumn' type must derive from FrameworkElement or FrameworkContentElement.```

### Impact

Impacts all Fluent themes.
https://github.com/dotnet/wpf/blob/94751f56a45603960704642bdbc245a78e725644/src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml#L1482
https://github.com/dotnet/wpf/blob/94751f56a45603960704642bdbc245a78e725644/src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml#L1510
https://github.com/dotnet/wpf/blob/94751f56a45603960704642bdbc245a78e725644/src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml#L1505

### Configuration

.NET 9 Preview 7
Microsoft Windows 11 Pro 10.0.22631
x64

### Other information

Looks this is also present in WPF UI too https://github.com/lepoco/wpfui/blob/4ac96867797267d566b82fbbfcab0c867353afaa/src/Wpf.Ui/Controls/DataGrid/DataGrid.xaml#L64

**Comment by miloush** [comment] 2024-09-10 14:38
I would suggest the issue is kept open until a PR merged.

**Closed as completed** 2024-10-10 12:56 UTC
Labels: Investigate, :construction: work in progress
