### ISSUE TITLE
Contrast issues in Fluent color scheme

### ISSUE THREAD

**Issue by christian-clausen** [dotnet/wpf#10140] opened 2024-12-04 08:31 UTC
### Description

It seems there is something fundamentally wrong with the color scheme. One example is `CardBackgroundFillColorDefault` versus `CardBackgroundFillColorSecondary`.

In both dark and light mode, when changing from `Default` to `Secondary`, the (background) color gets darker.

Consequently, when changing from `Default` to `Secondary`, the contrast between text and background *increases* in dark mode and *decreases* in light mode.

The consequence of this is that if we want a certain UI design to have higher contrast in both dark and light modes, we cannot use these built-in definitions, but need to define our own, theme-dependent color scheme.

### Reproduction Steps

1. Create a WPF app with Fluent enabled, and add this to the main window:
```xaml
<Border
    Background="{DynamicResource CardBackgroundFillColorDefaultBrush}"
    BorderBrush="Blue"
    BorderThickness="1"
    Height="60"
    Width="100">
    <StackPanel HorizontalAlignment="Center" VerticalAlignment="Center">
        <TextBlock Foreground="{DynamicResource TextFillColorSecondaryBrush}" Text="Hello World" />
    </StackPanel>
</Border>
```
2. Set Windows colors to *Dark*
3. Set border background to `CardBackgroundFillColorDefaultBrush` and run
4. Set border background to `CardBackgroundFillColorSecondaryBrush` and run
5. Set Windows colors to *Light*
6. Set border background to `CardBackgroundFillColorDefaultBrush` and run
7. Set border background to `CardBackgroundFillColorSecondaryBrush` and run

### Expected behavior

If `Secondary` is *darker* than `Default` in *dark mode*, then `Secondary` should *lighter* than `Default` in *light mode*.

### Actual behavior

`Secondary` is *darker* than `Default` in both *dark mode* and *light mode*.

Here follows screenshots of code and results. All examples use the same text brush, `TextFillColorSecondaryBrush` and varies border background from `Default` to `Secondary` in dark mode and then light mode.

Dark mode and border background `CardBackgroundFillColorDefaultBrush`:
![Image](https://github.com/user-attachments/assets/f53b86a9-09d2-4275-bc46-a7683a1a5e8b)

Dark mode and border background `CardBackgroundFillColorSecondaryBrush`:
![Image](https://github.com/user-attachments/assets/380aaaa9-72c9-4d0e-8c1e-6eb58a08c4eb)

Light mode and border background `CardBackgroundFillColorDefaultBrush`:
![Image](https://github.com/user-attachments/assets/7e63c209-0da8-4604-b293-9ff3f70a3368)

Light mode and border background `CardBackgroundFillColorSecondaryBrush`:
![Image](https://github.com/user-attachments/assets/ac1912cd-1616-47e5-a565-4c02c969599b)

### Regression?

Not really because this is the first version of the Windows 11 Theme, but I did compare to WinUI where the color definitions are different.

In WinUI there seems to be a single definition covering both light and dark modes with alpha taking care of consistency:
![Image](https://github.com/user-attachments/assets/7d50e19e-e5a5-4ab5-8f5d-b9008eeb70b0)

In WPF Fluent, light mode equals WinUI:
![Image](https://github.com/user-attachments/assets/194290e0-e75e-4022-bffa-7338ee963cad)

But the dark mode is different:
![Image](https://github.com/user-attachments/assets/6f1c30ec-bea2-47bf-957e-ea95e847584e)

 

### Known Workarounds

Define our own theme-dependent color scheme.

### Impact

This impacts everyone developing WPF apps with Windows 11 theming leading to lower developer productivity. When contrast issues are not discovered during development and quality assurance, this leads to WPF app solution accessibility issues for end users.

### Configuration

```
C:\tmp>dotnet --info
.NET SDK:
 Version:           9.0.100
 Commit:            59db016f11
 Workload version:  9.0.100-manifests.4a280210
 MSBuild version:   17.12.7+5b8665660

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100\
```

**Comment by siagupta0202** [comment] 2024-12-10 09:34
I believe WinUI also has different definitions for light and dark mode and not just a single definition. Moreover, the color values match both in WinUI and WPF

Dark mode for WinUI - [microsoft-ui-xaml/src/controls/dev/CommonStyles/Common_themeresources_any.xaml at main · microsoft/microsoft-ui-xaml](https://github.com/microsoft/microsoft-ui-xaml/blob/main/src/controls/dev/CommonStyles/Common_themeresources_any.xaml#L55)

Light mode for WinUI - [microsoft-ui-xaml/src/controls/dev/CommonStyles/Common_themeresources_any.xaml at main · microsoft/microsoft-ui-xaml](https://github.com/microsoft/microsoft-ui-xaml/blob/main/src/controls/dev/CommonStyles/Common_themeresources_any.xaml#L251)

**Comment by christian-clausen** [comment] 2024-12-10 10:19
Yes, you are right, I did not notice that the Common XAML file defined multiple resource dictionaries. So probably WinUI has a similar issue.

**Comment by siagupta0202** [comment] 2024-12-17 06:35
@christian-clausen  If you want the controls to have a higher contrast ratio, you can use `TextFillColorPrimaryBrush` and `CardBackgroundFillColorDefaultBrush` for your control. If there is a constraint that you cannot use `TextFillColorPrimaryBrush`, then you can take a look at the rest of the resources, probably another combination will be a better fit for your scenario. 

Since we are aligning our behavior to that of WinUI's which it seems to be doing as in both the Secondary seems to be darker than Default (in both light and dark mode), this is not a bug as such with the resources.

If there are any more queries, please feel free to put them here or else can we go ahead and consider this as closed?

**Comment by siagupta0202** [comment] 2024-12-31 05:51
@christian-clausen since we are not deviating from the intended fluent behavior, I am going ahead and closing this issue. If there are any more queries, you can reopen this issue with more details.

**Closed by siagupta0202** 2024-12-31 05:51 UTC
Labels: :mailbox_with_no_mail: waiting-author-feedback, Investigate, Win 11 Theming
