### ISSUE TITLE
Namable rows and columns in WPF grids

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#9411] opened 2024-07-16 06:48 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Namable-rows-and-columns-in-WPF-grids/10157580)._

---
How about giving us the ability to name WPF grid rows and columns in XAML rather than having to use and update numbers all the time. For example,

```  
  
    
      
    

    
    
  

  
  
```

That way if you, for example, insert a row, you wouldn’t have to go through and update all the row numbers of subsequent rows. It gets time consuming when there are a lot of rows with a lot of stuff in them. Not to mention the numbers aren’t readable at all.

Granted you would still have to update span properties with numbers, but maybe you could add name support for those too, like a RowSpan=“Name1…Name2” kind of thing.  That would be cool because you could specify things like RowSpan="Name1.." which would span from row Name1 to the last row, RowSpan="..Name2" which would span from the first row to row Name2, or RowSpan=".." which would span across all rows.

---
#### Feedback Bot on 9/27/2022, 08:35 AM: 

(private comment, text removed)

**Comment by miloush** [comment] 2024-07-16 11:24
Duplicate of #3614 #2844 #166

**Closed** 2024-07-16 11:48 UTC
