### ISSUE TITLE
update wpf dx9 to dx12

### ISSUE THREAD

**Issue by icetech233** [dotnet/wpf#9962] opened 2024-10-16 01:22 UTC
### Description

update dx9 to dx12

### Reproduction Steps

1

### Expected behavior

1

### Actual behavior

1

**Comment by himgoyalmicro** [comment] 2024-10-16 05:33
Closing this as a duplicate of [#7062](https://github.com/dotnet/wpf/issues/7062)

**Closed by himgoyalmicro** 2024-10-16 05:33 UTC
