### ISSUE TITLE
In .NET9 preview 6, 'Data on clipboard is invalid (0x800401D3 (CLIPBRD_E_BAD_DATA))' Exception thrown while retrieving data from the clipboard

### ISSUE THREAD

**Issue by RajaVigneshB** [dotnet/wpf#9495] opened 2024-07-31 11:58 UTC
### Description

We are copy a text to clipboard using the Clipboard.SetDataObject method. Then when we retrieve the data from the clipboard using the Clipboard.GetDataObject method, the data not valid exception is thrown in the .NET9 preview 6 version.

```
 //Clear the existing data in the clipboard
 Clipboard.Clear();
IDataObject dataObject = new DataObject();
 dataObject.SetData("TextInfo", "I have copied this");
 //Set the data in the clipboard
 Clipboard.SetDataObject(dataObject, true);

 //Retrieve the data from the clipboard
 IDataObject retrievedDataObject =Clipboard.GetDataObject();
 if (retrievedDataObject != null && retrievedDataObject.GetDataPresent("TextInfo"))
 {

    // Exception is thrown here.
     string clipboardData = (string)retrievedDataObject.GetData("TextInfo");
 }
```

### Reproduction Steps

Use the above provided code snippet in the description to reproduce the issue.

### Expected behavior

The data should be retrieved properly

### Actual behavior

Data not valid exception is thrown

### Impact

Copy and paste of a simple text is affected

### Configuration

.NET9 Preview 6

**Comment by lindexi** [comment] 2024-07-31 12:42
Duplicate of #9289

**Comment by lindexi** [comment] 2024-07-31 12:43
Thank you @RajaVigneshB . Could you see https://github.com/dotnet/wpf/issues/9289 ?

**Comment by rchauhan18** [comment] 2024-08-07 07:35
@RajaVigneshB This issue has been fixed in the latest version of .NET9 (preview 7 onwards)
As @lindexi mentioned, you can refer to issue: https://github.com/dotnet/wpf/issues/9289
Closing the issue.

**Closed by rchauhan18** 2024-08-07 07:35 UTC
