### ISSUE TITLE
CommandParameter doesn't trigger Command revalidation

### ISSUE THREAD

**Issue by trodent83** [dotnet/wpf#4472] opened 2021-05-04 05:36 UTC
.NET Core Version: 5.0.201
Windows version: Windows 10 Entrprise 190
Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
**Problem description: 
If the CommandParameter of a Button is changed the Command will not be automaticly revalidated and this can result in the strange behavior that even though the parameter is set the command doesn't see this until something else triggers the revalidation of the command.

This would have the beneficial effect that the revalidating of the commands could  be more event driven.

**Actual behavior: If only the command parameter is change nothing happens

**Expected behavior: The CanExecute of the corresponding command should be automaticly triggered.

**Comment by miloush** [comment] 2021-05-04 11:02
Duplicate of #316, #3452. Another duplicate: #4078. PR: #4217.

**Comment by trodent83** [comment] 2021-05-06 04:40
@miloush 
I would say it is more associated with it as those refresh to the original initialization of the control, and this for the binded value's change, but they can be solved with the same mechanism.

**Comment by ryalanms** [comment] 2021-05-06 19:21
@trodent83:  Please close if you agree this is a duplicate.  Thanks.

**Closed** 2021-05-07 04:16 UTC
Labels: .NET Framework

**Comment by miloush** [comment] 2021-05-08 23:33
@trodent83 Whether the value is changed as a result of binding or by setting up the control does not make a difference - in both cases, the property changed handler would be triggered.
