### ISSUE TITLE
Window CustomControl is not stylized at design time.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#4546] opened 2021-05-20 18:36 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Window-CustomControl-is-not-stylized-at-/1427931)._

---
* .NET Core Version: 4.8
* Windows version: win10
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
 
**Problem description:**

### CustomWindow and CustomUserControl

```csharp
public class CustomWindow : Window
{
    static CustomWindow
    {
        DefaultStyleKeyProperty.OverrideMetadata(
            typeof(CustomWindow), 
            new FrameworkPropertyMetadata(typeof(CustomWindow)));
    }
}

public class CustomUserControl : UserControl
{
    static CustomUserControl 
    {
        DefaultStyleKeyProperty.OverrideMetadata(
            typeof(CustomUserControl), 
            new FrameworkPropertyMetadata(typeof(CustomUserControl)));
    }
}
````

### Generic.xaml

```xaml
<Style TargetType="{x:Type local:CustomWindow}">
    <Setter Property="Background" Value="Blue"/>
    <Setter Property="Template">
        <Setter.Value>
            <ControlTemplate TargetType="{x:Type local:CustomWindow}">
                <Border Background="{TemplateBinding Background}"
                        BorderBrush="{TemplateBinding BorderBrush}"
                        BorderThickness="{TemplateBinding BorderThickness}" Padding="10">
                    <ContentPresenter/>
                </Border>
            </ControlTemplate>
        </Setter.Value>
    </Setter>
</Style>

<Style TargetType="{x:Type local:CustomUserControl}">
    <Setter Property="Background" Value="Green"/>
    <Setter Property="Template">
        <Setter.Value>
            <ControlTemplate TargetType="{x:Type local:CustomUserControl}">
                <Border Background="{TemplateBinding Background}"
                        BorderBrush="{TemplateBinding BorderBrush}"
                        BorderThickness="{TemplateBinding BorderThickness}">
                    <ContentPresenter/>
                </Border>
            </ControlTemplate>
        </Setter.Value>
    </Setter>
</Style>
```

### MyWindow and MyUserControl

```csharp
public partial class MyWindow : CustomWindow
{
    // DesignTime not stylized.
}

public partial class MyUserControl : CustomUserControl
{
    // DesignTime stylized.
}
```

```xaml
<!-- MyWindow.xaml -->
<custom:MyWindow ...>
    <Grid>
    </Grid>
</custom:MyWindow>

<!-- MyUserControl.xaml -->
<custom:MyUserControl ...>
    <Grid>
    </Grid>
</custom:MyUserControl>
````

### MyWindow(CustomWindow) DesignTime not stylized.

! [image] (https://user-images.githubusercontent.com/52397976/118633451-7828f300-b80c-11eb-81c8-a4e0ed1bc328.png)

### MyUserControl(CustomUserControl) DesignTime stylized.

! [image] (https://user-images.githubusercontent.com/52397976/118633561-942c9480-b80c-11eb-9447-9b480fee4733.png)

_The style is well applied when it is Runtime._

---
#### Feedback Bot on 5/19/2021, 11:59 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by devncore-james** [comment] 2021-05-21 07:35
This is me :smile:

**Comment by lindexi** [comment] 2021-05-22 00:41
Duplicate of #4524

**Comment by devncore-james** [comment] 2021-05-22 01:20
Thank you for send message to me. :)

2021년 5월 22일 (토) 오전 9:41, lindexi ***@***.***>님이 작성:

**Closed** 2022-06-29 10:50 UTC
Labels: External Non-WPF Issue
