### ISSUE TITLE
PresentationCore pdb is missing

### ISSUE THREAD

**Issue by onovotny** [dotnet/wpf#1262] opened 2019-07-14 14:03 UTC
Trying with the latest nightly of .NET Core SDK 3 preview 7, in the debugger, PresentationCore.pdb isn't found. The rest of the WPF pdbs are found and I can source-step into the code, just that one appears missing.

**Comment by rladuca** [comment] 2019-07-15 23:25
@onovotny I just installed the latest Preview 7 drop and I was able to get the PDB for `PresentationCore` to load.

The version I was using was `3.0.100-preview7-012814` and I was able to load PDBs for both x86 and x64.  This was only having MS + NuGet symbol servers enabled (I made sure to turn off all internal symbol servers and clear the cache).

Are you sure your symbol servers are enabled?

**Comment by vatsan-madhavan** [comment] 2019-07-16 00:43
Seems to work ok for me - this is my experience. 

![UAyMmxMpB8](https://user-images.githubusercontent.com/20246435/61257912-f0619180-a727-11e9-9437-6150ed16b988.gif)

**Comment by rladuca** [comment] 2019-07-24 00:23
All this moving around has the bot confused.

In any case, I'm going to close this issue out since we can't reproduce this at the current time.

@onovotny If you see this crop up again, feel free to open another issue.

**Closed by rladuca** 2019-07-24 00:23 UTC
Labels: area-infrastructure, issue-type-question, needs-author-feedback
