### ISSUE TITLE
Visual Studio 2019 Crashing, as soon as RDP Connects

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#1360] opened 2019-07-24 03:27 UTC
Not sure if it only crashes when window is active or not. Also not sure if having Windows Taskbar to the right makes a difference. Using RDP full screen.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/649452/visual-studio-2019-crashing-as-soon-as-rdp-connect.html
VSTS ticketId: 948312_
_These are the original issue comments:_

Visual Studio Feedback System on 7/18/2019, 05:47 PM (5 days ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
Visual Studio Feedback System on 7/19/2019, 08:56 AM (5 days ago): <markdown><p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>
</markdown>
Visual Studio Feedback System on 7/19/2019, 08:56 AM (5 days ago): <p>This feedback is being re-triaged as we are moving it to another team that can better help with the issue. Thanks for your patience.</p><p>  </p><p><strong></strong><u></u><sub></sub><sup></sup></p>

_These are the original issue solutions:_
(no solutions)

**Comment by weltkante** [comment] 2019-07-24 06:06
I assume there's a private stacktrace attached to the vsfeedback which points to WPF being responsible for the VS crash? Otherwise it makes no sense that this ends up in the WPF repo ...

**Comment by rladuca** [comment] 2019-07-24 17:30
Internally this was called out as related to #1198 .

@vatsan-madhavan I wasn't able to find the associated stacks and dumps on the internal tickets, so I don't feel comfortable duping this immediately.  We can talk in triage.

**Comment by vatsan-madhavan** [comment] 2019-07-26 04:40
In the internal ticket history, I can see that @jekelly made the association between this and #1198.

**Comment by SamBent** [comment] 2020-06-11 23:56
The private information was removed from the vsfeedback ticket by the time the issue arrived here;  no one knows why or how.  Without that, there's nothing we can do - I'm closing the issue.

If it really is a dupe of #1198, a fix was shipped in servicing updates to .NET 4.8 last September.

**Closed by SamBent** 2020-06-11 23:56 UTC
Labels: area-netfx, issue-type-bug
