### ISSUE TITLE
Wpf's Button's Thickness property is invalid

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#3771] opened 2020-11-06 03:24 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Wpfs-Buttons-Thickness-property-is-inv/958226)._

---
New construction of win7 flagship system,
Button's ThicknessBorder was found to be invalid, always displaying a 1-pixel border.
Putting the project into Win10 can be displayed normally.

---
#### Feedback Bot on 3/23/2020, 07:33 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 5/8/2020, 03:19 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.

---
### Original Solutions
(no solutions)

**Comment by SamBent** [comment] 2020-11-14 02:30
This is a duplicate of questions asked 10 years ago at
- https://social.msdn.microsoft.com/Forums/en-US/f486e9bc-9dc6-43e8-a402-dc45a6bc7458/button-border-thickness
- https://social.msdn.microsoft.com/Forums/vstudio/en-US/cb4c5f93-dbbf-4bd0-ade2-866220362886/wpf-button-border-thickness

To summarize the answers:  WPF's "Aero" theme uses ButtonChrome to render the button's border.  This matches the look of native buttons using the OS Aero theme for Win7, but it doesn't support changing the BorderThickness.  You can override this by providing your own style for Button.

On Win8 and above, WPF uses its "Aero2" theme (to match the OS Aero theme for Win8), which doesn't use ButtonChrome and  does support changing the BorderThickness.

Note that Win7 is out of support, so WPF is not changing its "Aero" theme (which we couldn't do anyway, for compat reasons).

**Closed by SamBent** 2020-11-14 02:30 UTC
