### ISSUE TITLE
. NET6 WPF: ToolTip doesn't work on ComboBoxItem

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#6043] opened 2022-01-31 19:01 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET6-WPF:-ToolTip-doesnt-work-on-Combo/1648606)._

---
[severity:It bothers me. A fix would be nice]

In WPF of .NET 6, the tooltip of the ComboBoxItem doesn't work if the ComboBox is inside of a UserControl.

Actual behavior: the tooltip shows up for about 500ms and then it disappears.
Expected behavior: the tooltip gets displayed for a reasonable amount of time. 

Note: _Setting explicitly the 'ToolTipService.ShowDuration' doesn't help._

Environment: Visual Studio Professional 2022 64-bit 17.0.5, .NET 6.0.1, Windows 10 Pro Version:21H1

I enclosed a project file that shows the issue:
[TooTipTest.zip] (https://aka.ms/dc/file?name=B054640530ce04d1181db74af20165109637788677425623620_TooTipTest.zip&tid=054640530ce04d1181db74af20165109637788677425623620)

I also inline the XAML for clarity.

The UserControl that contains the ComboBox:

```
<UserControl x:Class="TooTipTest.SomeUserControl"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:local="clr-namespace:TooTipTest"
             mc:Ignorable="d" 
             d:DesignHeight="50" d:DesignWidth="400">
    <Grid>
        <ComboBox>
            <ComboBoxItem Content="AAAA" ToolTip="aaaaaaa"/>
            <ComboBoxItem Content="BBBB" ToolTip="bbbbbbb"  ToolTipService.ShowDuration="30000"/>
            <ComboBoxItem Content="CCCC" ToolTip="ccccccc"/>
        </ComboBox>
    </Grid>
</UserControl>
```

The Windows that hosts the UserControl:

```
<!-- Window Container-->
<Window x:Class="TooTipTest.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:TooTipTest"
        mc:Ignorable="d"
        Title="MainWindow" Height="350" Width="600">
    <Grid>
        
<TextBlock Text="The TooTip on ComboBoxItem doesn't work; it shows up for only 500 ms." 
                   HorizontalAlignment="Center" 
                   VerticalAlignment="Center" 
                   Margin="0,0,0,50"/>
        
<!-- The UserControl that contains the ComboBox -->
        <local:SomeUserControl VerticalAlignment="Center" HorizontalAlignment="Center" MinWidth="200"/>
    </Grid>
</Window>
```

---
#### Feedback Bot on 1/27/2022, 00:45 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by 6outtaTen** [comment] 2022-02-01 21:55
Looks like it's a problem with .net 6.0.
Changing `<TargetFramework>net6.0-windows</TargetFramework>` to `<TargetFramework>net5.0-windows</TargetFramework>` seems to fix the issue. 
If I were you, I'd just use .net5.0 instead and if you must use 6.0 I'd wait for a fix, as it is clearly an issue with the version.

**Comment by gurpreet-wpf** [comment] 2022-02-07 05:10
This is duplicate of #5716 and hence closing this. The fix has been worked on with the original issue.

**Closed by gurpreet-wpf** 2022-02-07 05:10 UTC
