### ISSUE TITLE
Failed to run Winforms/WPF .Net 6.0 app in Visual Studio by pressing F5 

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/wpf#4620] opened 2021-06-01 08:37 UTC
* .Net Version: **.Net SDK 6.0.100-preview.6.21280.2** from main branch in https://github.com/dotnet/installer
* More Info: 
1. This is a recent .Net SDK build's regression, cannot repro in previous build: .Net SDK 6.0.100-preview.6.21276.13
2. Cannot repro when building app in CLI

* Repro steps:
1.	Launch VS to create a Winforms/WPF .Net 6.0 app
2.	Press F5 to run it
 
* Actual result: 
Failed to run app
![F5Issue](https://user-images.githubusercontent.com/26474449/120292930-54c77300-c2f7-11eb-8d91-dc50bf1524e0.gif)
 
* Expected result:
Run app successfully

**Comment by Olina-Zhang** [comment] 2021-06-03 02:28
A similar issue: https://github.com/dotnet/runtime/issues/53508

**Comment by RussKie** [comment] 2021-06-03 22:49
Duplicate of dotnet/runtime#53508

**Comment by RussKie** [comment] 2021-06-03 22:50
This is the issue I raised to the runtime time. I expect the fix to flow through shortly.

**Closed by RussKie** 2021-06-03 22:49 UTC
Labels: External Non-WPF Issue

**Comment by RussKie** [comment] 2021-06-03 22:58
I've just tested Window Forms, and everything seems back to normal with https://github.com/dotnet/winforms/pull/5038 (runtime v20210603.1).

**Comment by Ashley-Li** [comment] 2021-06-07 03:14
Verified the issue with latest .NET SDK 6.0.100-preview.6.21306.1, the issue has been fixed, after created a Winforms/WPF .Net 6.0 app and then press F5 to run it, run app successfully. Please see below gif:
![issue_53508_verify](https://user-images.githubusercontent.com/56664234/120954360-920d8400-c781-11eb-9f56-17cf27f5a9d0.gif)
