### ISSUE TITLE
Wpf app is released as a single file and cannot be run.

### ISSUE THREAD

**Issue by lifuhua123** [dotnet/wpf#3650] opened 2020-09-22 03:50 UTC
# Issue Title

Wpf app is released as a single file and cannot be run.

# General
I tried winform and wpf independent deployment scheme under .net 5 RC.1, winform can run successfully, but wpf cannot start.

**Comment by lindexi** [comment] 2020-10-15 00:47
Duplicate of #3634 ？

**Comment by ryalanms** [comment] 2020-10-15 01:11
Yes, @lindexi, it looks like a duplicate to me as well.  

From my understanding, SingleFile wasn't supported until RC2, but there is another blocking bug noted in #3634.

**Closed** 2020-10-20 06:30 UTC
Labels: issue-type-bug
