### ISSUE TITLE
Custom Dictionary Not Being Applied Correctly in WPF TextBox - Red Underline Persisting on Dictionary Words

### ISSUE THREAD

**Issue by Sekar47** [dotnet/wpf#9808] opened 2024-09-18 13:05 UTC
### Description

I am experiencing a problem with applying a custom dictionary to a TextBox in a WPF application. Despite correctly setting the SpellCheck.CustomDictionaries property to include my .lex file, the TextBox continues to underline words from the custom dictionary with red squiggly lines, indicating them as errors.

### Reproduction Steps

[CustomDict.zip](https://github.com/user-attachments/files/17044337/CustomDict.zip)
1. In the attached sample, note that in a MainWindow.xaml , we've added a text in textbox which is already present in the custDictionary.
2. Run the sample and note that the word is still underlined by the red squiggly line.

[Note] : Ensure the _uri of the custDictionary.

### Expected behavior

Words present in the custom dictionary should not be underlined with red squiggly lines in the TextBox.

### Actual behavior

Words in the custom dictionary are still highlighted as errors.

Any insights or suggestions to resolve this issue would be greatly appreciated.

### Configuration

OS: Windows 11
.NET Framework version: .NET Framework 4.8
Visual Studio: VS2022

**Comment by Sekar47** [comment] 2024-09-19 03:59
Hi @miloush ,

Thank you for pointing out the connection to issue #9760 ?  It seems like both myself and other users are encountering the same problem with no solution or workaround available yet.

**Comment by harshit7962** [comment] 2024-09-23 05:16
Closing this ticket as it is a duplicate of #9760. Will keep things updated there.

**Closed by harshit7962** 2024-09-23 05:16 UTC
