### ISSUE TITLE
WPF Textbox SpellCheck FileLoadException .NET Framework 4.5.2

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5759] opened 2021-11-29 23:35 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/WPF-Textbox-SpellCheck-FileLoadException/1159420)._

---
<p>Hi,</p><p>i have a WPF application with a textbox on a view like this:</p><pre>&lt;TextBox  HorizontalAlignment=&quot;Stretch&quot; Text=&quot;{Binding Comments}&quot;  BorderThickness=&quot;0&quot; 
TextWrapping=&quot;Wrap&quot; SpellCheck.IsEnabled=&quot;True&quot; xml:lang=&quot;en-US&quot;                          VerticalAlignment=&quot;Stretch&quot; AcceptsReturn=&quot;True&quot; VerticalScrollBarVisibility=&quot;Auto&quot; /&gt;</pre><p>We have been installed the Language pack, but sometimes we get an exception like this:</p><pre>Application:Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.IO.FileLoadException at MS. Internal.ReaderWriterLockSlimWrapper.ExecuteWithinLockInternal(System.Action, System.Action, System.Object ByRef, System.Delegate, System.Object[]) at MS. Internal.ReaderWriterLockSlimWrapper.WithWriteLock[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Func`3&lt;Boolean,Boolean,Boolean&gt;, Boolean, Boolean, Boolean ByRef) at System.Windows.Documents.MsSpellCheckLib.SpellCheckerFactory.Create(Boolean) at System.Windows.Documents.WinRTSpellerInterop.. ctor() at System.Windows.Documents.SpellerInteropBase.CreateInstance() at System.Windows.Documents.Speller.EnsureInitialized() at System.Windows.Documents.Speller.SetCustomDictionaries(System.Windows.Controls.CustomDictionarySources, Boolean) at System.Windows.Documents.TextEditor.SetCustomDictionaries(Boolean) at System.Windows.Controls.SpellCheck.OnIsEnabledChanged(System.Windows.DependencyObject, System.Windows.DependencyPropertyChangedEventArgs) at System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs) at System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs) at System.Windows.Controls.TextBox.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs) at System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs) at System.Windows.DependencyObject.UpdateEffectiveValue(System.Windows.EntryIndex, System.Windows.DependencyProperty, System.Windows.PropertyMetadata, System.Windows.EffectiveValueEntry, System.Windows.EffectiveValueEntry ByRef, Boolean, Boolean, System.Windows.OperationType) at System.Windows.DependencyObject.SetValueCommon(System.Windows.DependencyProperty, System.Object, System.Windows.PropertyMetadata, Boolean, Boolean, System.Windows.OperationType, Boolean) at System.Windows.Baml2006.WpfMemberInvoker.SetValue(System.Object, System.Object) at MS. Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(System.Object, System.Xaml.XamlMember, System.Object) Exception Info: System.Windows.Markup.XamlParseException at System.Windows.Markup.XamlReader.RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri) at System.Windows.FrameworkTemplate.LoadTemplateXaml(System.Xaml.XamlReader, System.Xaml.XamlObjectWriter) at System.Windows.FrameworkTemplate.LoadTemplateXaml(System.Xaml.XamlObjectWriter) at System.Windows.FrameworkTemplate.LoadOptimizedTemplateContent(System.Windows.DependencyObject, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector, System.Collections.Generic.List`1&lt;System.Windows.DependencyObject&gt;, System.Windows.UncommonField`1&lt;System.Collections.Hashtable&gt;) at System.Windows.FrameworkTemplate.LoadContent(System.Windows.DependencyObject, System.Collections.Generic.List`1&lt;System.Windows.DependencyObject&gt;) at System.Windows.StyleHelper.ApplyTemplateContent(System.Windows.UncommonField`1&lt;System.Collections.Specialized.HybridDictionary[]&gt;, System.Windows.DependencyObject, System.Windows.FrameworkElementFactory, Int32, System.Collections.Specialized.HybridDictionary, System.Windows.FrameworkTemplate) at System.Windows.FrameworkTemplate.ApplyTemplateContent(System.Windows.UncommonField`1&lt;System.Collections.Specialized.HybridDictionary[]&gt;, System.Windows.FrameworkElement) at System.Windows.FrameworkElement.ApplyTemplate() at System.Windows.FrameworkElement.MeasureCore(System.Windows.Size) at System.Windows.UIElement.Measure(System.Windows.Size) at System.Windows.ContextLayoutManager.UpdateLayout() at System.Windows.ContextLayoutManager.UpdateLayoutCallback(System.Object) at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks() at System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object) at System.Windows.Media.MediaContext.RenderMessageHandler(System.Object) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate) at System.Windows.Threading.DispatcherOperation.InvokeImpl() at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at MS. Internal.CulturePreservingExecutionContext.Run(MS. Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object) at System.Windows.Threading.DispatcherOperation.Invoke() at System.Windows.Threading.Dispatcher.ProcessQueue() at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef) at MS. Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef) at MS. Win32.HwndSubclass.DispatcherCallbackOperation(System.Object) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate) at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32) at MS. Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr) at MS. Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef) at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame) at System.Windows.Application.RunDispatcher(System.Object) at System.Windows.Application.RunInternal(System.Windows.Window) at Sennin.App.Main()</pre><p><br></p><p>Has this issue been solved with later .Net Framework versions?</p> <p>Thanks,</p><p>Francesco</p>

---
#### Feedback Bot on 8/23/2020, 11:11 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/20/2020, 01:42 AM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

#### Bruce Kingsley on 12/9/2020, 00:57 PM: 

<p>We too are having this problem which can't be "catched" in an exception block, so our application simply crashes. There doesn't seem to be any pattern when or what computer is more likely to result in this failure. In many places, we've been forced to disable spell checking which has become a disappointment to our software users.</p><p>If this not the forum to get the Microsoft .NET Framework/Core development team attention to this issue, please provide the appropriate link.<br></p>

---
### Original Solutions
(no solutions)

**Comment by singhashish-wpf** [comment] 2022-06-28 11:58
We are unable to reproduce this on net48. Hence closing this.

**Closed by singhashish-wpf** 2022-06-28 11:58 UTC
