### ISSUE TITLE
Would be nice if the controls color theme would take over the theme from the windows settings

### ISSUE THREAD

**Issue by scalablecory** [dotnet/wpf#2082] opened 2019-10-22 16:14 UTC
_From @PeterPann23 on Tuesday, October 22, 2019 7:01:37 AM_

# Windows Settings for theme is not applied to controls on winforms elements

# General
One can go over the Windows.UI.ViewManagement.UISettings and apply the themes as development time however as we are starting a new implementation one could already take the theme from windows and apply this on the form, or have a property on the form class that states UseTheme so if the user has "Dark-Mode" then the form draws "Dark-Mode" for as much as that's possible in a non WPF app. 

_Copied from original issue: dotnet/core#3676_

**Comment by weltkante** [comment] 2019-10-22 16:24
@scalablecory you keep moving WinForms issues to WPF :-(

That said, its probably not actionable, WinForms is just wrapping win32 controls and has no influence on the theming implementation.

**Comment by PeterPann23** [comment] 2019-10-23 06:37
Hi,
You should stop closing this issue, place it at winforms desk if this is theirs to implement. WinForms can read Windows.UI.ViewManagement.UISettings just as well as any other .net framwork. instead of aplying a "hard coded" color they can just pick-up the users profile's color schema

**Comment by weltkante** [comment] 2019-10-23 06:46
@PeterPann23 they can read settings, but they are not applying colors. WinForms is wrapping the OS win32 controls which come with a builtin theme, this is not programmed within WinForms.

**Comment by scalablecory** [comment] 2019-10-23 07:20
woops, sorry about that!

**Comment by weltkante** [comment] 2019-10-23 07:21
OP has reopened the issue himself, this can be resolved as duplicate of dotnet/winforms#2160 now?

**Comment by PeterPann23** [comment] 2019-10-23 19:03
@weltkante Yes the can read but they do not apply the colors, I have opened the issue in winfroms git, lets see if they can consider it. thanks for the feedback, appreciate it

**Closed** 2019-10-24 18:37 UTC
