### ISSUE TITLE
PresentationTraceSources.TraceLevel not found

### ISSUE THREAD

**Issue by stefanolson** [dotnet/wpf#113] opened 2018-12-07 00:39 UTC
* .NET Core Version: 3.0 Preview1
* Windows version: 10, 1803
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No (well not on 4.5 for sure)

 **Problem description:**
attempting to use PresentationTraceSources.TraceLevel causes failure to compile with  the error:
error MC3045: Unknown property 'PresentationTraceSources.TraceLevel' for type 'System.Windows.Data.Binding' encountered while parsing a Markup Extension. 

Works fine in WPF on the .net framework.

 **Expected behavior:**
Should compile and run and trace bindings
 
 **Minimal repro:**
` <TextBox Grid.Row="0" Text="{Binding PresentationTraceSources.TraceLevel=High}" Grid.Column="1"/>`

Stefan

**Comment by rladuca** [comment] 2018-12-07 01:02
@stefanolson Thanks for reporting this, I don't believe we've tested the trace sources at this point.

@ryalanms This looks like a PBT issue, can you take a look when you get a chance?

**Comment by rladuca** [comment] 2018-12-07 06:03
@ryalanms I looked a little further into this, and I think it's not PBT, but rather missing xmlns definitions in the WindowsBase ref assembly.  I'll assign this over to myself and see about fixing it tomorrow.

@stefanolson The problem is likely in code we haven't open sourced just yet.  Once fixed, it should appear in the daily builds, I'll let you know so you can verify.

**Comment by rladuca** [comment] 2018-12-07 16:32
@stefanolson I've filed an overarching issue to track work to sweep all the xmlns issues.  Please track the progress there.

Duplicate of #119

**Comment by rladuca** [comment] 2018-12-07 16:32
Duplicate of #119

**Closed by rladuca** 2018-12-07 16:32 UTC
Labels: bug
