### ISSUE TITLE
2D test failing due to change in GetHashCode in Core 3

### ISSUE THREAD

**Issue by grubioe** [dotnet/wpf#848] opened 2019-06-04 16:15 UTC
Copied from VSO ID: 803447

Test:

```
Name="Color API Test" Priority="1" Area="2D" SubArea="API Tests"
```

Fails due to a change in GetHashCode from corefx. What the test code is doing is generating 2 different colors and verifying that the resulting hash codes are not equal, the hashcode is calculated from System.Windows.Media.Color by overriding GetHashCode:

https://github.com/dotnet/wpf/blob/9c5dd1acfe9037f92f6c91b05ab2f7e18edf55b7/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Color.cs#L214-L220

which essentially only returns the hashcode from its internal struct which is defined as:

https://github.com/dotnet/wpf/blob/9c5dd1acfe9037f92f6c91b05ab2f7e18edf55b7/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Color.cs#L1158-L1161

in Framework different values for a,r,g,b would result in a different HashCode in Core it seems only the first value is considered for HashCode calculation, our test has the same first value so the hash code is the same.

As per corefx recommendation (https://github.com/dotnet/corefx/issues/35613) we should override and implement a correct HashCode mechanism for our 4 floats in MILColorF, ideally mirroring what Framework used to do

**Comment by weltkante** [comment] 2019-06-05 13:25
Was it verified in your original ticket source that this isn't actually a bug in .NET Core? Otherweise I think it'd be worth opening an issue with coreclr to verify that this behavior is intended.

I don't mind proper GetHashCode implementations in WPF but if thats an unintended bug the poor hashcode quality will likely impact users who port their applications as well.

**Comment by weltkante** [comment] 2019-06-06 07:43
@grubioe actually I cannot reproduce this, I took above definition of `MILColor` and created instances which differ only in a single component. Regardless which component differs, the hash code always differs too for me.

```C#
Debug.WriteLine($"Hash = {new MILColor { a = 0xFF, r = 0xAA, g = 0xBB, b = 0xCC }.GetHashCode()}");
Debug.WriteLine($"Hash = {new MILColor { a = 0x00, r = 0xAA, g = 0xBB, b = 0xCC }.GetHashCode()}");
Debug.WriteLine($"Hash = {new MILColor { a = 0xFF, r = 0x00, g = 0xBB, b = 0xCC }.GetHashCode()}");
Debug.WriteLine($"Hash = {new MILColor { a = 0xFF, r = 0xAA, g = 0x00, b = 0xCC }.GetHashCode()}");
Debug.WriteLine($"Hash = {new MILColor { a = 0xFF, r = 0xAA, g = 0xBB, b = 0x00 }.GetHashCode()}");

// output
//Hash = -669667421
//Hash = -669667492
//Hash = -669710941
//Hash = -659640413
//Hash = 336965539
```

**Comment by grubioe** [comment] 2019-06-06 15:55
Thanks for checking @weltkante 

@miguep - is this still valid?  It was logged back in February and seems that it no longer repros.

**Comment by miguep** [comment] 2019-06-11 19:36
the issue can still be reproduced like this:

``` csharp

            System.Windows.Media.Color ColorA = System.Windows.Media.Color.FromScRgb(1.0f, 0.3f, 0.4f, 1.0f);
            System.Windows.Media.Color ColorB = System.Windows.Media.Color.FromScRgb(0.99999f, 0.3f, 0.4f, 1.0f);
            System.Windows.Media.Color ColorC = System.Windows.Media.Color.FromScRgb(1f, 0.2999f, 0.4f, 1.0f);


            int hashA = ColorA.GetHashCode();
            int hashB = ColorB.GetHashCode();
            int hashC = ColorC.GetHashCode();
```

In .NET Framework all three hashcodes are different, but in .NET Core, A and C are the same.

an issue against corefx was opened https://github.com/dotnet/corefx/issues/35613, and closed as a by-design behavior, with the recommendation that we implement GetHashCode to our requirements, we'll use this issue to track that work, since we would like Color.GetHashCode to behave as it did in .NET Framework

**Comment by weltkante** [comment] 2019-06-11 19:47
I see, `GetHashCode` actually doesn't use `MILColor` from the original issue description, but `MILColorF`, so thats the reason why I couldn't reproduce it, as it only happens with float/double members. Thanks for verifying that its intentional.

**Comment by miguep** [comment] 2019-06-11 21:28
@weltkante good observation, the description was actually misleading, I've updated it for clarity, thank you

**Closed** 2019-07-23 01:26 UTC
Labels: rank20, regression
