### ISSUE TITLE
WPF app cannot be built in VS2019RC+Net Core 3 Preview 4

### ISSUE THREAD

**Issue by pavelovcharov** [dotnet/wpf#408] opened 2019-03-06 08:27 UTC
* .NET Core Version:  3.0.100-preview4-010591
* Windows version: 1809 (17763.316)

* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

 **Problem description:**
If an application contains XAML-files a build error occurs:
`1>C:\Program Files\dotnet\sdk\3.0.100-preview4-010591\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets\Microsoft.WinFX.targets(243,9): error MC1000: Unknown build error, 'Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.'`

 **Actual behavior:**
Build error occurs
 
 **Expected behavior:**
 No build errors

 **Minimal repro:**
1) Create a new WPF application
 2) Try to build it

**Comment by stevenbrix** [comment] 2019-03-06 17:19
Thanks for filing this issue. I'm able to reproduce this inside VS as well, but noticed that building from the cli via `dotnet build` works fine. Are you able to use that in the meantime while we figure this out?

**Comment by pavelovcharov** [comment] 2019-03-07 09:56
Yes, I'm using command line for now, it is not as comfortable as Visual Studio though

**Comment by KexyBiscuit** [comment] 2019-03-07 10:47
This has been annoying. Since Microsoft/msbuild#3986, I can't build my project from CLI.

**Comment by nguerrera** [comment] 2019-03-07 21:40
I have a fix for this in PR.

**Comment by stevenbrix** [comment] 2019-03-07 22:09
This is awesome, thanks @nguerrera!

**Comment by ryalanms** [comment] 2019-03-07 22:18
Thanks, Nick.

**Comment by nguerrera** [comment] 2019-03-08 01:38
This is now fixed as of .NET Core SDK 3.0.100-preview4-010654

**Closed by nguerrera** 2019-03-08 01:38 UTC
Labels: bug
