### ISSUE TITLE
[dotnet-sdk-9.0.100-preview.7.24375.12] Fail to load the interface controls for youtubedlwpf.

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/wpf#9486] opened 2024-07-30 09:18 UTC
### Description

When run the 3rd party application youtubedlwpf with the latest .NET 9 build, it failed to load interface controls without any errors.  After we tried to debug following the steps , it doesn't show the error either. It seems related to the fix for resource.
 Could you please help look into it? Please refer to repro information from [Internal bug](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2174443)  

### Reproduction Steps

**Debug Repro steps:**

Please get the repro information from [Internal bug](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2174443)
1.Open "C:\ReproAppSource\youtube-dl-wpf\youtube-dl-wpf.sln" with Visual Studio.
2. Build project YoutubeDl.Wpf.
3. Update ...\bin\Debug\net7.0-windows10.0.22621.0\youtube-dl-wpf.runtimeconfig.json to run against with dotnet-sdk-9.0.100-preview.7.24375.12:
```
"frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "9.0.0-preview.7.24374.12"
      },
      {
        "name": "Microsoft.WindowsDesktop.App",
        "version": "9.0.0-preview.7.24375.4"
      }
```
5. Run the app.
6. Click "Setting" icon.
7. Click "Dark" in Color theme.
8. Close the app and restart it.

Expected Result:

### Expected behavior

App launch successfully.
![image](https://github.com/user-attachments/assets/a179d080-24fc-4d8a-9d73-c35dee95302d)

### Actual behavior

App interface loading failed without any errors.

![image](https://github.com/user-attachments/assets/e7d87637-b39c-4be8-a83a-592f338f8765)

### Regression?

Yes
Verify Scenarios:
1). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.300: Pass
2). Windows 10 21H2 AMD64 + dotnet-sdk-9.0.100-preview.7.24371.4: Pass
3). Windows 10 21H2 AMD64 + dotnet-sdk-9.0.100-preview.7.24375.12: Fail

### Configuration

**Application Name:** youtubedlwpf
**OS**： Windows 10 21H2
**CPU:** X64
**.NET Build Number:** dotnet-sdk-9.0.100-preview.7.24375.12
**App or App Source checking at:** https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2174443
**Github Link:**  https://github.com/database64128/youtube-dl-wpf

**Dotnet Info:**

```
.NET SDK:
 Version:           9.0.100-preview.7.24375.12
 Commit:            9a99a3bf32
 Workload version:  9.0.100-manifests.57c130fb
 MSBuild version:   17.12.0-preview-24374-02+48e81c6f1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-preview.7.24375.12\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.

Host:
  Version:      9.0.0-preview.7.24374.12
  Architecture: x64
  Commit:       static

.NET SDKs installed:
  9.0.100-preview.7.24375.12 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-preview.7.24373.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-preview.7.24374.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.7.24375.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Other information

**Findings:**
If we build this app with dotnet-sdk-9.0.100-preview.7.24375.12 and launch the app, it will show error: 
```System.Windows.Markup.XamlParseException: 'Index was outside the bounds of the array.'.``` We are not sure if this error is related to the loading of interface styles.

StackTrace:
```
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
```

@dotnet-actwx-bot @dotnet/compat

**Comment by harshit7962** [comment] 2024-08-05 07:32
@Junjun-zhao, we are reviewing a fix for this incorrect rendering. To add details, this is due to an early exit from evaluating resources [here](https://github.com/dotnet/wpf/blob/main/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Application.cs#L1741).

This is a regression caused while introducing Fluent theme APIs.

#### Available Workaround
Window's `ContentRendered` event can be hooked and the application's resource dictionary can be re-evaluated by the developers.

Something along the these lines needs to be done:

```cs
private void ReactiveWindow_ContentRendered(object sender, System.EventArgs e)
{
    var x = Application.Current.Resources;

    Application.Current.Resources = null;

    Application.Current.Resources = x;
}
```

Due to the availability of a word-around, this is **not a blocker** for .NET9, preview 7 release.

**Closed** 2024-08-09 13:27 UTC
Labels: Investigate, :construction: work in progress

**Comment by Junjun-zhao** [comment] 2024-08-15 08:51
Verified this issue with dotnet-sdk-9.0.100-rc.1.24413.1, it has been fixed.
