### ISSUE TITLE
OnApplyTemplate not called on ContentControl

### ISSUE THREAD

**Issue by mysteryx93** [dotnet/wpf#1966] opened 2019-09-27 02:31 UTC
Version: .NET Core 3
Windows 10 x64
It works in .NET Framework 4.8

I have a WPF user control deriving from ContentControl. It's working fine in .NET Framework 4.8. In .NET Core 3, however, OnApplyTemplate never gets called. (MediaPlayerWpf inherits from ContentControl)

```
public class MpvMediaPlayer : MediaPlayerWpf
{
    public override void OnApplyTemplate()
    {
        base.OnApplyTemplate();
        // This never gets called.
    }
}
```

**Comment by weltkante** [comment] 2019-09-27 07:41
Works for me in both 3.0 GA (3.0.0-rc1-19456-20) and an older preview 8 I had lying around (3.0.0-preview8-28376-27). I'm using this code and can put a breakpoint into OnApplyTemplate which gets hit correctly. Can you provide a reproduction example?

<details><summary>working code</summary>

```C#
namespace WpfApp1
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }
    }

    public class MediaPlayerWpf : ContentControl
    {
    }

    public class MpvMediaPlayer : MediaPlayerWpf
    {
        public override void OnApplyTemplate()
        {
            base.OnApplyTemplate();
            // This never gets called.
        }
    }
}
```

```XAML
<Window x:Class="WpfApp1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:local="clr-namespace:WpfApp1"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <local:MpvMediaPlayer />
    </Grid>
</Window>
```

</details>

**Comment by mysteryx93** [comment] 2019-09-27 12:20
Reproduced the problem. The line causing OnApplyTemplate to never trigger is DefaultStyleKeyProperty. Comment that line and it gets triggered

```
public class MpvTestBase : ContentControl {
    static MpvTestBase() {
        DefaultStyleKeyProperty.OverrideMetadata(typeof(MpvTestBase), new FrameworkPropertyMetadata(typeof(MpvTestBase)));
    }

    public override void OnApplyTemplate() {
        base.OnApplyTemplate();
    }
}
```

**Comment by weltkante** [comment] 2019-09-27 12:40
Thats probably a duplicate of #1699 - Desktop Framework had `Properties\AssemblyInfo.cs` in the project template which contained a [`[assembly: ThemeInfo(...)]`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.themeinfoattribute?view=netcore-3.0) attribute which is required for `generic.xaml` to work. You have to add that attribute manually for now.

**Comment by vatsan-madhavan** [comment] 2019-10-22 00:16
The updated application templates in .NET Core 3.1 and .NET Core 5.0 should now address this.

**Closed by vatsan-madhavan** 2019-10-22 00:16 UTC
Labels: issue-type-bug, rank20
