### ISSUE TITLE
WPF Surface 2.0 SDK Source Code

### ISSUE THREAD

**Issue by Noemata** [dotnet/wpf#673] opened 2019-05-10 19:18 UTC
Given that much of the WPF Surface 2.0 SDK is both usable and useful when developing WPF .Net 4.x applications, it would be great to see the WPF Surface 2.0 SDK published as open source.  Unlike the rest of the WPF sources, this could be done independently and immediately and would provide significant value to the community from day 1.

If nothing else, publish the source to ScatterView!

Thus, Microsoft could leave it to the community to integrate this work with the eventual .Net Standard 3.0 implementation of WPF.

**Comment by grubioe** [comment] 2019-05-29 20:28
Closing as duplicate of #118

**Closed by grubioe** 2019-05-29 20:28 UTC
