### ISSUE TITLE
Some programming ligatures do not work

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#282] opened 2019-01-22 17:42 UTC
<p>Visual Studio does not correctly display correctly some programming ligatures that contain a hyphen such as &lt;- or &lt;!--</p><p>This has been reported before:
</p><p>https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/12983895-fix-ligatures</p>
https://github.com/tonsky/FiraCode/issues/259

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/44061/some-programming-ligatures-do-not-work.html
VSTS ticketId: 422890_
_These are the original issue comments:_

Visual Studio Team on 4/18/2017, 01:50 PM (643 days ago): Thank you for your feedback. We have determined that this issue will not be addressed in the upcoming release. We will continue to evaluate it for future releases. Thank you for helping us build a better Visual Studio.

Leonardo Santagada on 6/5/2018, 05:11 AM (231 days ago): <p>would be great if this was fixed.</p>

Nathan Phillip Brink (binki) on 10/15/2018, 09:25 AM (99 days ago): <p>Please post your comments on the OP’s post rather than as solutions. Thanks!</p>

Bryan Slatner on 10/15/2018, 09:11 AM (99 days ago): Experiencing this in F#. Ligatures for |> and <| and others work, but not <- or ->
Rob LaDuca [MSFT] on 1/18/2019, 02:03 PM (3 days ago): <p>Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on problem reports with issues impacting a broad number of customers.</p>

Sergey Semushin on 1/19/2019, 06:22 AM (3 days ago): <p>So 36 upvotes doesn't cut it to "issues impacting a broad number of customers." I'm a bit surprised.<br></p>

Gareth Lees on 1/21/2019, 10:06 AM (23 hours ago): <p>I don't understand the closure without fixing, it's a core issue that impacts more on developers than you would normally imagine and is the reason that I have had to move to Rider and VS Code for a lot of my editing needs. Please reconsider this, especially as fixing it in VS would involve fixing it in WPF and have far-reaching effects.</p>

Amos Anderson on 1/21/2019, 10:44 AM (22 hours ago): <p>I can imaging leaving it as a low priority but not closing it. I agree that it's a situation that doesn't bring about the end of the world but some of us would like to see it fixed. </p>

Tobias Burger on 1/21/2019, 11:53 AM (21 hours ago): <p>So WPF will never get proper ligature support? I can remember the time where Microsoft was "pumped" that WPF was presented as one of the first technologies with ligature support (on Windows)...</p>

Stuart Lang on 1/21/2019, 11:56 AM (21 hours ago): <p>Closing this seems like a mistake to me. I'll take a look at the repo now wpf is open source, even if that means it will be years away from landing in VS. https://github.com/dotnet/wpf</p>

_These are the original issue solutions:_
(no solutions)

**Comment by rladuca** [comment] 2019-01-22 17:48
Dupe of #109 .  This was created via an automatic closeout from VS Feedback.

**Closed by rladuca** 2019-01-22 17:48 UTC
Labels: enhancement

**Comment by Predelnik** [comment] 2019-01-23 12:09
Thanks, at least now it's understandable why the issue was closed.

**Comment by karelz** [comment] 2019-01-24 07:11
Duplicate of #109

**Comment by karelz** [comment] 2019-01-24 07:11
@rladuca making GH recognize it as duplicated - see above ;)
