### ISSUE TITLE
Performance degradation when using Spell Checker

### ISSUE THREAD

**Issue by denis-adamchuk** [dotnet/wpf#3350] opened 2020-08-18 13:17 UTC
* **.NET Framework 4.8**
* Windows version: **2004 (OS Build 19041.450)** (yes, it includes KB4562899)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: **Yes**
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? **No**

 **Problem description:**

Application freezes for a few seconds when typing text into a TextBox with SpellChecker enabled.

For example, when I do Ctrl-V with a following snippet from the clipboard:
![image](https://user-images.githubusercontent.com/25159366/90517921-bd7d9e80-e16e-11ea-94f9-f1f31d9410ac.png)

Text **includes** apostrophes before and after code snippet (I work with markdown text).
I took the snippet from your codebase, but it does not matter what is inside apostrophes.

 **Actual behavior:** 

After Ctrl-V application freezes for a few seconds and I cannot type further text.
I also observe sporadic delays when text contains words in apostrophes.
When I pause application, stacktrace points (multiple times) to the code added in 751153802c4e4d06484743c351266c9831ade85d

`
 NdrClientCall2	Unknown
 ObjectStublessClient	C++
 _ObjectStubless@0	Unknown
 589966ef()	Unknown
 [Frames below may be incorrect and/or missing, native debugger attempting to walk managed call stack]	Unknown
 589966ef()	Unknown
 [Managed to Native Transition]	
 System.Windows.Documents.MsSpellCheckLib.Extensions.ToList	Unknown
 System.Windows.Documents.MsSpellCheckLib.SpellChecker.ComprehensiveCheckImpl	Unknown
 System.Windows.Documents.MsSpellCheckLib.SpellChecker.ComprehensiveCheckImplWithRetries.AnonymousMethod__0	Unknown
 System.Windows.Documents.MsSpellCheckLib.RetryHelper.TryExecuteFunction<System.__Canon>	Unknown
 System.Windows.Documents.MsSpellCheckLib.SpellChecker.ComprehensiveCheckImplWithRetries	Unknown
 System.Windows.Documents.WinRTSpellerInteropExtensions.ComprehensiveGetTokens	Unknown
 System.Windows.Documents.WinRTSpellerInterop.SpellerSentence.Segments.get	Unknown
 System.Windows.Documents.WinRTSpellerInterop.EnumTextSegments	Unknown
 System.Windows.Documents.Speller.SearchForWordBreaks	Unknown
 System.Windows.Documents.Speller.ExpandToWordBreakAndContext	Unknown
 System.Windows.Documents.Speller.ScanRange	Unknown
 System.Windows.Documents.Speller.OnIdle	Unknown
`

I'm not sure if it makes many different COM calls or there is a single COM call inside OnIdle which takes too long.
I'm not sure if it is somehow caused by my environment. Please let me know if you need extra details.
Any workaround is appreciated.
 
 **Expected behavior:**

Text typing does not have delays.

 **Minimal repro:**

It 100% reproduces on a WPF sample application in Visual Studio 2017/2019.
I can attach a full example, but I think this XAML is enough because the rest is auto-generated code.
`
<Window x:Class="WpfApp1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp1"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
   <Grid>
      <TextBox x:Name="textBox" TextWrapping="Wrap" Text="TextBox"
               AcceptsReturn="True" HorizontalScrollBarVisibility="Auto" VerticalScrollBarVisibility="Auto" SpellCheck.IsEnabled="True"/>
   </Grid>
</Window>
`

**Comment by peter-top** [comment] 2020-08-25 08:46
A similar issue was reported to our customer service last week. Several customers complained about performance degredation and micro-freezes when typing into a WPF-RichTextBox. Beside custom logic that's being executed on every key stroke in said RichtTextBoxe (for IntelliSense and other things) there ist also spell-checking enabled. The same performance degradation occured when pasting text (Strg+V).
Disabling the spell checker did improve the typing-performance - but not as much as needed.

After investigating the issue we could pinpoint the performance degradation and micro-freezes were caused by a patch that was delivered via windows 10 automatic update: 

https://support.microsoft.com/en-us/help/4569751/kb4569751-cumulative-update-for-net-framework

Uninstalling the KB4569751 eliminated the performance degradation.

I'm aware that this is a patch for the full .NET Framework 4.8 but maybe the cause of effect for this performance degradation is similar to the one mentioned above.

**Comment by denis-adamchuk** [comment] 2020-08-25 09:14
Thank you for a comment, @peter-top.

My users complain on this issue too.
I'm developing an open-source tool... and WPF TextBox is the only free TextBox control with a built-in spell checker that I've found so I would be really happy to find a workaround...

KB4569751 looks similar to KB4562899 that I mentioned in my description.
The former seems to be targeted for Win10 1909 and the latter is for Win10 2004.

**Comment by RevitArkitek** [comment] 2020-09-03 20:31
We are experiencing slowness now as well on our tool that uses a WPF TextBox for spell checking.

**Comment by garzooma** [comment] 2020-09-21 20:28
We're seeing the same multi-second lag between typing a key on the keyboard and seeing it appear on the screen in a simple application containing a WPF TextBox.  The specific situations:

1. After pasting in text with spelling errors, say, Lorem Ipsum.  _Not if the text doesn't have misspellings._
2. With SpellCheck enabled.  _Not if disabled._
3. On Windows 10.  _Not if Windows 7._

**Comment by jessekingf** [comment] 2020-09-21 20:50
I am seeing this as well, which makes my application almost unusable.

**Comment by garzooma** [comment] 2020-09-22 20:16
I did a bunch more trials and came up with a much simple scenario for demonstrating the issue:

1.)	You just need a single misspelled word, not a whole section of misspelled text.
2.)	Not just any misspelled word works.  I found one that causes the problem from the Lorem Ipsum text.  But a random series of letters doesn’t work.
3.)	There needs to be two lines, with a period at the end of the first line.

I also created a video demonstrating the problem, which I posted to YouTube: [https://youtu.be/ndVBaN07Gf0](https://youtu.be/ndVBaN07Gf0)

**Comment by JesikaDG** [comment] 2020-09-29 17:56
In our application, the update made our spellchecking area of our code 3000% slower than it had been. Customers are frustrated and demanding a fix. I have tried the review the code changes made by https://github.com/dotnet/wpf/pull/2871 and https://github.com/dotnet/wpf/pull/3092, but am not familiar with the code to really see the problem.
I have also profiled the code and found that most of the time is spent in System.Windows.Documents.MsSpelCheckLib.SpellChecker.ComprephensiveCheckImplWithRetries, which was called both directly and indirectly by System.Windows.Documents.WinRTSpellerInteropExtensions.ComprehensiveGetTokens
![EnumTextSegments profile](https://user-images.githubusercontent.com/4993406/94597337-4eea3100-0242-11eb-8e2f-28e6de9ec1ea.png)
![ComprehensiveCheckImplWithRetries Profiling](https://user-images.githubusercontent.com/4993406/94597304-42fe6f00-0242-11eb-85f2-89121a4d9887.png)

**Comment by denis-adamchuk** [comment] 2020-09-30 09:49
I think that applications where spell-checking is extremely important (e.g. commercial ones) may consider using [NetSpell ](https://github.com/loresoft/NetSpell) library by analogy with how [GitExtensions](https://github.com/gitextensions/gitextensions) did, see https://github.com/gitextensions/gitextensions/tree/master/GitUI/SpellChecker
I don't have a feeling that Microsoft gives a high priority to this issue.

**Comment by garzooma** [comment] 2020-10-02 19:46
We spoke with Microsoft, and they gave us an undocumented switch to set in app.config:

```
<runtime>
    <AppContextSwitchOverrides value="Switch.System.Windows.Controls.DoNotAugmentWordBreakingUsingSpeller=true"/>
</runtime>
```

It seems to make the problem go away for us.  I'd be interested to know what it shows in @JesikaDG's profiling.

**Comment by denis-adamchuk** [comment] 2020-10-03 10:20
@garzooma This configuration trick works like a charm for me, spell checking is no longer slow. Thank you.

**Comment by blakepell** [comment] 2020-11-15 23:23
I'm also experiencing slow behavior in a TextBox where spell check is enabled (not loading, slow typing).  Disabling spellcheck gets rid of the issue.   I noticed this after updating to .NET 5 (5.0.100) but I'm unsure if that was the cause or not.  I especially notice if I begin deleting text out of the text box.  Not sure how to apply this fix (or if it applies) to WPF on .NET Core.

**Comment by RevitArkitek** [comment] 2020-11-16 00:33
If you don't want to mess around with a config file, add this code after InitializeComponent:
`AppContext.SetSwitch(@"Switch.System.Windows.Controls.DoNotAugmentWordBreakingUsingSpeller", true);`

**Comment by blakepell** [comment] 2020-11-16 00:49
@RevitArkitek Thank you for the suggestion.  I just tried the `AppContext.SetSwitch` On .NET 5 and it still lags when typing heavily once a period, comma, semi-colon kind of character is in the box.

**Comment by jepmoel** [comment] 2021-02-25 10:22
We have the same issue. However it seems to be fixed in the .NET Framework February 2021 Cumulative Update Preview for .NET Framework. https://devblogs.microsoft.com/dotnet/net-framework-february-2021-cumulative-update-preview-for-net-framework/

My test shows positive results.

**Comment by ptholin** [comment] 2021-05-21 14:45
@blakepell
Did anyone find a fix that solves the performance issues on .NET 5?

**Comment by blakepell** [comment] 2021-05-21 16:13
@ptholin I was never able to find a fix other than disable spell checking all together (which is unfortunate).  It's directly related to the word breaking and the interop call, the performance hit doesn't happen when typing until some separator char is entered (and then it gets progressively slower with every additional separator / key stroke).  The text box is basically unusable with spell checking enabled when it lags a few seconds between every key stroke.

**Comment by vatsan-madhavan** [comment] 2021-05-21 17:14
@SamBent Did you have a fix for this ready at some point? I thought I saw a fix for this from you but maybe I'm mis-remembering a(n internal only) .NET Framework fix that's yet to make it to .NET 5.

**Comment by SamBent** [comment] 2021-05-21 17:18
It's fixed in .NET Framework, but not yet ported to .NET 5.

**Comment by ptholin** [comment] 2021-05-21 17:43
@SamBent This issue stops us moving from 4.8 to .NET 5. Do you know when we can expect the fix to be ported and released in .NET 5?

**Comment by SamBent** [comment] 2021-05-21 18:16
I'll try to get it into the next .NET 5 servicing update.  It may slip to the one after that, if the deadline is too close.

Thanks for the reminder.  I hadn't realized this was blocking .NET 5.

**Comment by ptholin** [comment] 2021-05-22 07:26
@SamBent @vatsan-madhavan @blakepell Thank you all for quick responses and for being very service minded.

**Comment by thorwm-zz** [comment] 2021-05-26 21:13
I hate to be the bearer of bad news but it seems that the slowness of the WPF Richtextbox is back. The 2021-03 Cumulative Update for Windows 10 - KB5001567 resolved the issue (March 2021) but now the slowness is back.  It doesn't matter if the spell check is on or off.
Did the latest Cumulative Update break this?  The WPF application I've written is targeting the .NET 4.6 framework.

**Comment by RevitArkitek** [comment] 2021-06-10 15:09
@thorwm-zz  Just to confirm, are you using the DoNotAugmentWordBreakingUsingSpeller switch?

**Comment by thorwm-zz** [comment] 2021-06-12 01:03
@RevitArkitek - I've tried it both ways, with and without, and no improvement:

<runtime>     
    <AppContextSwitchOverrides value="Switch.System.Windows.Controls.DoNotAugmentWordBreakingUsingSpeller=true"/>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Memory" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.1" newVersion="4.0.1.1" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Google.Apis.Auth" publicKeyToken="4b01fa6e34db77ab" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.48.0.0" newVersion="1.48.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>

**Comment by JesseDietrichson** [comment] 2021-07-30 02:52
@SamBent Was this ever fixed in .NET 5? I still seem to be seeing input lag issues with RichTextBox.

**Comment by SamBent** [comment] 2021-08-17 22:31
Fix ported to 5.0.10, 6.0.

**Closed by SamBent** 2021-08-17 22:31 UTC
Labels: Bug, netfx-servicing-approved, issue-type-netfx-port

**Comment by SamBent** [comment] 2021-08-17 22:34
@thorwm-zz - if you're seeing slowness with the switch set to True, it's a different bug.  I'm not seeing it.  Please open a new issue, and include a repro.

**Comment by blakepell** [comment] 2021-09-18 20:22
I can confirm that 5.0.10 fixed this issue for me.  Thank you @SamBent, it's appreciated.
