### ISSUE TITLE
XmlLanguage.GetEquivalentCulture doesn't match System.Globalization.CultureInfo

### ISSUE THREAD

**Issue by innominate227** [dotnet/wpf#7307] opened 2022-11-22 00:38 UTC
* .NET Core Version: 5.0
* Windows version: windows 10
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No

 **Problem description:**
_XmlLanguage.GetEquivalentCulture()_ no longer matches _new System.Globalization.CultureInfo_.
When compiling with netcoreapp3.1 string1 and string2 in the code block below are the same.  With net5.0 they are different.
```
var string1 = (-10).ToString("C2", new System.Globalization.CultureInfo("en-US"));
var string2 = (-10).ToString("C2", System.Windows.Markup.XmlLanguage.GetLanguage("en-US").GetEquivalentCulture());
```

 **Actual behavior:** 
string1 and string2 difer 

 **Expected behavior:**
string1 and string2 are the same
 
 **Minimal repro:**
See description

**Comment by anjalisheel-wpf** [comment] 2023-01-27 11:35
@innominate227 This is not reproducible, working fine for me, please check the attached screen recording for your reference, I am testing it on the environment provided by you only.

https://user-images.githubusercontent.com/85492722/215076983-7ec651e4-d40f-48d2-9aa4-8d357474f7ae.mp4

**Comment by innominate227** [comment] 2023-01-27 17:09
Here is a reop showing the issue: https://github.com/innominate227/WpfCurrencyNegativePatternIssue.  And screenshot of what i see when debugging.
![image](https://user-images.githubusercontent.com/1129177/215150278-6e2d1eec-3e80-4b3e-89ae-bdb9865303e2.png)

**Comment by miloush** [comment] 2023-01-30 13:34
One situation where `CultureInfo` constructor and `XmlLanguage.GetEquivalentCulture()` differs is when user has customized the formatting in the control panel/settings (in which case this would be a duplicate of #1946). @innominate227 has this happened here? Can you post a screenshot of _Settings > Time & language > Language & region_ and of _Control Panel > Region > Additional settings > Currency_?

**Comment by innominate227** [comment] 2023-02-13 18:19
![image](https://user-images.githubusercontent.com/1129177/218540867-2f7d7370-e3ad-4971-9624-e751726cdb4e.png)

![image](https://user-images.githubusercontent.com/1129177/218541031-38fb9de9-e65c-49cb-8690-d2fa23228beb.png)

![image](https://user-images.githubusercontent.com/1129177/218541257-25dde0e6-7304-4369-b9e8-b086f0f58537.png)

**Comment by miloush** [comment] 2023-02-16 18:18
Did you change the negative currency format?

![image](https://user-images.githubusercontent.com/10546952/219453171-6e1e5367-6671-499a-aeac-7733233c3b8f.png)

For me the default US defaults do not use the parenthesis. If that is the case, it is the issue I mentioned.

**Comment by innominate227** [comment] 2023-02-16 18:30
I did not.  Mine also looks the same.
![image](https://user-images.githubusercontent.com/1129177/219454672-41731a62-f87d-4464-a375-6854cef02876.png)

And my sample app still shows
![image](https://user-images.githubusercontent.com/1129177/219455554-51d7e60b-f524-4cdc-b041-07dc57e2dd95.png)

**Comment by miloush** [comment] 2023-02-16 18:37
But in your previous picture it shows the parenthesis format in this dialog?

**Comment by innominate227** [comment] 2023-02-16 18:37
It would be interesting to see what old .net version display like on your machine.  For me.

net framework 4.8
![image](https://user-images.githubusercontent.com/1129177/219456777-16284596-9264-4ef8-a5ce-eaaf3f0bad58.png)

net core 3.1
![image](https://user-images.githubusercontent.com/1129177/219456935-f82b640e-f037-4e7a-9585-c2522c752b5b.png)

net 5.0
![image](https://user-images.githubusercontent.com/1129177/219457097-f3f96d92-e7a9-4623-811e-1df6094dcb8c.png)

net 6.0
![image](https://user-images.githubusercontent.com/1129177/219457184-989f5b40-99eb-44b9-bed3-7951d3e4f0c3.png)

**Comment by miloush** [comment] 2023-02-16 18:37
oh right sorry my bad different tabs

**Comment by miloush** [comment] 2023-02-16 18:44
For the record I think this was a change in .NET Core (rather than WPF). I am just trying to find some document to point to.

**Comment by miloush** [comment] 2023-02-16 19:00
Here we go: https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu

```
<ItemGroup>
	<RuntimeHostConfigurationOption Include="System.Globalization.UseNls" Value="true" />
</ItemGroup>
```

should restore the .NET Framework behavior.

**Closed** 2023-05-02 13:02 UTC
Labels: :mailbox_with_no_mail: waiting-author-feedback, :zzz: no-recent-activity
