### ISSUE TITLE
WPF DataGrid column visibility change breaks databinding

### ISSUE THREAD

**Issue by grubioe** [dotnet/wpf#739] opened 2019-05-23 15:52 UTC
Copied from VSO ID: 892081
* Windows version: (`winver`):
  * Windows Version: Windows 10 i.e version 1803  
  * Visual Studio Version: 2019 16.0.3
  * .Net Version: 4.7.1, 4.7.2, 4.8

* Does the bug reproduce also in WPF for .NET Framework 4.8?: **Yes**, .Net Framework 4.7.1, 4.7.2, 4.8

 
 
**Problem Description:**
=============
 Customer has created a WPF application based on WPF's DataGrid control. 
He creates the DataGrid control with columns with Visibility="Collapsed" 
Making such a collapsed column visible may destroy data binding of the first visible column's 
cell occurring after the last collapsed column in the grid.
 
**Longer version:**
```xml
<DataGrid x:Name="theGrid" AutoGenerateColumns="False">
 <DataGrid.Columns>
  <DataGridTemplateColumn Header="Visible 1" CellTemplate="{StaticResource ComboTemplate}"/>
  <DataGridTemplateColumn Header="Collapsed 1" Visibility="Collapsed" x:Name="col1" />
  <DataGridTemplateColumn Header="Collapsed 2" Visibility="Collapsed" x:Name="col2" />
  <DataGridTemplateColumn Header="Collapsed 3" Visibility="Collapsed" x:Name="col3" />
  <DataGridTemplateColumn Header="Visible 2" CellTemplate="{StaticResource ComboTemplate}"/>
  <DataGridTemplateColumn Header="Visible 3" CellTemplate="{StaticResource ComboTemplate}"/>
```
 
When setting a not shown column (Visibility=Collapsed) to visible and said column is between two collapsed columns, 
the cell of the first visible column after the last collapsed column in the grid will be recreated 
and this will furthermore cause, that the ComboBox in that cell will lose its bound value. 
 
Since this might sound a little bit confusing, there is a sample app to demonstrate the behavior. 
 
**Steps to reproduce:**
=============

1.) Use a machine with Visual Studio 2019 and the .Net Framework 4.8 installed
2.) Unzip the attached sample DataGridColumnVisibilityAndBindingIssue.rar
3.) Run the sample
4.) Press the ToggleBotton "Collapsed 2" to make the DataGrid's 3rd column visible
 
**Actual Result**
=============
The ComboBox will lose its text "One" in the first cell of the 4th column "Visible 2" 
 
 
**Expected Result**
===============
The ComboBox will keep its text "One" in the first cell of the 4th column "Visible 2" 
 
 
When starting the app, you have 3 ToggleButtons, each one for hiding and showing a column. 
There is also an event handler attached to the DataGridCell.Loaded event, so we can see, 
which cells have been created & loaded. 
If you toggle buttons 1 & 3, everything works as expected: Columns 1 & 3 will be shown or collapsed. 
There is no tampering around with any bindings. 
In the debug output you'll see, that the cell of the column being set visible has been loaded. 
But if you press Button 2 to show Column 2 (columns "Collapsed 1" & "Collapsed 3" must not be visible, 
otherwise this bug will not occur), 
the column will show properly, but the value in the combo box of column "Visible 2" will be lost. 
 
If you look into the debug output, you'll find the following: 
Loaded: Hash=[ 62990845] Index=[2] Header=[Collapsed 2] 
Loaded: Hash=[ 26550365] Index=[4] Header=[Visible 2] 
Which means, that the DataGridCellsPresenter did create a new cell container for the column "Visible 2", 
although it already had one and was visible all the time. 
That new cell has then for some reason a broken binding or at least the selected item isn't set correctly.

**Preliminary Investigation:**
===============

1. Changing visibility of column A sometimes causes cell templates for column B to be re-created.  Repro shows one example; there are surely others.
2. Some bindings in B's template react poorly to being replaced.  Instead of simply going away, they install a bad value into the binding group's proposed-value table.  In the repro, the binding 
```xml 
<ComboBox SelectedItem="{Binding Item}" ItemsSource="{Binding Items}"/>
```
installs null as the proposed value for the SimpleViewModel.Item property.

3. The new instance of B's template uses the proposed value (null) instead of the data item's value ("One").  This is correct, it's what makes template replacement work, as when you open a cell for editing and replaces its display template with its edit template (or vice versa).
4. The binding from (2) can be affected by other bindings in the template.   (In the repro, SelectedItem can be changed indirectly by changing ItemsSource.)  This situation has led to problems in the past, arising from event-leapfrogging or aliasing where it's challenging to recognize whether a change comes from user input or from a side-effect of some other action that shouldn't cause changes in the data-item.

Further investigation is needed to determine

1. when does DataGrid re-create column templates
2. how can bindings distinguish real changes from side-effect ones - can/should DataGrid do anything to help
3. can this pollution of the proposed-value table occur with "normal" bindings (that lack the interdependence of bindings involving the selection properties)
4. does this pollution affect other situations when column templates are replaced, e.g. column virtualization

 
[DataGridColumnVisibilityAndBindingIssue.zip](https://github.com/dotnet/wpf/files/3213068/DataGridColumnVisibilityAndBindingIssue.zip)

**Comment by anjali-wpf** [comment] 2023-09-13 06:35
@grubioe - It looks like this issue is not reproducible on .NET Core, could you please confirm?

If the issue can only be reproduced on .NET Framework and not .NET Core, you may close the issue here and open a DTS issue instead.

**Closed** 2023-10-04 10:01 UTC
Labels: Bug, :mailbox_with_no_mail: waiting-author-feedback, :zzz: no-recent-activity
