### ISSUE TITLE
Hit test fails if mouse is over a text object

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#642] opened 2019-05-03 19:07 UTC
<p>Hello Microsoft Support,</p><p>I've drawn a text by a DrawingVisual object, but the hit test fails when the mouse pointer is on it. For hit testing I'm using a GeometryHitTestParameters and EllipseGeometry objects. I've notice that if I use a PointHitTestParameters object, so all works well.</p><p>I've attached a complete solution that show the problem. Let me point out, that this issue is very serious for us because it doesn't allows to go on in our work.<br>Thank you in advance.<br>Best regards,<br><br>Simone</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/533445/hit-test-fails-if-mouse-is-over-a-text-object.html
VSTS ticketId: 847713_
_These are the original issue comments:_

Visual Studio Feedback System on 4/15/2019, 07:36 PM (17 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Jeff Schwartz [MSFT] on 4/16/2019, 04:20 PM (16 days ago): <p>Thanks for sharing feedback <a rel="user" href="https://developercommunity.visualstudio.com/users/86125/82408540-96cb-425a-a759-0107c4e509f6.html" nodeid="86125">@Simone Padovan</a>.  Can you elaborate more on what is not happening that you would expect?</p><p>In the attached sample I am seeing the proper events fire and callbacks fire (by setting break points and mousing over the text block).  Thanks</p>

Jeff Schwartz [MSFT] on 4/17/2019, 02:49 PM (15 days ago): <p>Thanks for the details.  I am going to route to the WPF team.</p>

_These are the original issue solutions:_

Simone Padovan solved on 4/17/2019, 10:14 AM (16 days ago), 0 votes: 
<p>Hello Jeff,</p>
<p>thank you for the answer. Sorry, I was unclear. Actually the HitTestCallback is called, because it is a consequence of the VisualTreeHelper.HitTest (RenderingHost.cs file line 34) method call from the mouse move event handler. <strong>But the interesting point</strong> is that the found object isn't the DrawingVisual of the text but it is the RenderingHost parent. The evidence is that you aren't able to see the &quot;Entity found !!&quot; message box. This occurs because the VisualTreeHelper.HitTest is called by passing a GeometryHitTestParameters as fourth parameter. Instead if you use a PointHitTestParameters you will see the message. The code is ready: simply comment/uncomment the 33 and 34 lines in the RenderingHost.cs file. Let me point out, that this issue is linked to the matrix transform at line 34 in the MainWindow.xaml.cs file: in fact if you comment it and the 37 line, the text is recognized and you will see the &quot;Entity found !!&quot; message box.</p>
<p>I think that this issue is linked to my other bug report <a target="_blank">The PathGeometry filling fails…</a> just that the point is the area painting but the problem source is the matrix: It would be great if you solve two problems at once.</p>
<p>Thank you in advance.</p>
<p>Regards,</p>
<p>Simone</p>

**Comment by Simon-IT** [comment] 2019-09-03 09:59
This was my reporting. After further investigation, the problem is not related to a text object but to all geometries where more than one transformation is applied to it. In the hit testing by geometry algotithm, the order in which the transformations are crosses is wrong. I've attached a VS solution that show better the problem: simply compile and test the project with and without the APPLY_TWO_SEPARATED_TRANSFORMATIONS conditional compilation symbol. Move the mouse over the text and/or circle. I'll open a pull request with my changes.

![Immagine](https://user-images.githubusercontent.com/24890180/64163612-e1eb4880-ce41-11e9-9c74-31b2a3780888.png)

[HitTestringByGeometryFails.zip](https://github.com/dotnet/wpf/files/3568901/HitTestringByGeometryFails.zip)

**Comment by weltkante** [comment] 2019-09-11 10:46
@grubioe can we get that reclassified and not put on 'future'? Its a genuine framework bug and the PR basically solved the problem already.

The problem is that when you push multiple matrix transformations into a DrawingContext the framework in some code paths (i.e. when hit testing) evaluates them in the wrong order.

**Comment by grubioe** [comment] 2019-09-20 17:22
@Simon-IT  - can you elaborate more on your business scenario and give us a bit more sense of the impact of this bug?    Given that 3.1 is an [LTS release](https://dotnet.microsoft.com/platform/support/policy/dotnet-core) the bar is much higher.   Thank you.

**Comment by weltkante** [comment] 2019-09-20 18:32
Not speaking for the OP, but having looked at the bug (and debugged it) I'll try to describe its impact. The bug is a math error in a very specialized code path composing transformation matrices when hit testing against a DrawingContext, you hit this code path when you have pushed multiple transformation matrices into a DrawingContext.

The impact of the bug is that it makes DrawingContext Push operations not composable. If you have a Render override on a Control or are using DrawingVisuals you cannot write modular code to draw into the DrawingContext using Push operations (you usually use Push operations when you have reusable drawing functions, you push the transformation to determine the position and scale of what you are drawing, the drawing code then can be position independent). If you happen to push multiple transformations (i.e. write composable code) they will trigger this bug and what you have drawn will not be hit-testable.

The workaround is to not use DrawingContext Push operation more than once and instead precomposing all transformations in the callers (keeping your own stack of transformations). You could also write a wrapper around DrawingContext to isolate it, but either way its a very intrusive workaround because you cannot use the WPF API as-is and have to write a replacement.

**Comment by Simon-IT** [comment] 2019-09-20 20:57
Hi, @weltkante explained well the problem. In our company, we are rewriting our sppecialized CAD program from WinForms to WPF. Besides using WPF for the UI, we use it for geometry drawing operations too. The graphic engine draws all the geometries into DrawingVisual objects that are children of a user control derived from FrameworkElement. This control has a scale transform with Y = -1 to have Y axis that points up. For every geometry we use a transformation for zoom a pan features but text objects has one more (another Y = -1) to compensate the "mirror" effect. This push two transformations that will be composed into the render pipe. This trigger the bug.
In this regard I wish to recall the oder bug [643](https://github.com/dotnet/wpf/issues/643) which is perhaps even more important than this. I'll continue the discussion about it at the proper issue page.
Thank you.

**Comment by Simon-IT** [comment] 2019-09-23 11:18
@grubioe I noticed that the pull request [1761](https://github.com/dotnet/wpf/pull/1761) for this bug it is marked for 5.0. 5.0 will be in **November 29, 2020**. How do we do ? It is impossible for us make good software with this bug. Moreover the solution is very simple and I think it isn't a big job or it need a big time to fix it. Please can we hope for 3.1 ?

**Comment by grubioe** [comment] 2019-09-23 15:42
Thanks for the information @Simon-IT - we are reviewing as a team this week to consider for 3.1.

**Comment by grubioe** [comment] 2019-09-26 04:53
@Simon-IT - are this issue and #643 blocking your company from migrating to .NET Core?  Are both needed concurrently? Meaning that you wouldn't be able to move forward if both are not fixed?   To solve for #643 seems more complex and likely that it cannot be included in .NET 3.1.  

Also, it seems that this issue (#642) has been in the framework for a while (5+ years) and while not ideal I'd make the case that given that a workaround exist (albeit intrusive) it could wait until .NET 5.

**Comment by Simon-IT** [comment] 2019-09-26 08:24
@grubioe First of all, thank you for the support.
> are this issue and #643 blocking your company from migrating to .NET Core? Are both needed concurrently? Meaning that you wouldn't be able to move forward if both are not fixed?

Yes. For a CAD program, pan and zoom features are basic tools. Also, filling shapes is meaningful for our goals.

>To solve for #643 seems more complex and likely that it cannot be included in .NET 3.1.

I don't know who could be notify when I replay to an issue, but have you read my suggestion for a possible solution at [643 issue comment](https://github.com/dotnet/wpf/issues/643#issuecomment-534941415) ?

> Also, it seems that this issue (#642) has been in the framework for a while (5+ years) and while not ideal I'd make the case that given that a workaround exist (‎albeit intrusive‎) it could wait until .NET 5.

You are right. But, as you know better than me, often a workaround calls another workaround and another and so on. Among other things this adds complexity and computational weight.

**Comment by grubioe** [comment] 2019-09-27 22:17
Thanks for the additional information Simon.  We are considering taking both #643 and this issue for .NET 3.1.  We'll let you know if something changes.

**Comment by Simon-IT** [comment] 2019-09-30 07:56
Thank you very much. I hope it will be for 3.1

**Closed** 2019-11-07 19:39 UTC
Labels: issue-type-bug, vsfeedback
