### ISSUE TITLE
Preview 7 is breaking BAML resources for VB WPF apps

### ISSUE THREAD

**Issue by jaredpar** [dotnet/wpf#9656] opened 2024-08-27 18:10 UTC
### Describe the bug

After upgrading to the .NET 9 Preview 7 SDK our WPF VB projects BAML files are corrupted. This is blocking our adoption of preview 7 as our binaries are effectively un-runnable.

### To Reproduce

1. Clone github.com/dotnet/roslyn
2. Build with the .NET 9 Preview 7 SDK 
3. Observe the binary `artifacts\bin\Microsoft.CodeAnalysis.EditorFeatures.Wpf\Debug\net472\Microsoft.CodeAnalysis.EditorFeatures.Wpf.dll` under IL Spy

You will see that the BAML resources are corrupted 

![image](https://github.com/user-attachments/assets/359f20ff-1535-45cb-a02c-e06b08939fc0)

The expected result is clean BAML resources

![image](https://github.com/user-attachments/assets/b0985deb-3736-464b-b268-5e7077f7c8ae)

### Exceptions (if any)

This results in XML exceptions trying to open our WPF application at execution time.

**Comment by miloush** [comment] 2024-08-27 23:29
Duplicate of pinned https://github.com/dotnet/wpf/issues/9582 (and https://github.com/dotnet/wpf/issues/9620 and #9636). Fixed in RC by https://github.com/dotnet/wpf/pull/9584.

**Closed by miloush** 2024-08-27 23:29 UTC
Labels: Untriaged, area-NetSDK
