### ISSUE TITLE
Permission to publish Surface SDK source code.

### ISSUE THREAD

**Issue by Noemata** [dotnet/wpf#3134] opened 2020-06-12 14:16 UTC
As mentioned here: https://github.com/dotnet/wpf/issues/118

I would like to get permission to publish the reverse engineered source code for the WPF Surface SDK.  A lot of very valuable code is currently out of reach that would be very beneficial to the WPF user community.

Can someone from Microsoft please provide some sort of legal waver for this?  It's a much better starting point than nothing.

**Comment by fabiant3** [comment] 2020-06-15 17:57
Closing as duplicate of #118

**Closed by fabiant3** 2020-06-15 17:57 UTC
