### ISSUE TITLE
Startup Window launches incorrectly

### ISSUE THREAD

**Issue by poqut** [dotnet/wpf#624] opened 2019-04-23 15:34 UTC
- .NET Core Version: 3.0.100-preview4-011223 (also tried with daily preview5)
- Windows version: Windows 10 1809 17763.437 (Parallels Desktop VM, Custom Scale: 350%, Resolution: 3360x2100)

Startup Window launches small and ignores properties like WindowStartupLocation (launches at random positions instead of being centered)

After that first launch, all other windows launch properly as it should be.

It was working before preview4 and still works if I downgrade to preview3.

I've created a new test project and here is the screenshots:
https://prnt.sc/nfu3y5
https://prnt.sc/nfu3qs

**Comment by rladuca** [comment] 2019-05-29 19:37
The fix for this was done in #741, it's a dupe of #334 .

You should see this fix in a future daily build.

**Closed by rladuca** 2019-05-29 19:37 UTC
Labels: bug, regression
