### ISSUE TITLE
dotnet msbuild lost resource files in .Net Core 3.0 Preview 7

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/wpf#1603] opened 2019-08-12 18:21 UTC
_From @Lily721 on Monday, August 12, 2019 9:27:09 AM_

Hi, 

I got a WPF .net core project, and I found out the resources in output dll is different between right click 'Build' button on Visual Studio and use command line 'dotnet msbuild ***.csproj'. Please try my attached sample. You'll see there's three images under resources folder, and I'd like to pack it to resources, so I added following code to RESX file:

`
  <data name="error" type="System.Resources.ResXFileRef, System.Windows.Forms">
    <value>error.png;System.IO.MemoryStream, mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
`

Then, I build the project in Visual Studio 2019 and following structure when reflect the output dll:

 WpfApp_ResourceTest.Resources.CheckResource.resources
    ┖ error
    ┖ info
    ┖ warning

But, if build this project with 'dotnet msbuild' or 'dotnet build' in command line, all the icon resource will lost. This will cause a big problem for our project, we can not find the resource file by resource key.

Another issue is, if the namespace is A, and my resource file located in B folder with the name C.resx, then it will create A.B.C.resources when you reflect output dll under .Net Core, but it creates A.C.resources when you use framework platform, I guess it is a bug for .Net Core.

Any idea is welcome.
[WpfApp_ResourceTest.zip](https://github.com/dotnet/core/files/3491669/WpfApp_ResourceTest.zip)

_Copied from original issue: dotnet/core#3172_

**Comment by carlossanlop** [comment] 2019-08-12 18:21
_From @carlossanlop on Monday, August 12, 2019 6:19:00 PM_

Thanks for reporting this issue, @Lily721 . I am transferring it to the wpf repo, where they will be able to help you with your problem.

**Comment by ojhad** [comment] 2019-08-23 01:06
@lily721 
Closing this issue because I am unable to reproduce using the latest .NET Core 3.0 Preview 9 build.
My recommendation would be to download the latest build and see if this is still a problem.

Regarding the naming discrepancy you mentioned, when building for .NET Framework 4.7.2, I am seeing the embedded resource file having the same naming structure as what is being output in .NET Core (`A.B.C.resources` from your example above). Which version of framework are you seeing this happen in? If this is giving you problems, please log a separate issue.

**Comment by Lily721** [comment] 2019-08-26 09:26
@ojhad , I cannot confirm this because I cannot find preview 9 at official website. I can verify this after next version launched, thank you any way.

**Comment by ojhad** [comment] 2019-08-28 23:59
@Lily721 Fix is now in the latest `Release/3.0.1XX` RC build that you can find here: https://github.com/dotnet/core-sdk/blob/master/README.md#installers-and-binaries

**Comment by Lily721** [comment] 2019-09-20 02:33
@ojhad , please try this sample with .Net Core 3.0.1 rc1 again, and build with command line "dotnet msbuild WpfAPP_ResourceTest.csproj", following issue occurred:

_C:\Program Files\dotnet\sdk\3.0.100-rc1-014190\Microsoft.CSharp.CurrentVersion.targets(100,9): error MSB3041: Unable to create a manifest resource name for "Resources\CheckResource.resx". Could not find a part of the path 'E:\XATCDocuments\.NetCore3.0\WpfApp_ResourceTest\WpfApp_ResourceTest\Resources\Resources\CheckResource.cs'. [E:\XATCDocuments\.NetCore3.0\WpfApp_ResourceTest\WpfApp_ResourceTest\WpfApp_ResourceTest.csproj]_

But if you build the project in Visual Studio, everything works fine, is this a bug?

**Comment by Lily721** [comment] 2019-09-23 03:19
BTW, if you use Visual Studio 2019 Preview this issue occurred not matter use dotnet msbuild or use Build tool in VS.

**Comment by rladuca** [comment] 2020-01-24 18:31
@Lily721 Can you confirm if this is still an issue under the latest .NET Core 3.1?

I am seeing the following output from the project under `dotnet build` or `dotnet msbuild`.
![image](https://user-images.githubusercontent.com/20006987/73093866-44e28800-3e94-11ea-81c1-5d8da7f78e1f.png)

**Comment by SebastianWojciechowski** [comment] 2020-01-31 14:15
I have similar issue. I use Visual Studio 16.4.4, SDK 3.1.101
Problem is with _Resource_ TestInputHelperFixture.SomeResource.dat file. 
The second one _EmbeddedResource_  TestInputHelperFixture.SomeEmbeddedResource.dat is working correctly.

I have a project with unit tests (nUnit), it is SDK project and has this in csproj:
```
  <ItemGroup>
    <EmbeddedResource Include="TestingResources\TestInputHelperFixture.SomeEmbeddedResource.dat" />
    <Resource Include="TestingResources\TestInputHelperFixture.SomeResource.dat" />
  </ItemGroup>

```
It targets project which has:
`<TargetFrameworks>net461;netstandard2.0</TargetFrameworks>`

When test project targets:
`<TargetFramework>net461</TargetFramework>`

- Build by Visual Studio attaches TestInputHelperFixture.SomeResource.dat file
- Build by `dotnet build` does not attach TestInputHelperFixture.SomeResource.dat file

When test project targets:
`<TargetFramework>netcoreapp3.1</TargetFramework>`

- Build by Visual Studio **does not** attache TestInputHelperFixture.SomeResource.dat file
- Build by `dotnet build` does not attach TestInputHelperFixture.SomeResource.dat file

**Closed** 2020-02-03 15:00 UTC
Labels: issue-type-question, needs-author-feedback, no-recent-activity, rank40
