### ISSUE TITLE
When stop hovering over control it's displayed incorrectly

### ISSUE THREAD

**Issue by PascalKoe** [dotnet/wpf#319] opened 2019-02-02 14:41 UTC
* .NET Core Version: 3.0.100-preview-010184
* Windows version: Windows 10 Education 1809 Build 17763.253
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
 
 **Problem description:**
Hovering over Controls (sometimes) causes them to display incorrectly. Either they get mostly the background color or they have some sort of out of focus zoomed in effect.
Couldn't reproduce it on a different Windows 10 Professional Version.
 
 **Actual behavior:**
When control isn't inside of a group box and I hover over the control and then leave it it's displayed incorrectly. Controls that don't have a hover animation don't seem to be affected (disabled buttons or labels for example).
 
 **Expected behavior:**
 Display correctly.

 **Minimal repro:**
Any application with the default controls will do as long as they have a hovering animation.
```
 <Window x:Class="TestApp.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:TestApp"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="9*"/>
            <RowDefinition Height="1*"/>
        </Grid.RowDefinitions>
        <GroupBox Header="A simple GroupBox" HorizontalAlignment="Left" Margin="0,0,0,0" VerticalAlignment="Top" Grid.Row="0">
            <Button Content="I dont disappear" FontSize="20"/>
        </GroupBox>
        <Button Content="I disappear" Grid.Row="1" FontSize="20"/>
    </Grid>
</Window>
```

![Minimal Repo](https://user-images.githubusercontent.com/15944057/52165354-13f7c900-2700-11e9-9cf3-69fa404ac67f.png)
Before hovering over the lower button.

![Minimal Repo after hover](https://user-images.githubusercontent.com/15944057/52165358-2b36b680-2700-11e9-8afe-807144fac711.png)
After hovering and leaving the button. Hovering and leaving the upper button doesn't produce the same issue.

![Option Menu of dnspy (64bit .NET Core WPF)](https://user-images.githubusercontent.com/15944057/52165299-21f91a00-26ff-11e9-9925-d28958d30036.png)
Screenshot from [dnspy ](https://github.com/0xd4d/dnSpy)(.NET Core version). The messed up stuff should be a bunch of checkboxes.

**Comment by stevenbrix** [comment] 2019-02-26 02:18
Thanks for filing this issue! What are the specs of your machine that this reproes on? Are you able to notice higher than usual CPU and/or memory usage when this occurs? Does the issue ever go away on it's own?

What exactly is the output of dnspy supposed to show? Looks like a pretty neat tool, but I'm not very familiar with it :)

**Comment by PascalKoe** [comment] 2019-03-02 13:00
Im running a Intel Core i9-9900k using the integrated UHD Graphics 630 with 32GB of RAM.
Couldn't notice any higher CPU usage. Memory usage also doesn't seem to be strange (~320MB).
The issue doesn't seem to go away by itself. Worked with it for over an hour and the bug still existed.

The output of dnspy should look like this:
![How it should look like](https://user-images.githubusercontent.com/15944057/53682026-f400f880-3cf1-11e9-81e4-33c01ad4437d.png)

**Comment by stevenbrix** [comment] 2019-05-24 19:23
Closing as duplicate of #707

**Closed by stevenbrix** 2019-05-24 19:23 UTC
Labels: bug
