### ISSUE TITLE
Selected value in ComboBox within the DataGridTemplateColumn is cleared on mouse wheel

### ISSUE THREAD

**Issue by MohanramAnbukkarasu** [dotnet/wpf#2952] opened 2020-04-28 14:40 UTC
**Problem description:**
Selected value in ComboBox within the DataGridTemplateColumn is cleared on mouse wheel
 
 **Actual behavior:** 
 I have created a sample with DataGridTemplateColumn which contains ComboBox as DataTemplate. I add a new object to the underlying collection which is bound to the DataGrid by clicking on a button. So that a new row will be added to the DataGrid template column. 

Once a new row has been inserted, I select an item from the newly added row's ComboBox and continue to add further rows to the DataGrid same like this. After inserting several rows, If I scroll down to the last row and scroll up to the first row using mouse wheel, the items selected in the row's ComboBox are cleared and the ComboBoxes are displayed with empty text.

 **Expected behavior:**
 The selected item in the ComboBox should not be cleared.
 **Minimal repro:**
Please find the sample application to reproduce this from the following link.

[DataGrid_TemplateColumn.zip](https://github.com/dotnet/wpf/files/4546456/DataGrid_TemplateColumn.zip)

**Comment by SamBent** [comment] 2020-07-06 00:14
[This issue is identical to [https://developercommunity.visualstudio.com/content/problem/1010353/selected-item-in-combobox-within-the-datagridtempl.html](https://developercommunity.visualstudio.com/content/problem/1010353/selected-item-in-combobox-within-the-datagridtempl.html), where it was resolved as "not a bug" with this response.]

Your sample never updates the SelectedProvision property. When you scroll away from the first item, it get re-virtualized. Then when you scroll back it gets de-virtualized, meaning that a new ComboBox is created and its SelectedValue is set from the data’s SelectedProvision property, which hasn’t been updated from its original value null. Thus the ComboBox displays empty.

Your template column doesn’t follow the expected pattern. You are expected to provide both a CellTemplate and a CellEditingTemplate; the former used to display the value, and the latter used to accept user edits. Without a CellEditingTemplate, the DataGrid thinks the column isn’t editable (i.e. read-only), and doesn’t apply the logic to commit pending edits. Meanwhile the binding in the CellTemplate, like all bindings in a DataGrid cell, is implicitly marked as UpdateSourceTrigger=Explicit to keep it from updating the data until the user commits a pending edit. The combination of these is what keeps your sample from updating the SelectedProvision property.

There are two ways you can get the desired behavior, depending on what your desire actually is.

1. Use the standard pattern. To do this, either add a CellEditingTemplate (with a similar ComboBox), or use the built-in column that does this for you: 
```
<DataGridComboBoxColumn Header="Combo" ItemsSource="{x:Static local:ViewModel.Fruits}" SelectedValueBinding="{Binding SelectedProvision}" DisplayMemberPath="Name"/>
```
(I’ve changed your data model slightly to lift the Fruits collection out of the individual Provision items into a static property where it can be shared by all Provisions. This is a more common and more efficient data design, and doesn’t have any bearing on your issue. The built-in column doesn’t support binding ItemsSource to a data-item property, as it’s not a common pattern.)

2. Mark the binding in your CellTemplate as “immediate update”:
```
SelectedItem="{Binding SelectedProvision, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"
```
This overrides the implicit behavior so that selecting an item in the ComboBox will immediately update the SelectedProvision property. But doing this has consequences. In a real app with many columns, users expect that pending edits are held until either the row is committed (ENTER, CTRL-ENTER, focus moves off the row, etc.) or reverted (ESC). Setting “immediate update” affects this; users can’t revert the change, the data model can run code that sees the change to SelectedProvision but not pending changes to other properties, etc.

**Closed by SamBent** 2020-07-06 00:14 UTC
Labels: issue-type-design-discussion
