### ISSUE TITLE
WPF build projects hand pick the Microsoft.NETCore.App references

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/wpf#9168] opened 2024-05-28 17:25 UTC
Projects in this repository hand pick the targeting pack references that come from the Microsoft.NETCore.App.Ref targeting pack which recently caused issues that required actions:
- https://github.com/dotnet/wpf/commit/d6b1f4560cb72806a9b55beae86ee5f769ec0960
- https://github.com/dotnet/wpf/commit/cb1bc77538a0fe02c4af9a364e515d2f77a5be12
- https://github.com/dotnet/wpf/commit/f704647788c026d99652b5b3716fab92486841d9
- https://github.com/dotnet/wpf/commit/93285ebf1dcd4e40549a001841179d2a1ec286e7

I would like to understand why wpf projects hand pick references. @jaredpar mentioned that there isn't really any benefit in doing. Libraries in runtime that are out-of-band did this as well in the past but we changed that a few years ago.

cc @ericstj

**Comment by jaredpar** [comment] 2024-05-28 17:52
The core problem is that we don't put any effort into testing subsets of our reference sets. There isn't really any effort into verifying a particular feature works with a subset of references, instead we put the effort into making sure that features work with the .NET X reference set. 

When you subset references you risk running into a number of problems:

1. Using a non-transitively complete reference graph. This means that bug fixes in the compiler, or new features, could cause errors when moving to new versions of the compiler ([example](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2264#issuecomment-788286687). These will always be resolved as "by design" and customers will be asked to have a transitively complete reference set. 
2. Getting errors when moving to new compiler features that require references that you don't have. New compiler features are tested against the net9.0 reference set, not subsets of the assemblies. 

There is also no meaningful perf benefit to referencing less assemblies. The compiler aggressively caches references, particularly ones in the core .NET reference set.

**Comment by ViktorHofer** [comment] 2024-05-28 18:57
@singhashish-wpf who is the right person on your team to chat about this?

**Comment by singhashish-wpf** [comment] 2024-05-29 05:07
@rchauhan18 and I will look into this, Let us know if there is something which should be changed.

**Comment by ViktorHofer** [comment] 2024-05-29 08:55
We basically want to understand why you hand pick references, i.e. in https://github.com/dotnet/wpf/blob/47efe4600a00ac059aeca109459e9a4e8132d907/src/Microsoft.DotNet.Wpf/src/PresentationUI/PresentationUI.csproj#L229-L257

... instead of just letting the TFM + FrameworkReference bring everything in automatically.

**Comment by jaredpar** [comment] 2024-05-29 16:42
@singhashish-wpf sure but why do we do this? As I mentioned above it's a recipe for hitting a number of problems because it's explicitly not tested. For WPF this turned into friction shipping .NET 9 features where as if WPF used the full reference set this wouldn't have happened. It's reasonable to expect that this will happen again in the future. 

Is there a reason you all can't use the normal full reference set here?

**Comment by singhashish-wpf** [comment] 2024-05-30 03:32
@jaredpar We are going run the experiment, to remove these references and use TFM + FrameworkReference thing, validate that first. Will update the thread with the findings.

**Comment by ThomasGoulet73** [comment] 2024-05-30 04:42
I did some snooping around to try to find if there was a reason for `NetCoreReference`.

I looked at the System.Xaml project because it was the first project open sourced in this repo and I saw that it hasn't always used `NetCoreReference`. It was added in dotnet/wpf#473, specifically this commit: 083719d2cc7e169148b94a148363584095bb0f6f which talks about "Integrate changes needed to use Microsoft.Dotnet.Arcade.Wpf.Sdk" so this might give some clue about the reasoning. @vatsan-madhavan who made the changes might have some context, AFAIK he isn't on the WPF team anymore but still works at Microsoft and answers questions in this repo from time to time when pinged.

I also saw this comment in the build files that might give some clues about the use of `NetCoreReference`: https://github.com/dotnet/wpf/blob/675f95f766b75c6a4f35d7d76c159320d138375c/eng/WpfArcadeSdk/tools/Pbt.targets#L29-L37

An explanation could be that it is to require explicit reference to new assemblies to avoid loading too many assemblies at runtime. WPF has a bad rep about slow startup and it employs a couple of "tricks" to reduce the need to load assemblies so this might be one of them. I don't know if those "tricks" are still needed or if this particular issue is one of those "tricks".

**Comment by ViktorHofer** [comment] 2024-05-31 10:47
> An explanation could be that it is to require explicit reference to new assemblies to avoid loading too many assemblies at runtime. WPF has a bad rep about slow startup and it employs a couple of "tricks" to reduce the need to load assemblies so this might be one of them. I don't know if those "tricks" are still needed or if this particular issue is one of those "tricks".

The number of (reference) assemblies that are passed to the compiler don't impact the number of assemblies that are loaded at run time. The runtime probes for and loads an assembly (with non-deterministic ordering) when it finds a type that needs to be resolved.

**Comment by ThomasGoulet73** [comment] 2024-05-31 13:18
> > An explanation could be that it is to require explicit reference to new assemblies to avoid loading too many assemblies at runtime. WPF has a bad rep about slow startup and it employs a couple of "tricks" to reduce the need to load assemblies so this might be one of them. I don't know if those "tricks" are still needed or if this particular issue is one of those "tricks".
> 
> The number of (reference) assemblies that are passed to the compiler don't impact the number of assemblies that are loaded at run time. The runtime probes for and loads an assembly (with non-deterministic ordering) when it finds a type that needs to be resolved.

That's true but what I meant was that with explicit references it means that you cannot use types from an assembly not explicitly referenced so it won't trigger the load of the assembly at runtime.

**Closed** 2024-11-11 05:30 UTC
Labels: Investigate, :construction: work in progress
