### ISSUE TITLE
image isn't rendered in wpf .net core project

### ISSUE THREAD

**Issue by XianghanWang** [dotnet/wpf#292] opened 2019-01-24 17:53 UTC
* .NET Core Version: 3.0 Preview1
* Windows version: 19H1
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes

Steps to reproduce:
1. Create new .net core WPF project
2. Add image element and set source to one image file.
3. F5

Actual: the image isn't rendered in UI.

**Comment by thomasclaudiushuber** [comment] 2019-01-24 20:30
Hi @XianghanWang, 

great finding.

How do you add the image? Are you using VS2019? 

I tried it with VS2019 and a .png file, and yes, it does not work by default. It's not a rendering issue, the problem is that the .png file does not get a Build Action when you add it. That means when you use it in XAML with an Image element, the file is not found, as it is not there at runtime. 

In VS2017 the BuildAction is set by default to "Resource", which includes the image and you can use it. You can do this manually by selecting the File in the Solution Explorer, pressing F4 to open the Properties, then change the BuildAction from "None" to "Resource". Now your image should render. If you don't use VS2019, try this in the .csproj file for your image:

```
<ItemGroup>
  <None Remove="coffeeCup.png" />
</ItemGroup>

<ItemGroup>
  <Resource Include="coffeeCup.png" />
</ItemGroup>
```

Does it work?

Beside the BuildAction "Resource" there's another option to embed an image: Set the BuildAction to "Content" and "Copy to output directory" to "Copy if newer", this should also make the image available at runtime, but not as part of your .dll, but as part of the output directory.

I think it's something that has to be fixed as part of VS2019 WPF tooling

**Comment by XianghanWang** [comment] 2019-01-24 20:48
Thanks @thomasclaudiushuber. Change BuildAction fix the problem. As you said, it is default Build Action error.

**Comment by fabiant2** [comment] 2019-01-24 23:40
@thomasclaudiushuber - truly appreciate your help. Would you mind opening an issue so we can properly fix this at some point?

**Comment by thomasclaudiushuber** [comment] 2019-01-30 10:04
@fabiant2 @XianghanWang 

I've added an issue for Visual Studio 2019 here: https://developercommunity.visualstudio.com/content/problem/440436/wpf-net-core-3-sdk-styled-project-images-png-jpg-e.html

That means this issue can be closed. 

Thanks,
Thomas

**Comment by stevenbrix** [comment] 2019-04-04 13:37
Closing as external

**Closed by stevenbrix** 2019-04-04 13:37 UTC
