### ISSUE TITLE
C# CompositionFailedException

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#447] opened 2019-03-18 02:24 UTC
Not sure who owns this exception when committing my staged code to Bitbucket. <br><br>Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part &quot;GitClientVS.UI.Views.PublishSectionView&quot;. ---&gt; System.Windows.Markup.XamlParseException: Set property 'System.Windows.ResourceDictionary.DeferrableContent' threw an exception. ---&gt; System.Xaml.XamlObjectWriterException: Set property 'System.Windows.ResourceDictionary.Source' threw an exception. ---&gt; System.IO.IOException: Cannot locate resource 'themes/metroheader.xaml'.<br>   at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)<br>   at System.IO.Packaging.PackagePart.GetStream(FileMode mode, FileAccess access)<br>   at System.IO.Packaging.PackWebResponse.CachedResponse.GetResponseStream()<br>   at System.IO.Packaging.PackWebResponse.GetResponseStream()<br>   at System.IO.Packaging.PackWebResponse.get_ContentType()<br>   at MS.Internal.WpfWebRequestHelper.GetContentType(WebResponse response)<br>   at MS.Internal.WpfWebRequestHelper.GetResponseStream(WebRequest request, ContentType&amp; contentType)<br>   at System.Windows.ResourceDictionary.set_Source(Uri value)<br>   at System.Windows.Baml2006.WpfSharedBamlSchemaContext.&lt;&gt;c.&lt;Create_BamlProperty_ResourceDictionary_Source&gt;b__342_0(Object target, Object value)<br>   at System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(Object instance, Object value)<br>   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(XamlMember member, Object obj, Object value)<br>   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)<br>--- End of stack trace from previous location where exception was thrown ---<br>   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)<br>   --- End of inner exception stack trace ---<br>   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)<br>   at MS.Internal.Xaml.Runtime.PartialTrustTolerantRuntime.SetValue(Object obj, XamlMember property, Object value)<br>   at System.Xaml.XamlObjectWriter.Logic_ApplyPropertyValue(ObjectWriterContext ctx, XamlMember prop, Object value, Boolean onParent)<br>   at System.Xaml.XamlObjectWriter.Logic_DoAssignmentToParentProperty(ObjectWriterContext ctx)<br>   at System.Xaml.XamlObjectWriter.Logic_AssignProvidedValue(ObjectWriterContext ctx)<br>   at System.Xaml.XamlObjectWriter.WriteEndMember()<br>   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)<br>   at System.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter)<br>   at System.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter)<br>   at System.Windows.SystemResources.ResourceDictionaries.LoadDictionary(Assembly assembly, String assemblyName, String resourceName, Boolean isTraceEnabled, Uri&amp; dictionarySourceUri)<br>   at System.Windows.SystemResources.ResourceDictionaries.LoadGenericDictionary(Boolean isTraceEnabled)<br>   at System.Windows.SystemResources.FindDictionaryResource(Object key, Type typeKey, ResourceKey resourceKey, Boolean isTraceEnabled, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference, Boolean&amp; canCache)<br>   at System.Windows.SystemResources.FindResourceInternal(Object key, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference)<br>   at System.Windows.FrameworkElement.FindResourceInternal(FrameworkElement fe, FrameworkContentElement fce, DependencyProperty dp, Object resourceKey, Object unlinkedParent, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference, DependencyObject boundaryElement, Boolean isImplicitStyleLookup, Object&amp; source)<br>   at System.Windows.StaticResourceExtension.FindResourceInAppOrSystem(IServiceProvider serviceProvider, Boolean allowDeferredReference, Boolean mustReturnDeferredResourceReference)<br>   at System.Windows.StaticResourceExtension.FindResourceInEnviroment(IServiceProvider serviceProvider, Boolean allowDeferredReference, Boolean mustReturnDeferredResourceReference)<br>   at System.Windows.StaticResourceExtension.TryProvideValueImpl(IServiceProvider serviceProvider, Boolean allowDeferredReference, Boolean mustReturnDeferredResourceReference)<br>   at System.Windows.ResourceDictionary.SetOptimizedStaticResources(IList`1 staticResources, IServiceProvider serviceProvider, StaticResourceExtension staticResourceWorker)<br>   at System.Windows.ResourceDictionary.SetKeys(IList`1 keyCollection, IServiceProvider serviceProvider)<br>   at System.Windows.ResourceDictionary.SetDeferrableContent(DeferrableContent deferrableContent)<br>   at System.Windows.Baml2006.WpfSharedBamlSchemaContext.&lt;&gt;c.&lt;Create_BamlProperty_ResourceDictionary_DeferrableContent&gt;b__297_0(Object target, Object value)<br>   at System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(Object instance, Object value)<br>   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(XamlMember member, Object obj, Object value)<br>   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)<br>   --- End of inner exception stack trace ---<br>   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)<br>   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)<br>   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)<br>   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)<br>   at GitClientVS.UI.Views.PublishSectionView.InitializeComponent()<br>   at GitClientVS.UI.Views.PublishSectionView..ctor(IPublishSectionViewModel vm)<br>   --- End of inner exception stack trace ---<br>   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()<br>   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()<br>   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)<br>   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)<br>   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()<br>   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.&lt;&gt;c__DisplayClass15_0.&lt;GetExportedValueHelper&gt;b__0()<br>   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportElement(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import, RuntimeExport export, Func`3 lazyFactory)<br>   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import)<br>   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.&lt;CreateValue&gt;b__10_0(RuntimeImport import)<br>   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()<br>   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)<br>   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)<br>   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()<br>   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()<br>   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)<br>   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)<br>   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()<br>   at Microsoft.VisualStudio.Composition.ExportProvider.&lt;&gt;c__DisplayClass53_0.&lt;CreateExport&gt;b__0()<br>   at Microsoft.VisualStudio.Composition.ExportProvider.&lt;&gt;c__DisplayClass55_0.&lt;CreateExportFactoryExport&gt;b__1()<br>   at Microsoft.VisualStudio.Composition.ExportProvider.&lt;&gt;c__DisplayClass54_0.&lt;CreateExportFactory&gt;b__0()<br>   at Microsoft.VisualStudio.Composition.DelegateServices.&lt;&gt;c__DisplayClass2_0`1.&lt;As&gt;b__0()<br>   at System.ComponentModel.Composition.ExportFactory`1.CreateExport()<br>   at Microsoft.VisualStudio.Composition.NetFxAdapters.MefV1ExportProvider.ComposablePartDefinitionForExportFactory.CreatePart()<br>   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.LifetimeContext.GetExportLifetimeContextFromExport[T](Export export)<br>   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.&lt;&gt;c__DisplayClass6_0`2.&lt;CreateStronglyTypedExportFactoryOfTM&gt;b__0()<br>   at System.ComponentModel.Composition.ExportFactory`1.CreateExport()<br>   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Create()

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/491375/c-compositionfailedexception.html
VSTS ticketId: 821871_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_

Ralf Pessel solved on 2019/3/18, 01:52 AM (8 hours ago), 0 votes: 
<p>Install the &quot;Clear MEF Component Cache&quot; in Visual Studio and delete the MEF Cache. The cache will be rebuild.</p>
<p>See: <a target="_blank">https://github.com/github/VisualStudio/issues/1340#issuecomment-346852177</a></p>

**Comment by geraldbauer** [comment] 2019-03-28 22:40
There appears to be a pattern starting to emerge for when I am seeing this error. (The Tools=>Clear MEF Component Cache is not resolving this issue.) 1) I have seen this happen when I just committed my Staged code and still have un-Staged changes that are in different folders. 2) I have seen this happen when I commit my changes that are across different folders. (Just trying to help.)

**Comment by geraldbauer** [comment] 2019-04-01 15:27
Also, I have multiple instances of Visual Studio open.

**Comment by stevenbrix** [comment] 2019-04-03 23:01
Thanks for filing this issue (and providing helpful information)! This looks like the same issue as #466. I'll close that one and use this as the master bug for this issue.

**Comment by matt-goldman** [comment] 2019-04-13 20:37
I have this same issue with the Bitbucket extension but it happens as soon as I open VS/Team Explorer. So unfortunately for me is unusable at this stage. Error code identical, I have also updated the Bitbucket extension TNA.

**Comment by 274188A** [comment] 2019-06-01 04:31
I'm also seeing this in VS 2019 Preview Ent
`VisualStudio.16.Preview/16.2.0-pre.1.0+28917.182`
Also using BitBucket extension.

**Comment by rladuca** [comment] 2019-06-01 14:57
@grubioe I am not convinced this is a WPF issue.  The common factor here seems to be the BitBucket extension.  Do you know what investigation VS did before we moved this issue from feedback?

**Comment by weltkante** [comment] 2019-06-01 19:51
@rladuca while the outer exception is VS this was probably moved here because of the inner exception `System.IO.IOException: Cannot locate resource 'themes/metroheader.xaml'.` might be related to the WPF packaging/resource resolution system.

Even if its identified to be VS and not WPF which is causing this, it would be nice to not just close these issues. It doesn't look great to users of VS if developercommunity issues are closed by moving them here, and then closed here because they don't belong here. Instead the original issue should be reopened if it doesn't belong here and the move was the wrong decision.

**Comment by rladuca** [comment] 2019-06-02 00:51
@weltkante Generally, these sorts of issues are with specific VS extensions (or VS itself) and not WPF.  The resource location schemes are usually fairly stable and we haven't made significant changes to these in .NET 4.8 that I am aware of (@miguep , I believe the last change you made might have been in 4.7.2?).  That's the source of my intuition that WPF is not, despite being on the stack, the specific root cause of this issue.  Of course that could be wrong, but VS teams are usually better placed to investigate from that context first and then forward to WPF.

I agree we shouldn't just close and move on and it wasn't my intent to suggest that's a good strategy.  What we normally do when we get these issues (prior to GitHub) is to bounce them to an appropriate VS team for a deeper triage.  Since the move to GitHub, this has started to be a little more complicated.  I cced @grubioe as he is the PM for WPF and the best situated to correctly get the issue back to those teams who need to look into it.

**Comment by grubioe** [comment] 2019-06-06 21:58
Hi all - 

It seems that the problems are specific to the bitbucket extension.  Please pose a question/raise an issue with the developer via this page:

https://marketplace.visualstudio.com/items?itemName=MistyK.VisualStudioBitbucketExtension 

Closing as external.

**Closed by grubioe** 2019-06-06 21:58 UTC
Labels: bug
