### ISSUE TITLE
The GenerateAssemblyInformationalVersionAttribute Property in csproj file doestn't work

### ISSUE THREAD

**Issue by chenyj796** [dotnet/wpf#295] opened 2019-01-28 03:22 UTC
* .NET Core Version: (3.0 Preview1)
* Windows version: (`windows 10`)
* Does the bug reproduce also in WPF for .NET Framework 4.6.1?: No

 
 
 **Problem description:**
I have an assembly attribute declaration as below:
``` csharp
[assembly: System.Reflection.AssemblyInformationVersion("some text")]
```
 
 **Actual behavior:** 
 build failed for report repeated AssemblyInformationVersionAttribute

 **Expected behavior:**
 success since I added the property in csproj file
``` csharp
<GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
```
 **Minimal repro:**

**Comment by stevenbrix** [comment] 2019-04-04 13:36
I don't have much history here, but this sounds like it might be by design? You were able to workaround it, correct?

cc @nguerrera, @ericstj

**Comment by vatsan-madhavan** [comment] 2019-04-04 14:49
Try setting `<GenerateAssemblyInfo>false</GenerateAssemblyInfo>` to prevent clashing with automatically generated ]assembly attributes](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateAssemblyInfo.targets)

This is not related to WPF directly  - I believe  this is a byproduct of adopting Sdk style projects.

**Comment by grubioe** [comment] 2019-04-19 21:50
@chenyj796 - I'm closing this as by design.  Please re-open if you feel otherwise

**Closed by grubioe** 2019-04-19 21:50 UTC
Labels: bug
