### ISSUE TITLE
The type 'x:Static' was not found

### ISSUE THREAD

**Issue by Symbai** [dotnet/wpf#117] opened 2018-12-07 14:57 UTC
* .NET Core Version: 3.0 Preview1
* Windows version: Windows 10 64bit, 1809
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No

This is a re-post of an issue posted in core, as its WPF related i believe it should be posted here instead https://github.com/dotnet/core/issues/2113 

 **Problem description:**

.NET core preview 1 doesn't accept x:static in xaml, where x is being defined as `xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"`
 
 **Actual behavior:** 

`XLS0414 The type 'x:Static' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built.`
 
 **Expected behavior:**

Works / no error like in framework
 
 **Minimal repro:**
 https://github.com/dotnet/core/files/2651359/CoreTest.zip
or:
```
<Window x:Class="CoreTest.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:CoreTest"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <Button ToolTip="{x:Static properties:Resources.PlayButtonTooltip}"/>
    </Grid>
</Window>
```

**Comment by karelz** [comment] 2018-12-07 16:13
@rladuca is it valuable to track this specific case separately? If it is just part of larger issue, I would mark it as dupe ...

**Comment by rladuca** [comment] 2018-12-07 16:31
Duplicate of #119

**Comment by rladuca** [comment] 2018-12-07 16:33
@Symbai Please track this in #119, so we can consolidate our xmlns issues.

Thanks!

**Closed** 2018-12-07 16:33 UTC
Labels: bug
