### ISSUE TITLE
The managed debugging assistant "FatalExecutionEngineError" has detected a problem when opening a new WPF window

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5635] opened 2021-11-05 15:51 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/The-managed-debugging-assistant-FatalEx/1421276)._

---
[severity:I'm unable to use this version]
Since today I get this error in **all my WPF** projects when I try to open a WPF window from code. There is no fixed line in the code where the error can be detected. I am not longer able to debug any WPF-project :-(

Have already done the following:
- Reinstalled VS 2019
- Deleted VS 2019 and installed VS 2017
- Deployed restore point
- Repaired .Net Framework

Nothing has helped. The error keeps coming back and looks like this:
The managed debugging assistant "FatalExecutionEngineError" has detected a problem in "xxxxxxxxx.exe".
For more information, see: The runtime has detected a fatal error. Error address: "0x7030f363" in thread "0x3ef4". Error code: 0xc00005. This error could be a problem in the CLR or in the unsafe or unverifiable parts of the user code. Common causes of this bug are Marshaller errors for COM interop or PInvoke, which can corrupt the stack.

Environment
- Windows 10 20H2 (german)
- Visual Studio 2017 (latest) / 2019 (latest)
- .Net Framework 4.8

Translated with www.DeepL.com/Translator (free version)

---
#### Feedback Bot on 5/12/2021, 06:21 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 9/5/2021, 08:15 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by singhashish-wpf** [comment] 2022-07-11 11:34
Is this reproducible in .NET6 and latest Visual Studio 2022 ?

**Comment by singhashish-wpf** [comment] 2023-02-08 05:28
Closing as no further details were provided since long time.

**Closed by singhashish-wpf** 2023-02-08 05:28 UTC
Labels: needs more information
