### ISSUE TITLE
Can not use a WPF Library (.NET 3.5) in a .net core 3.0 WPF Application

### ISSUE THREAD

**Issue by ms579984** [dotnet/wpf#1973] opened 2019-09-30 06:52 UTC
Hello,

I have the following problem:

I can’t use a third party WPF library (compiled for .NET 3.5) with a .net Core 3.0 WPF App. The compiler error message is:

error MC1000: Unknown build error, 'Could not find type ‘System.Collections.ObjectModel.ObservableCollection`1’ in assembly ‘C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\3.0.0\ref\netcoreapp3.0\WindowsBase.dll’.

or

error CS7069: Reference to type ‘ObservableCollection<>’ claims it is defined in ‘WindowsBase’, but it could not be found
### Example:

I attached a small example to reproduce the error message.
This example contains:
[WpfApp1.zip](https://github.com/dotnet/wpf/files/3669193/WpfApp1.zip)

1.  A .net Core 3.0 WPF Application project
2.  A .net 3.5 WPF UserControl project
3.  The UserControl has public property with a ObservableCollection<>.
4.  The WPF Application uses the UserControl and want to access the public property -> Compile error.

If I switch the .NET 3.5 Project to at least 4.0 everythings compiles as excepted.

```
public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            WpfControlLibrary1.UserControl1 c = new WpfControlLibrary1.UserControl1();
            c.items.Add(1);
        }
    }
```

```
public partial class UserControl1 : UserControl
    {
        public UserControl1()
        {
            InitializeComponent();
        }

        public ObservableCollection<int> items
        {
            get;
        } = new ObservableCollection<int>();
    }
```

### Background:

I’m trying to port our existing .net 4.7.2 application to .net core 3.0.
This application has a dependency to an old third party .net 3.5 WPF Assembly (I do not have source code of it and the company is out of business so there is no chance to get a newer version).
The rest of the application works very well but this is a show stopper.
I tested this with the current Visual Studio 2019 (16.3.1) on a fresh installed Win10 1903.

### Questions:

Is it intended that WPF 3.5 assemblies are not useable or is this a bug ?
Why is Type-Forwarding from WindowsBase to the real locations of types not working (the ObservableCollection<> has moved to the System-assembly) ?

Best Regards,
Marco Scholz

**Comment by weltkante** [comment] 2019-09-30 08:42
duplicate of #1964? (fix planned for 3.1)

**Comment by ms579984** [comment] 2019-10-01 05:24
Yes it seems to be the same issue.

**Comment by rladuca** [comment] 2019-10-07 19:05
Closing as a duplicate

**Closed by rladuca** 2019-10-07 19:05 UTC
