### ISSUE TITLE
French Canadian Keyboard Layout "}" key being swallowed by WPF ListView

### ISSUE THREAD

**Issue by dan-roboticarm** [dotnet/wpf#7641] opened 2023-03-18 10:01 UTC
### Description

When a TextBox is inside a ListView in WPF, the "}" can't be used if the Keyboard Layout is French Canadian. This key is on Right-Alt (or Alt Gr)+< (on a US Keyboard it is the backslash/pipe key). Other key combinations on Right-Alt work fine. 

### Reproduction Steps

1) Insert the following XAML code into MainWindow.xaml:

```
<Grid>
    <Grid.RowDefinitions>
        <RowDefinition Height="Auto"/>
        <RowDefinition Height="Auto"/>
        <RowDefinition/>
        <RowDefinition/>
    </Grid.RowDefinitions>
    <ListView Grid.Row="0">
        <ListView.Items>
            <TextBox Width="300"></TextBox>
        </ListView.Items>    
    </ListView>
    <TextBox Grid.Row="1" HorizontalAlignment="Left" Width="300"></TextBox>
</Grid>
```
2) Build and run.
3) Switch the built in Keyboard settings in Windows to the French Canadian layout
4) Try typing "}" into the TextBox outside of the ListView.
5) Try typing "}" into the TextBox inside of the ListView. 
6) Switch Keyboard layouts to the US layout.
7) Try typing "}" into the TextBox inside of the ListView. 

### Expected behavior

The "}" key should be usable in a Textbox whether that TextBox is inside of a ListView or not, regardless of the keyboard layout.

### Actual behavior

When typing "}" into the TextBox outside of the ListView, the Textbox updates appropriately. 
When typing "}" into the TextBox inside of the ListView, nothing happens if the Keyboard layout is the French Canadian layout.
When typing  "}" into the TextBox inside of the ListView, it updates appropriately if the Keyboard layout is the US layout.

### Regression?

Unknown.

### Known Workarounds

For End Users, switch keyboard layouts.
For a code workaround, maybe handling the PreviewKeyDown event and directly updating the Textbox before it gets to the ListView.

### Impact

It only impacts people who use a French Canadian keyboard layout when typing a specific character into a Textbox, but it may affect others with extended characters on Right-Alt in their keyboard layouts.

### Configuration

Which version of .NET is the code running on? .NET 7.0
What OS and version, and what distro if applicable? Windows 11
What is the architecture (x64, x86, ARM, ARM64)? x64
Do you know whether it is specific to that configuration? I don't believe so.

### Other information

ListView appears to be marking the KeyPress event as handled, therefore it never gets back to TextBox as a TextInput event.

**Comment by miloush** [comment] 2023-03-18 12:25
This is the culprit:

https://github.com/dotnet/wpf/blob/5d596bd99a06466c7b7aa67f7f66b108abad809a/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ListBox.cs#L333-L335

And similarly, the dead key next to shift will not work on CAFR layout:

https://github.com/dotnet/wpf/blob/5d596bd99a06466c7b7aa67f7f66b108abad809a/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ListBox.cs#L320-L322

This obviously causes similar issues on other keyboard layouts as noted.

The code does check only for Ctrl present, not the suggested shortcuts. This could be fixed by making sure _only_ Ctrl is pressed, i.e. removing the mask, which would preserve the intended behaviour yet still allow keyboards to type.

(You can also see that if you set the selection mode to anything else than extended, it will start working agiain.)

**Closed** 2023-06-28 09:11 UTC
Labels: Investigate
