### ISSUE TITLE
Using a BackgroundVisualHost causes a crash in WPF (example repo available)

### ISSUE THREAD

**Issue by scalablecory** [dotnet/wpf#2276] opened 2019-12-04 18:39 UTC
_From @adscott1982 on Tuesday, December 3, 2019 5:04:20 PM_

Showing / hiding UI on a non-main thread dispatcher will cause WPF to crash.

This problem is present on .NET Core 3.0, Framework 4.8, 4.7.2 and 4.7.0 and perhaps others.

Using the technique in the following blog post used to work, but will now eventually cause a crash in WPF:

http://gettinggui.com/creating-a-busy-indicator-in-a-separate-thread-in-wpf/

This issue has only been seen since around September 2019.

A repo demonstrating the issue is here, and will usually cause the issue within a couple of minutes:

https://github.com/adscott1982/BackgroundUIThreadError

My system is:

Windows 10 Professional 1909
Visual Studio 2019 Professional
Nvidia Quadro P400

There are various different exception messages that will be shown when the issue presents itself. I will gather up as many as I can and attach them as text files.

[Catastrophic failure.txt](https://github.com/dotnet/core/files/3917794/Catastrophic.failure.txt)
[internal error in the dot net runtime.txt](https://github.com/dotnet/core/files/3917810/internal.error.in.the.dot.net.runtime.txt)
[render thread failure.txt](https://github.com/dotnet/core/files/3917837/render.thread.failure.txt)
[missing end command.txt](https://github.com/dotnet/core/files/3917839/missing.end.command.txt)

_Copied from original issue: dotnet/core#3948_

**Comment by AdamCaviness** [comment] 2020-09-25 15:29
We are hitting this as well. We have to use the BackgroundVisualHost because the main dispatcher must create controls on screen and that can take quite a while of course. Without something like the approach demonstrated, WPF apps can't appear responsive. We are on .NET Core 3.1 at present but we also experienced it in Framework 4.7.2 and 4.8.

**Comment by PhysShell** [comment] 2022-11-18 06:35
Hi. We're also experiencing this issue. Has anyone managed to found a workaround? @AdamCaviness?

**Comment by PhysShell** [comment] 2022-11-22 12:38
As a quick temporary fix we replaced this control with DXSpashScreen from Devexpress which our app is based on, it covers our use cases.

**Comment by Kuldeep-MS** [comment] 2023-03-23 09:33
UPDATE- I have taken a look at the code of repro app and found that if we simply add null check for `Application.Current` it resolves the [issue](https://github.com/dotnet/wpf/issues/2276#issuecomment-1477763789)
see the code below: 
```
this.decoratorTimers.Add(new Timer(o =>
            {
                Application.Current?.Dispatcher?.Invoke(
                    () =>
                    {
                        this.Decorator4.IsBusyIndicatorShowing = !this.Decorator4.IsBusyIndicatorShowing;
                    });
            },
                null,
                (int)(this.random.NextDouble() * 100) + 100,
                (int)(this.random.NextDouble() * 100) + 100));
```
@adscott1892 - Let me know if I missed anything too look at?

**Comment by Kuldeep-MS** [comment] 2023-03-23 10:07
@adscott1982 - Thanks for your reply. We are closing the issue as it is not reproducible.
We can reopen the issue when repro app is available.

**Closed by Kuldeep-MS** 2023-03-23 10:07 UTC
Labels: Bug
