### ISSUE TITLE
WPF app throws memory overflow on Windows 8 with a specific combo of StackPanel and images

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#3762] opened 2020-11-06 03:23 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/WPF-app-throws-memory-overflow-on-Window/870731)._

---
<p>I struggled with a memory overflow on a WPF app, happening only on Windows 8/8.1 - any installation (Win7 and Win10 worked fine).</p> <p>The app just crashed at start (when the app first displayed the main window), with a memory overflow exception, with presentation core as source.</p> <p>I found out that the problem only happened when two small images were both scaled high quality in the same panel:</p><pre>&lt;StackPanel Orientation=&quot;Horizontal&quot;&gt;
&lt;Image Source=&quot;.. \Images\Tools.png&quot; Width=&quot;24&quot; Height=&quot;24&quot; RenderOptions.BitmapScalingMode=&quot;HighQuality&quot;&gt;&lt;/Image&gt;
&lt;Image Source=&quot;.. \Images\DownArrow.png&quot; Width=&quot;8&quot; Height=&quot;8&quot; RenderOptions.BitmapScalingMode=&quot;Linear&quot;&gt;&lt;/Image&gt; &lt;!-- HighQuality scaling would crash on Windows 8 --&gt;
&lt;/StackPanel&gt;
</pre><p>Images are 64x64 PNGs, so there's no apparent reason for a memory problem. Using &quot;linear&quot; as scaling mode for one of the two imagines solved. Using a DockPanel instead of a StackPanel, for example, doesn't solve.</p> <p>The app was addressed to the Framework 4.6.1, and the installed framework was 4.8.03761.</p>

---
#### Feedback Bot on 1/2/2020, 11:32 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 2/7/2020, 11:32 AM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.

---
### Original Solutions
(no solutions)

**Comment by elyoh** [comment] 2021-02-08 22:25
* .NET Core Version: `.NET 5.0.2`
* Windows version: `Windows 8.1 6.3.9600`
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes

 **Problem description:**
Some 8-bit png images cause out of memory exception in PresentationCore when combined with `RenderOptions.BitmapScalingMode="HighQuality"`

 **Actual behavior:** 
Displaying some 8-bit png images cause out of memory exception in PresentationCore.

One suspected stack trace:
```
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at System.Windows.Media.Imaging.TransformedBitmap.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapSource.CompleteDelayedCreation()
   at System.Windows.Media.Imaging.BitmapSource.get_WicSourceHandle()
   at System.Windows.Media.Imaging.BitmapSource.CopyCommon(BitmapSource sourceBitmap)
   at System.Windows.Media.Imaging.BitmapImage.CloneCore(Freezable source)
   at System.Windows.Freezable.Clone()
```
 **Expected behavior:**
Image loads as expected.

 **Minimal repro:**
[ImageBug [08-02-2021 22-03].zip](https://github.com/dotnet/wpf/files/5947146/ImageBug.08-02-2021.22-03.zip)
[ImageBugNet5 [08-02-2021 22-04].zip](https://github.com/dotnet/wpf/files/5947147/ImageBugNet5.08-02-2021.22-04.zip)

I can reliably reproduce when running on Windows 8.1 (only) with latest .NET 5.0 and .NET 4.8.

The repros include 3 valid png images.
`Images\8bit_crash.png` gives issue.
`Images\8bit.png` does not.
`Images\24bit.png` does not.

I can can sometimes avoid the error by adding a `24bit.png` image on the same view.

`8bit_crash.png` was created in paint.net.  I have other 8-bit png files from a range of sources which cause the same issue .  The issue started appearing sporadically in telementy in November 2020.  I have not been able to narrow it down to a specific OS update.

The only solution I have found is to avoid using 8-bit png images, or use an alternative `BitmapScalingMode` as suggested above.

**Comment by ryalanms** [comment] 2021-02-08 23:09
Thank you for the report and repro projects, @elyoh.  We will review this again in triage.

**Comment by SamBent** [comment] 2021-02-17 01:21
WPF asks WIC (the OS imaging component, WindowsCodecs.dll) to do the actual work of scaling the image to the desired size.  The error comes from IWICBitmapScaler::Initialize returning E_OUTOFMEMORY.  This only happens on Win8.1, and not if you've included the 24-bit .png.  This feels like a WIC bug, not WPF;  I've asked the WIC team for help.

BTW, I see the issue using Images\8bit.png, contrary to @elyoh remark.

**Comment by elyoh** [comment] 2021-02-17 09:29
> BTW, I see the issue using Images\8bit.png, contrary to @elyoh remark.

This difference chimes with what we are seeing (an in production app with many 8-bit image assets works perfectly when testing on Windows 8.1, but crashes on some client machines).  I wonder if some aspect of the issue is hardware related.

**Comment by SamBent** [comment] 2021-02-18 19:07
The WIC team confirms this is a known regression in Windows 8.1, fixed in Win10.  It has to do with initializing WIC's internal format converter.  The codepath through IWICBitmapScaler::Initialize doesn't do the lazy initialization, and thus returns E_OUTOFMEMORY if it needs to convert the bitmap's pixel format before scaling it, unless the format converter has been previously initialized for some other reason.

Including a 24-bit png works around the WIC bug, because WPF asks WIC to convert the bitmap to a format that the WPF render thread supports.  This does the necessary initialization.

**Comment by SamBent** [comment] 2021-02-18 23:45
This isn't a WPF issue.  Closing.

**Closed by SamBent** 2021-02-18 23:45 UTC
Labels: .NET Framework, Bug, Investigate

**Comment by ADNALYTICS** [comment] 2021-11-25 12:26
Is it possible that this error also occurs on Windows Server 2012 R2 (Windows 6.3.9600) ?
