### ISSUE TITLE
A11y_.NETWPF_ExpenseItIntro_View Expense Report_Zoom: When zooming to 200% the "names" title and the view button is getting truncated.

### ISSUE THREAD

**Issue by Blessymanna** [dotnet/wpf#5044] opened 2021-08-09 07:09 UTC
[Check out Accessibility Insights!]([url](url)) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

GitHubTags:#A11yMAS;#A11ySev2;#A11yTCS;#A11yWCAG;#DesktopApp;#WCAG1.4.4;#DesktopApp;#Win10;#BM-.NetCore(WPF)-Win32-July2021;#.NET Core;#Benchmark;

### Environment details:
Application Name: .NET Core WPF
Microsoft .NET Core SDK Version 6.0.100-rc.1.21380.2
Windows Version: Windows10

### Repro Steps
Launch VS 2019 Int Preview
Navigate to Getting started and right click on the Expense it intro and click on build
Then right click on Expense it Intro then Click on Debug-->Start New Instance.
Check after zooming to 200%, the names title and the view button is visible as it is or not.
### Actual Result:
After zooming to 200%, the names title and the view button is getting truncated.

### Expected Result:
After zooming to 200%, the names title and view button should not get truncated.

### User Impact:
The users with low vision, not able to view the complete information.

**Comment by singhashish-wpf** [comment] 2021-08-20 11:45
@Blessymanna I couldn't reproduce the issue. Could you please help to share the screenshot of your repro?
Also, I am zooming via windows+ '+' (Magnifier)

**Comment by merriemcgaw** [comment] 2021-09-08 18:46
@singhashish-wpf please put an image in here to show the "Make Everything Bigger" setting is what works appropriately on this sample app. 

Then please close this issue as not really a bug. If the testers come back to you please send mail to me, Ryan Shugart and Scott O'Hara and we'll get it figured out for you.

**Comment by singhashish-wpf** [comment] 2021-09-09 06:14
@merriemcgaw the issue is reproducible with Make Everything Bigger. I'll be fixing it soon.

**Comment by singhashish-wpf** [comment] 2021-09-09 06:33
This is an issue in the WPF Sample App(https://github.com/microsoft/WPF-Samples/).
PR https://github.com/microsoft/WPF-Samples/pull/403
For bugs in WPF Sample Apps, please register the bugs in the sample apps repo (https://github.com/microsoft/WPF-Samples)

**Comment by singhashish-wpf** [comment] 2021-09-09 09:44
Fix PR https://github.com/microsoft/WPF-Samples/pull/403

Please use the latest Sample App from the WPF Sample App repo during next testing. it'll include the fix.

**Closed by singhashish-wpf** 2021-09-09 09:44 UTC
Labels: Accessibility, issue-type-tracking-external

**Comment by merriemcgaw** [comment] 2021-09-09 21:31
Just an FYI that I don't think the testers will know if it's a WPF bug or an app bug, we've run into that every time. So I'd suggest either duplicating the Issue in the samples, or just leaving it here for their tracking.

**Comment by Blessymanna** [comment] 2021-09-16 09:03
@merriemcgaw We reverified this issue with "Make everything bigger" and this issue is not reproducing anymore. Providing screenshot for reference.
![Screenshot (174)](https://user-images.githubusercontent.com/88525506/133583556-13fd2832-b383-489d-baed-f058e5209ced.png)
