### ISSUE TITLE
XamlLoadPermission.FromXml for element without `class` attribute throws NRE

### ISSUE THREAD

**Issue by hughbe** [dotnet/wpf#191] opened 2018-12-18 21:24 UTC
```cs


[Fact]
public void FromXml_NoClassAttribute_ThrowsArgumentException()
{
    var permission = new XamlLoadPermission(PermissionState.None);
    var elem = new SecurityElement("IPermission");
    Assert.Throws<ArgumentException>("elem", () => permission.FromXml(elem));
}
```

Expected: throws `ArgumentException`
Actual: throws `NullReferenceException`

**Comment by stevenbrix** [comment] 2019-04-04 18:53
@hughbe is this a dup of #213?

**Comment by grubioe** [comment] 2019-04-11 21:44
Closing as duplicate of 213

**Closed by grubioe** 2019-04-11 21:44 UTC
