### ISSUE TITLE
WPF Style not apply if it one in list

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#5760] opened 2021-11-29 23:35 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/WPF-Style-not-apply-if-it-one-in-list/1159563)._

---
[severity:I'm frustrated, but able to complete my work]
When i make siple WPF application with page navigation

When i use App.xaml.cs to navigate first page is want see label with red background

protected override void OnStartup(StartupEventArgs e)
    {
        var navigationWindow = new NavigationWindow
        {
            Content = new Page1(),
            ShowsNavigationUI = false,
        };

navigationWindow.Show();

base. OnStartup(e);
    }

And apply one style in App.xaml - it not work!

<Application.Resources>
    <Style TargetType="Label">
        <Setter Property="Background" Value="red" />
    </Style>
</Application.Resources>

When apply two or more styles - it work

<Application.Resources>
    <Style TargetType="Label">
        <Setter Property="Background" Value="red" />
    </Style>
    
<Style TargetType="Button">
        <Setter Property="Background" Value="red" />
    </Style>
</Application.Resources>

---
#### Feedback Bot on 8/23/2020, 07:14 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 12/2/2020, 06:45 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by singhashish-wpf** [comment] 2022-06-28 11:55
We are unable to reproduce this with the description provided on .NET6/VS2022. Hence closing this.

**Closed by singhashish-wpf** 2022-06-28 11:55 UTC
