### ISSUE TITLE
SDK-style WPF Projects targeting net472 are broken because ImportFrameworkWinFXTargets is false

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/wpf#4515] opened 2021-05-13 21:35 UTC
This PR has regressed building WPF projects that use the SDK-style:
https://github.com/dotnet/wpf/pull/2976

By default ImportFrameworkWinFXTargets was `true`, but now changes to `false`, resulting in MarkupCompile not running.

FYI @Nirmal4G

**Comment by KirillOsenkov** [comment] 2021-05-13 21:51
so just upgrading the SDK from 5 to 6 will break the build in a very confusing way

**Comment by Nirmal4G** [comment] 2021-05-14 02:06
Even if it is set as `true`, the .NET SDK should reset it to `false` based on the `TargetFramework`. Let me take a look…

**Comment by KirillOsenkov** [comment] 2021-05-14 02:24
It wasn't set to anything in my codebase, and setting it to true in my `Directory.Build.props` fixed it.

Just create a new SDK-style .csproj, target `net472` only, add some WPF references (PresentationCore, PresentationFramework, System.Xaml and WindowsBase), create a new Application and Window in Main() and build.

**Comment by KirillOsenkov** [comment] 2021-05-14 02:25
This is the line that sets it to false (whereas otherwise it is true for me):
https://github.com/dotnet/wpf/pull/2976/files#diff-5827fafdcece80f275068609904789952b21a8e75ae7b3fcb6b0fd39b3d0d0b5R171

**Comment by vatsan-madhavan** [comment] 2021-05-14 02:27
IIRC WPF SDK was using the SDK’s WinFx props/Targets (it has a props too), PresentationBuildTasks etc even when building NetFx targets. That has been the behavior since sometime in 3.x. NetFx targets do not use NetFx’s copy of targets or tasks. 

Not sure if the regression implicates this or not but figured I’d put this out there to help with the investigation. 

See #2075

**Comment by Nirmal4G** [comment] 2021-05-14 03:32
In .NET SDK's [`BeforeCommon.targets`][File] These [Lines 49-56][Code] reset it to `true` when targeting `.NETFramework` but doesn't do that! since, we set this in `props` in the Windows Desktop SDK. So, the solution here is, either move the setting in the `WindowsDesktop.props` to `Sdk.props` or update the SDK logic to handle this case.

_I recommend we move the setting to `Sdk.props` to preserve it's intended behavior—as it was meant be used only when using the Windows Desktop SDK directly_. My PR was supposed to be merged before the v5 refactoring but was delayed. Meanwhile, I didn't know the logic was being updated in the Main SDK during that time.

If it's okay with the team, I can go ahead and open a PR.

[File]: https://github.com/dotnet/sdk/blob/release/5.0.3xx/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets
[Code]: https://github.com/dotnet/sdk/blob/release/5.0.3xx/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets#L49-L56

**Comment by Nirmal4G** [comment] 2021-05-14 03:51
In .NET SDK's [`BeforeCommon.targets`][File] These [Lines 49-56][Code] reset it to `true` when targeting `.NETFramework` but doesn't do that! since, we set this in `props` in the Windows Desktop SDK. So, the solution here is, either remove the setting from the `WindowsDesktop.props` which may break projects or move the setting to `Sdk.props` and update the Main SDK logic to handle this case.

_I recommend we move the setting to `Sdk.props` to preserve it's intended behavior—as it was meant be used only when using the Windows Desktop SDK directly_. My PR was supposed to be merged before the v5 refactoring but was delayed. Meanwhile, I didn't know the logic was being updated in the Main SDK during that time.

I can go ahead and open a PR on what the team recommends.

[File]: https://github.com/dotnet/sdk/blob/release/5.0.3xx/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets
[Code]: https://github.com/dotnet/sdk/blob/release/5.0.3xx/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets#L49-L56

**Comment by KirillOsenkov** [comment] 2021-05-14 04:30
No worries at all, it’s hard not to break MSBuild and we do it all the time. Welcome to the club! And thanks for looking into this.

**Comment by vatsan-madhavan** [comment] 2021-05-14 04:32
@dsplaisted fyi

**Comment by dsplaisted** [comment] 2021-05-14 15:54
Yeah, it made sense to set this to false in WindowsDesktop.props when that was only imported if the project was explicitly using Microsoft.NET.Sdk.WindowsDesktop.  But now we always import that props file.

You could move it to the WindowsDesktop Sdk.props file, I think that would work in both situations.

**Comment by ryalanms** [comment] 2021-06-03 19:27
We need to fix this.  @Nirmal4G:  Are you going to create a PR or should someone from the WPF get it?  Thanks.

**Comment by Nirmal4G** [comment] 2021-06-04 13:56
For now, Moving the logic to the `SDK.props` should work but a long-term fix should be fixing the .NET Framework's WinFX targets and tasks that ships with the SDK!

**Closed** 2021-06-04 16:01 UTC
Labels: Bug
