### ISSUE TITLE
WPF Surface 2.0 SDK (open source)

### ISSUE THREAD

**Issue by Noemata** [dotnet/wpf#8696] opened 2024-01-18 03:08 UTC
I have asked about this before, but so far, several years later, this is still unresolved.  Will the WPF Surface 2.0 SDK source code be made available?

If not, would Microsoft permit a GitHub repo containing the reverse engineered version of the Surface 2.0 SDK DLLs instead?

If the latter is not to be permitted, could the reasons be outlined?

Given that C# DLLs are easily reverse engineered, what is Microsoft's official position on significant legacy DLLs such as the above since there was a time Microsoft prohibited reverse engineering some of these components.  Without allowing reverse engineering of such components, many essential legacy tech items remain trapped inside Microsoft with no path forward for enhancement, fixes and modernization.

The Surface 2.0 SDK had some very useful components that are still relevant to present day WPF applications.  ScatterView is one such essential component.

**Comment by Symbai** [comment] 2024-01-19 01:03
You have already opened an issue for this: #118 if everyone would create another issue because he doesn't get a reply this repo would be full of duplicates everywhere. Trust me, I'm not happy about my issues and PRs are being ignored as well. But as other people don't do this I think it would just be fair if you don't do it as well.

**Comment by lindexi** [comment] 2024-01-19 02:58
Closing as duplicate of https://github.com/dotnet/wpf/issues/118

**Closed by lindexi** 2024-01-19 02:58 UTC
Labels: Untriaged
