### ISSUE TITLE
WPF Textbox work abnormally when IME is Chinese Simplified(Microsoft Pinyin)

### ISSUE THREAD

**Issue by lisalisal** [dotnet/wpf#6194] opened 2022-03-02 11:45 UTC
* .NET Core Version: .Net 5.0
* Windows version: Version 2004(OS build 19041.1415)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No.
 
Issue description:
1.New a wpf textbox with data binding, data bidding is like:
TextBox Text="{Binding Path=InputText,UpdateSourceTrigger=PropertyChanged}"

2.Choose 'Chinese(Simplified China) Microsoft Pinyin' as IME .
3.Enable 'Use previous version of Microsoft Pinyin', please refer attached video 'use_previous_version.mov' for detailed steps.
4.Input serval chars like 'qwert', then Chinese IME popup, click '2' to select '请问让'.  '请问让' is corresponding to 'qwer', and then choose '2' for left char 't', then the issue happens. Could refer attached video 'textbox_lost_chinese_chars.mov' for details

Excepted result:
'请问让她' should be present in textbox.

Actual result:
only '她' is in textbox. the previous chinese chars '请问让' are missing.

 Investigation:
1. If disable 'Use previous version of Microsoft Pinyin', the issue won't happen. 
2. Remove 'UpdateSourceTrigger=PropertyChanged' in TextBox binding, the issue won't happen. 
Attach my test project 'wpfapp8.zip' 

Attached files:
1. 'use_previous_version.mov' for enabling 'Use previous version of Microsoft Pinyin'
2. 'textbox_lost_chinese_chars.mov' for issue
3. 'wpfapp8.zip' is simple textbox test code4. 
[WpfApp8.zip](https://github.com/dotnet/wpf/files/8169258/WpfApp8.zip)
https://user-images.githubusercontent.com/89184738/156355305-b6cdf349-96ce-4a25-9542-fc538e5c2da6.mov
https://user-images.githubusercontent.com/89184738/156355411-f648df27-4bd9-4c32-b670-aa9ced73d9bd.mov

**Comment by lindexi** [comment] 2022-03-03 00:51
It seems like the IME issues.

**Comment by lisalisal** [comment] 2022-03-03 07:09
@lindexi Could I know which win32 application you tried also has the same issue? We tried notepad and search box of file explorer, don't hit this issue.

**Comment by lindexi** [comment] 2022-03-03 07:11
@lisalisal NodPad++ SublimeText Edge and so on. 

但非必现

各个版本的 Windows 修了又修，修了又修……

**Comment by lindexi** [comment] 2022-03-03 07:14
Could you try use the thired part Pinyin, just like *QQ Pinyin* or *Sougou input* ?

如果尝试用搜狗，然后什么都正常，那么证明是微软拼音投毒。否则就是应用的锅

**Comment by miloush** [comment] 2022-03-07 18:39
I can reproduce the behaviour.

The difference between the legacy and new IME is that the legacy IME commits the first part of the string and then starts a new composition with the remaining "t" character. The new IME only commits the full thing.

This would normally not be a problem, except that a two-way binding on property changed is used, so once the first part is committed, the remaining composition is cancelled because new value is set as TextBox.Text.

### Legacy:

|Event|TextComposition.CompositionText|TextComposition.Text|TextBox.Text|
|---|---|---|---|
|Source property GET|return
|**Preview+TextInputStart**|||
|Preview+TextInputUpdate|q||
|Preview+TextInputUpdate|q'w||q
|Preview+TextInputUpdate|q'we||q'w
|Preview+TextInputUpdate|q'we'r||q'we
|Preview+TextInputUpdate|q'we'r't||q'we'r
|Preview+TextInputUpdate|去微软||q'we'r't
|PreviewTextInput||去微软|去微软
|Source property SET|value = 去微软
|Source property GET|return 去微软|
|Source property SET|value = 去微软
|**Preview+TextInputStart**|||去微软
|Preview+TextInputUpdate|t||去微软
|Source property GET|return 去微软|this kills composition
|Preview+TextInputUpdate|太||去微软
|PreviewTextInput||太|太
|Source property SET|value = 太
|Source property GET|return 太
|Source property SET|value = 太
|Source property GET|return 太

I am leaning towards this being a bug on the WPF side. The GET-SET pairs should not be interruptible by other events. It is also not clear to me why there needs to be a second SET since the first GET returned the expected value.

### New:

|Event|TextComposition.CompositionText|TextComposition.Text|TextBox.Text|
|---|---|---|---|
|Source property GET|return
|**Preview+TextInputStart**|||
|Preview+TextInputUpdate|q||
|Preview+TextInputUpdate|q'w||q
|Preview+TextInputUpdate|q'we||q'w
|Preview+TextInputUpdate|q'we'r||q'we
|Preview+TextInputUpdate|q'we'r't||q'we'r
|Preview+TextInputUpdate|去微软t||q'we'r't
|Preview+TextInputUpdate|去微软太||去微软t
|Source property SET|去微软太
|PreviewTextInput||去微软太|去微软太
|Source property SET|value = 去微软太
|Source property GET|return 去微软太
|Source property SET|value = 去微软太
|Source property GET|return 去微软太

On this one I am confused about PreviewTextInput firing _after_ the text property is changed, shouldn't that be before, like in the previous case, so that it the handler has a chance to do something about it?

**Comment by lisalisal** [comment] 2022-03-09 05:57
Duplicated to https://github.com/dotnet/wpf/issues/5444.
Update to dotnet 6.0.3.can resolve this issue.

**Closed** 2022-03-09 05:57 UTC
Labels: needs more information

**Comment by lindexi** [comment] 2022-03-09 13:05
soga原来说的是这个锅哇…… 不好意思

**Comment by miloush** [comment] 2022-03-09 14:45
I confirm the original issue does not reproduce in 6.0.3. There is now a hidden exception if the composition text is longer than the text set through property, caused by `ITextStoreACP.GetTextExt`. Also the binding is still set before PreviewTextInput in the latter case, but these separate issues.
