### ISSUE TITLE
ElementHost Null Reference Exception in ProcessCmdKey

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/wpf#649] opened 2019-05-03 19:15 UTC
I am using WindowsFormsIntegration.dll version 4.8.3752.0 and getting a Null Ref Exception in the ElementHost.cs. I included a simple solution which reproduces this bug in the attached Zip file.

If you look at my attachment of the decompiled source (processcmdkey.png) I will explain what happens:

I have an ElementHost which is contained on a Winform Container Control in a Winforms Application. The ElementHost contains a WPF UserControl so it looks something like this:

WinformsApplication
   ContainerControl
      ElementHost
         Wpf.UserControl

If I press the ESC key, ProcessCmdKey is called on the ElementHost. When ProcessCmdKey gets to line 369, it allows the key press to be processed by the application. The ESC key is caught by the Cancel Button on the Wpf.UserControl which calls Dispose on the ContainerControl, which also Disposes of the ElementHost.

ProcessCmdKey then goes on to line 370 and throws an exception because _hostContainerInternal is now NULL because the ElementHost was disposed.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/553929/elementhost-null-reference-exception-in-processcmd.html
VSTS ticketId: 860777_
_These are the original issue comments:_

Visual Studio Feedback System on 5/1/2019, 09:57 PM (38 hours ago): We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.

_These are the original issue solutions:_
(no solutions)

**Comment by GLantaff** [comment] 2019-05-16 15:08
Does this bug have any priority? I'm concerned because when Windows 10 - 1903 ships (which includes version of .NET framework that includes this bug), our existing application will start getting exceptions. If fix will take a while, we need to notify users to not update OS.

**Comment by grubioe** [comment] 2019-06-11 18:26
Closing as duplicate of #898

**Closed by grubioe** 2019-06-11 18:26 UTC
Labels: bug

**Comment by EngAJ** [comment] 2019-07-11 16:12
Is this fix available or is there any release date for this fix?
Is there any workaround?


We already had two customers that updated and the issue remains after the last Cumulative Update for .NET.

**Comment by GLantaff** [comment] 2019-07-18 19:44
Any ETA on getting this fix released? This makes our released software look really bad.

**Comment by weltkante** [comment] 2019-07-18 20:34
You are asking on an issue closed as duplicate, there's probably nobody listening on it

/cc @vatsan-madhavan @rladuca @SamBent from #898 which had the fix
