### ISSUE TITLE
Merging Avalonia with WPF

### ISSUE THREAD

**Issue by TeddyAlbina** [dotnet/wpf#265] opened 2019-01-16 00:41 UTC
After a lot of code reading i think it's possible to merge Avalonia with Wpf code to produces a cross platform standardized UI for .net core. 

It's someone interested to start ?

**Comment by lindexi** [comment] 2019-01-17 01:17
I do not think this is a good idea.

**Comment by karelz** [comment] 2019-01-17 01:47
Seems to be covered already here: #59. I'd suggest to close it as duplicate ...

**Comment by stevenbrix** [comment] 2019-04-04 04:12
Duplicate of #59

**Closed by stevenbrix** 2019-04-04 04:12 UTC
Labels: question
