### ISSUE TITLE
Check if _child is null in TemplatedAdorner.MeasureOverride

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/wpf#234] opened 2019-01-04 11:37 UTC
No null check [here](https://referencesource.microsoft.com/#PresentationFramework/src/Framework/MS/Internal/Controls/TemplatedAdorner.cs,143) is weird given that there is a null check [here](https://referencesource.microsoft.com/#PresentationFramework/src/Framework/MS/Internal/Controls/TemplatedAdorner.cs,166)

From reference source:
```cs
        /// <summary>
        /// Measure adorner.
        /// </summary>
        protected override Size MeasureOverride(Size constraint)
        {
            Debug.Assert(_child != null, "_child should not be null");
 
            if (ReferenceElement != null && AdornedElement != null &&
                AdornedElement.IsMeasureValid &&
                !DoubleUtil.AreClose(ReferenceElement.DesiredSize, AdornedElement.DesiredSize)
                )
            {
                ReferenceElement.InvalidateMeasure();
            }
 
            (_child).Measure(new Size(Double.PositiveInfinity, Double.PositiveInfinity));
 
            return (_child).DesiredSize;
        }
 
 
 
        /// <summary>
        ///     Default control arrangement is to only arrange
        ///     the first visual child. No transforms will be applied.
        /// </summary>
        protected override Size ArrangeOverride(Size size)
        {
            Size finalSize;
 
            finalSize = base.ArrangeOverride(size);
 
            if (_child != null)
            {
                    _child.Arrange(new Rect(new Point(), finalSize));
            }
            return finalSize;
        }
```

Did a search and did not find `TemplatedAdorner` in the repo.

Repro:
Resize the window with the below markup:
```
<DataGrid ItemsSource="{Binding People}">
    <DataGrid.RowStyle>
        <Style TargetType="DataGridRow">
            <Setter Property="adorners:Info.Template">
                <Setter.Value>
                    <ControlTemplate>
                        <Border BorderBrush="HotPink"
                                BorderThickness="3">
                            <AdornedElementPlaceholder />
                        </Border>
                    </ControlTemplate>
                </Setter.Value>
            </Setter>
        </Style>
    </DataGrid.RowStyle>
</DataGrid>
```

**Comment by stevenbrix** [comment] 2019-01-04 17:19
@JohanLarsson the source code for PresentationFramework hasn't been opened yet. Once the infrastructure is ready to do so, this looks like something that could be fixed.

**Comment by JohanLarsson** [comment] 2019-01-04 17:38
Ok, np, just wrote the issue as a reminder.

**Comment by daniel-loudon** [comment] 2019-01-18 15:39
I would like to take this as a first issue.

**Comment by karelz** [comment] 2019-01-18 19:04
Great @daniel-loudon, thanks!
I just sent you collaborator invite - that way we can assign the issue to you (assigning temporarily to myself). Ping me when you accept the invitation.
Let us know if you need any help.

**Comment by karelz** [comment] 2019-01-18 19:05
Oh, wait. I just read the thread and it seems the code is not open-sourced yet - is that right @stevenbrix? In that case, we should not mark the issue as up-for-grabs as it is not ready for contributors yet.
Can you please confirm?

**Comment by stevenbrix** [comment] 2019-01-18 19:16
@karelz that's correct, i'll remove up-for-grabs. @daniel-loudon, it's yours when the source is available!

**Comment by karelz** [comment] 2019-04-09 15:48
@stevenbrix @vatsan-madhavan is the code open-sourced now? If yes, we can add the up-for-grabs again ;) ... I bet there are few community members who will be interested in helping out :)

**Comment by stevenbrix** [comment] 2019-04-09 17:10
@karelz unfortunately not yet. we don't have exact dates yet, but we should be able to start getting to this soon.

**Comment by siegfriedpammer** [comment] 2021-07-29 17:13
As the relevant code is now open sourced, would you accept contributions that fix this issue? Also, will this be part of .NET 6 or 7, if fixed in the near future? Thanks!

**Comment by harshit7962** [comment] 2023-10-04 06:45
@JohanLarsson is this bug still reproducing? Coz I am unable to reproduce this on my end.

**Closed** 2023-10-25 07:01 UTC
Labels: Bug, Good First Issue, :mailbox_with_no_mail: waiting-author-feedback, :zzz: no-recent-activity
