### ISSUE TITLE
.NET6  "ToolTip " property display exception

### ISSUE THREAD

**Issue by xwang-888** [dotnet/wpf#6497] opened 2022-04-29 05:52 UTC
Tooltip this property will disappear after flashing once when the mouse moves in.
But downgrade the project to Display normally after net5.
![image](https://user-images.githubusercontent.com/56998197/165891132-71a8bee3-f877-4961-a263-5e1ac0fb2bbc.png)

**Comment by gurpreet-wpf** [comment] 2022-04-29 07:09
Closing this as a dupe of #6220. This will be resolved in next release.

**Closed by gurpreet-wpf** 2022-04-29 07:09 UTC
