### ISSUE TITLE
Consider shipping System.Xaml as a separate netstandard package

### ISSUE THREAD

**Issue by ryalanms** [dotnet/wpf#4140] opened 2021-02-05 19:44 UTC
System.Xaml can be used independently of WPF, but consuming System.Xaml requires building with the Windows-specific `net6.0-windows` target framework.  Consider shipping System.Xaml as a separate netstandard package that can be built without the Windows-specific TFM.

**Comment by lindexi** [comment] 2021-02-06 00:51
Yeah, and I made it as a separate package in https://github.com/lindexi/lindexi_gd/tree/master/System.Xaml

**Comment by lindexi** [comment] 2021-03-08 11:33
@ryalanms Because System.Xaml depends on System.Windows.Extensions, I cannot change it to netstandard. See https://github.com/dotnet/wpf/pull/4252

**Comment by lindexi** [comment] 2021-07-03 01:41
See https://github.com/dotnet/wpf/issues/3543

**Comment by AArnott** [comment] 2022-09-19 17:08
Looks like a dupe of #46

**Comment by pchaurasia14** [comment] 2023-08-30 06:33
Closing as duplicate.

**Closed by pchaurasia14** 2023-08-30 06:33 UTC
Labels: Work Item
